------------------------------------------------------------------------
-- Substrate.Algebra.ParityKernel.Universal
--
-- ◆ip-abel-α — the UNIVERSAL "even ≠ prime" lemma: the mod-2 kernel of the
-- generator-count is generated by grade-2 (pair) elements. Over any generator
-- alphabet Gen, a Word is even (count-parity 𝟘) IFF it decomposes into
-- adjacent generator-PAIRS. This is "even = 2·k" as a word-level construction,
-- and it SUBSUMES the ℕ converse (Gen = ⊤).
--
--   Gr2Gen w        — w is a product of generator-pairs (g2-nil / g2-pair)
--   Gr2Gen→even     — a paired word is even (char-2: a pair leaves parity fixed)
--   even→Gr2Gen     — an even word pairs up (the trivial even-length pairing)
--
-- --safe --without-K, no postulates/holes.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Algebra.ParityKernel.Universal where

open import Substrate.Foundation.Nat using (ℕ; zero; suc)
open import Substrate.Foundation.Eq using (_≡_; refl; trans; sym)
open import Substrate.Foundation.Empty using (⊥-elim)
open import Substrate.Algebra.F2 using (F₂; 𝟘; 𝟙; _+_; +-assoc; +-identityˡ; 𝟙≢𝟘)
open import Substrate.Algebra.N-to-F2-Parity using (parity)
open import Substrate.Groups.Coxeter.Word using (Word; []; _∷_)

module _ {Gen : Set} where

  -- number of generators (ℓ = 1 per generator: the count that parity reads).
  count : Word Gen → ℕ
  count []      = zero
  count (_ ∷ w) = suc (count w)

  wpar : Word Gen → F₂
  wpar w = parity (count w)

  -- w is a product of generator-PAIRS (grade-2 elements).
  data Gr2Gen : Word Gen → Set where
    g2-nil  : Gr2Gen []
    g2-pair : (a b : Gen) {w : Word Gen} → Gr2Gen w → Gr2Gen (a ∷ b ∷ w)

  -- prepending a pair leaves the count-parity fixed (characteristic 2).
  par-ss : (n : ℕ) → parity (suc (suc n)) ≡ parity n
  par-ss n = trans (sym (+-assoc 𝟙 𝟙 (parity n))) (+-identityˡ (parity n))

  wpar-pair : (a b : Gen) (w : Word Gen) → wpar (a ∷ b ∷ w) ≡ wpar w
  wpar-pair a b w = par-ss (count w)

  -- FORWARD: a pair-decomposed word is even.
  Gr2Gen→even : {w : Word Gen} → Gr2Gen w → wpar w ≡ 𝟘
  Gr2Gen→even g2-nil              = refl
  Gr2Gen→even (g2-pair a b {w} g) = trans (wpar-pair a b w) (Gr2Gen→even g)

  -- CONVERSE ("even = 2·k"): an even word decomposes into pairs. The odd
  -- singleton is impossible (its parity is 𝟙 ≢ 𝟘).
  even→Gr2Gen : (w : Word Gen) → wpar w ≡ 𝟘 → Gr2Gen w
  even→Gr2Gen []          _ = g2-nil
  even→Gr2Gen (a ∷ [])    e = ⊥-elim (𝟙≢𝟘 e)
  even→Gr2Gen (a ∷ b ∷ w) e =
    g2-pair a b (even→Gr2Gen w (trans (sym (wpar-pair a b w)) e))
