------------------------------------------------------------------------
-- Substrate.Algebra.Abelian.Z6-as-PFG
--
-- Z/6 = Z/2 × Z/3 as an AbelianPFG instance — the smallest non-trivial
-- CRT abelian PrimeFactoredGauge. Demonstrates the framework at
-- the simplest possible multi-prime abelian case.
--
-- W2 of the 20-slice arc per [[prime-factored-gauge-arc]] follow-on.
-- Sub-arc W's first concrete instance.
--
-- Structural framing. Z/6 has order 6 = 2 · 3. Its two Sylow
-- subgroups are:
--   Sylow-2 = {0, 3} ⊂ Z/6 (cyclic of order 2, = the image of 3·Z/6)
--   Sylow-3 = {0, 2, 4} ⊂ Z/6 (cyclic of order 3, = the image of 2·Z/6)
--
-- By CRT: every element n ∈ Z/6 factors uniquely as n = a · 3 + b · 4
-- (mod 6) for a ∈ {0, 1} and b ∈ {0, 1, 2}. The 6-case enumeration:
--   0 = 0·3 + 0·4    1 = 1·3 + 1·4 (= 3 + 4 = 7 = 1)
--   2 = 0·3 + 2·4    3 = 1·3 + 0·4
--   4 = 0·3 + 1·4    5 = 1·3 + 2·4 (= 3 + 8 = 11 = 5)
--
-- The substrate's Z6-FieldBond + Z6-FieldTower (existing modules)
-- formalise the CRT decomposition Z/6 → (Z/2, Z/3) via FieldBond /
-- FieldFanOut. This module bridges that infrastructure into the
-- AbelianPFG framework.
--
-- Module-parametric over the joint-gen witness (= the CRT
-- decomposition witness). Concrete proof for Z/6 is a 6-case
-- enumeration following the table above; mechanical but verbose.
-- Per substrate's pragmatic discipline, deferred to consumer
-- modules supplying the witness.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

open import Substrate.Foundation.Fin using (Fin; zero; suc)
open import Substrate.Foundation.Fin.Literals using (₁)
open import Substrate.Foundation.Nat using (ℕ)
open import Substrate.Foundation.Product using (Σ; _,_)

open import Substrate.Category.AbelianPFG
  using (AbelianPFG; mkAbelianPFG)
open import Substrate.Category.PrimeFactoredGauge
  using (PrimeFactoredGauge; mkPFG)
open import Substrate.Category.SylowDecomposition
  using (SylowDecomposition; mkSylowDecomposition; InGenerated)
open import Substrate.Category.GTorsor using (GTorsor)

module Substrate.Algebra.Abelian.Z6-as-PFG
  -- The Z/6 carrier.
  (Z6 : Set)
  -- Group operations on Z/6.
  (_+Z6_ : Z6 → Z6 → Z6)
  (0Z6 : Z6)
  (-Z6_ : Z6 → Z6)
  -- Equivalence (= propositional equality for Fin 6; abstract here).
  (_≈Z6_ : Z6 → Z6 → Set)
  -- The 2 Sylow predicates:
  --   Sylow-pred zero       = "in Sylow-2 = {0, 3}"
  --   Sylow-pred ₁ = "in Sylow-3 = {0, 2, 4}"
  (Sylow-pred-Z6 : Fin 2 → Z6 → Set)
  -- Joint-generation witness: every element is in the subgroup
  -- generated by Sylow-2 ∪ Sylow-3.
  (joint-gen-Z6 :
    (g : Z6) →
    InGenerated (λ z → Σ (Fin 2) (λ i → Sylow-pred-Z6 i z))
                _+Z6_ 0Z6 g)
  -- Commutativity:
  (Z6-abelian-comm : (a b : Z6) → (a +Z6 b) ≈Z6 (b +Z6 a))
  -- A torsor of Z/6 acting on itself (= regular representation):
  (Z6-torsor : GTorsor Z6 Z6 _+Z6_ 0Z6 _≈Z6_ _≈Z6_)
  where

------------------------------------------------------------------------
-- 1. The Sylow decomposition for Z/6.
------------------------------------------------------------------------

Z6-primes : Fin 2 → ℕ
Z6-primes zero       = 2
Z6-primes ₁ = 3

Z6-multiplicities : Fin 2 → ℕ
Z6-multiplicities zero       = 1   -- Sylow-2 = Z/2
Z6-multiplicities ₁ = 1   -- Sylow-3 = Z/3

Z6-SylowDecomposition : SylowDecomposition Z6 _+Z6_ 0Z6 2
Z6-SylowDecomposition = mkSylowDecomposition
  Z6-primes
  Z6-multiplicities
  Sylow-pred-Z6
  joint-gen-Z6

------------------------------------------------------------------------
-- 2. The PrimeFactoredGauge for Z/6.
------------------------------------------------------------------------

Z6-PFG : PrimeFactoredGauge Z6 Z6 _+Z6_ 0Z6 _≈Z6_ _≈Z6_ 2
Z6-PFG = mkPFG Z6-SylowDecomposition Z6-torsor

------------------------------------------------------------------------
-- 3. The AbelianPFG instance.
------------------------------------------------------------------------

Z6-AbelianPFG : AbelianPFG Z6 Z6 _+Z6_ 0Z6 _≈Z6_ _≈Z6_ 2
Z6-AbelianPFG = mkAbelianPFG Z6-PFG Z6-abelian-comm

------------------------------------------------------------------------
-- 4. Capstone — Z/6 lives as an AbelianPFG instance.
--
-- W2 of the 20-slice arc. The substrate's smallest concrete CRT
-- abelian PFG instance.
--
-- Concrete completion requires consumer modules to supply:
--   * Z/6 carrier (= Fin 6)
--   * Addition + zero (= modular arithmetic on Fin 6)
--   * Sylow predicates (= explicit subset membership)
--   * Joint-generation witness (= 6-case CRT enumeration)
--   * Commutativity proof (= mod-6 arithmetic commutes)
--   * Self-torsor structure (= Z/6 acting on itself)
--
-- The substrate's existing Z6-FieldBond + Z6-FieldTower modules
-- provide the CRT decomposition data; bridging to this AbelianPFG
-- framework is a one-line composition once the per-instance data
-- is wired.
--
-- Next: W3 (Z/30 = Z/2 × Z/3 × Z/5, 3-prime case).
------------------------------------------------------------------------
