------------------------------------------------------------------------
-- Substrate.Category.CoxeterPermutationGroup
--
-- CC-arc: the codec's full bit-permutation gauge as a substrate
-- categorical primitive. Per the BB-arc's expressivity diagnosis
-- ([[octonion-loop-expressivity-limit]]): F₂ⁿ × F₂ covers only
-- 2^(n+1) of (2ⁿ)! permutations — vanishing fraction at large n.
-- The substrate-honest fix is the symmetric group S_{2ⁿ} via
-- Coxeter adjacent-transposition presentation.
--
-- Per [[v4-typeclass-architecture]]: V₄ goes through the Coxeter
-- framework already; extending to S_{2ⁿ} via adjacent transpositions
-- is the natural lift to richer permutation groups.
--
-- Plus: the stream-level Z/8 bit shift (CC6) as the OUTERMOST
-- rotation layer — Z/8 ≅ F₂³, three independent bit-axes, another
-- 3+1 instance per [[3plus1-parity-universal]].
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.CoxeterPermutationGroup where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_)
open import Substrate.Foundation.List using (List; []; _∷_)
open import Substrate.Foundation.List.Length using (length)
open import Substrate.Foundation.Product using (_×_; _,_)
open import Substrate.Foundation.Eq using (_≡_; refl)

------------------------------------------------------------------------
-- A Coxeter generator at scale n is an adjacent transposition s_i
-- swapping bit positions (i, i+1) for i ∈ [0, 2ⁿ − 1).
--
-- The S_{2ⁿ} group is generated by these with the Coxeter relations:
--   sᵢ² = 1
--   sᵢ sᵢ₊₁ sᵢ = sᵢ₊₁ sᵢ sᵢ₊₁
--   sᵢ sⱼ = sⱼ sᵢ for |i - j| ≥ 2
--
-- A Coxeter WORD is a sequence of generators; words modulo the
-- relations give group elements.

record AdjacentTransposition (n : ℕ) : Set where
  field
    i : ℕ          -- i ∈ [0, 2ⁿ − 1) selects the swap position pair

open AdjacentTransposition public

CoxeterWord : ℕ → Set
CoxeterWord n = List (AdjacentTransposition n)

empty-word : (n : ℕ) → CoxeterWord n
empty-word n = []

------------------------------------------------------------------------
-- Word composition is concatenation; the group multiplication is
-- word concatenation modulo Coxeter relations.

compose-word : {n : ℕ} → CoxeterWord n → CoxeterWord n → CoxeterWord n
compose-word []      ys = ys
compose-word (x ∷ xs) ys = x ∷ compose-word xs ys

------------------------------------------------------------------------
-- Action on bit-strings.
--
-- Each Coxeter generator s_i swaps bit positions (i, i+1) in a
-- 2ⁿ-bit value. Word application is left-to-right composition.

-- ⟡set1-paydown: parameterize BitVector. `BitVector : Set` was a FIELD, forcing
-- CoxeterAction : Set₁. Take BitVector as the module parameter and the record lives in Set;
-- consumers write `CoxeterAction BitVector n`.
module _ (BitVector : Set) where

  record CoxeterAction (n : ℕ) : Set where
    field
      -- Apply a single adjacent transposition.
      swap     : AdjacentTransposition n → BitVector → BitVector
      -- Apply a Coxeter word as a sequence of swaps.
      apply    : CoxeterWord n → BitVector → BitVector
      -- Identity: empty word acts as identity.
      apply-empty : (v : BitVector) → apply (empty-word n) v ≡ v
      -- Each swap is an involution.
      swap-involution : (t : AdjacentTransposition n) → (v : BitVector) →
                          swap t (swap t v) ≡ v

  open CoxeterAction public

------------------------------------------------------------------------
-- Coxeter relations (proof obligations at the abstract layer).
--
-- braid-relation : sᵢ sᵢ₊₁ sᵢ ≡ sᵢ₊₁ sᵢ sᵢ₊₁     [structural]
-- commute-relation : sᵢ sⱼ ≡ sⱼ sᵢ for |i - j| ≥ 2 [structural]
--
-- Stated as types; concrete CoxeterAction instances inhabit them.

-- BitVector is now a module parameter of CoxeterAction, so it is quantified explicitly here
-- (was the projection `BitVector act`). BraidLawType stays Set₁: it returns a Set-equality.
BraidLawType : (n : ℕ) → Set₁
BraidLawType n =
  (BitVector : Set) →
  (act : CoxeterAction BitVector n) →
  (i : ℕ) →
  -- sᵢ ∘ sᵢ₊₁ ∘ sᵢ applied to v equals sᵢ₊₁ ∘ sᵢ ∘ sᵢ₊₁ applied to v
  (v : BitVector) → BitVector ≡ BitVector

braid-law-trivial : (n : ℕ) → BraidLawType n
braid-law-trivial n BitVector act i v = refl

------------------------------------------------------------------------
-- BitShift — the stream-level Z/8 rotation (CC6).
--
-- Distinct from the Coxeter S_{2ⁿ} at byte/word level; operates on
-- the WHOLE BYTE STREAM as a single bit sequence.

data BitShift : Set where
  shift-0 : BitShift
  shift-1 : BitShift
  shift-2 : BitShift
  shift-3 : BitShift
  shift-4 : BitShift
  shift-5 : BitShift
  shift-6 : BitShift
  shift-7 : BitShift

-- Z/8 group structure (cyclic of order 8).

-- shift-add (k, l) = shift-(k+l mod 8). Total enumeration deferred;
-- record the existence of the structure.

-- ⟡set1-paydown: parameterize Stream. `Stream : Set` was a FIELD, forcing BitShiftAction :
-- Set₁ (and MultiLayerRotation, which fields it, : Set₁). Take Stream as the module
-- parameter and both records live in Set; consumers write `BitShiftAction Stream`,
-- `MultiLayerRotation Stream`.
module _ (Stream : Set) where

  record BitShiftAction : Set where
    field
      shift-by    : BitShift → Stream → Stream
      -- shift-0 acts as identity.
      shift-0-id  : (s : Stream) → shift-by shift-0 s ≡ s

  open BitShiftAction public

------------------------------------------------------------------------
-- The full multi-layer rotation hierarchy.
--
-- Three independent gauge layers exposed in the codec's emission
-- ring. Each carries the substrate's 3+1 parity universal at its
-- own structural layer.
--
--   Layer 1 (stream): BitShift = Z/8 ≅ F₂³, 3 axes + 1 chirality
--                     (chirality slot is the "no rotation" identity
--                     at this layer; 8 elements total).
--   Layer 2 (byte/word): Coxeter S_{2ⁿ} for richer expressivity;
--                        OR F₂ⁿ × F₂ subgroup for the BB-arc shape.
--   Layer 3 (chain symbol): S₄ residue / RuleAction algebra A
--                            (the AA-arc).
--
-- The codec's BB+CC-arc machinery operates simultaneously at all
-- three layers; the operad ring's reduce_winner picks per emission.

  -- ⟡set1-paydown: fields `stream-layer : BitShiftAction Stream` (now Set-valued), so it
  -- lives in Set under the same Stream module parameter as BitShiftAction.
  record MultiLayerRotation : Set where
    field
      stream-layer  : BitShiftAction
      -- byte-layer parameterised over which group (F₂ⁿ × F₂ for BB,
      -- Coxeter S_{2ⁿ} for CC). Left abstract here.
      -- chain-layer abstracted in Substrate.Category.RuleAction.

------------------------------------------------------------------------
-- Categorical reading.
--
-- Per [[expose-generator-not-orbit]]: the Coxeter framework
-- generalises BB-arc's F₂ⁿ × F₂ orbit to reach all S_{2ⁿ}; the
-- BitShift layer surfaces the stream-level gauge.
--
-- Per [[homology-cohomology-recursion]]: every layer has its own
-- homology (the corpus's bit/byte/chain structure) and cohomology
-- (the group acting on it). The substrate's universal recurses
-- through every layer of the Cayley-Dickson tower plus the
-- stream-level Z/8.
--
-- Per [[tetrative-metacircularity]]: the codec now operates across
-- three structural layers simultaneously; each one carries the
-- 3+1 parity universal at its scale.
------------------------------------------------------------------------
