------------------------------------------------------------------------
-- Substrate.Category.LieAlgebra
--
-- The categorical primitive for Lie algebras: anti-commutative
-- algebra (L1) extended with the Jacobi identity:
--   [x, [y, z]] + [y, [z, x]] + [z, [x, y]] ≡ 0V
--
-- L2 of the 20-slice L-arc. Built ON TOP OF L1
-- [[AntiCommutativeAlgebra]] per substrate convention (layered
-- specialisation: minimum-axiom record below, additional axioms in
-- specialised records above).
--
-- Per [[categorical-name-first]]: "Lie algebra" is the standard
-- name; the universal property is "associative algebra freely
-- generated by V mod the relations [x,y] = xy - yx" (= universal
-- enveloping algebra adjunction, L18). The bracket-only axiomatic
-- presentation (ACA + Jacobi) is the standard categorical capture.
--
-- Per [[continuous-via-discrete-inference-rules]]: the carrier is
-- abstract (user-supplied Set); the Lie structure is the substrate's
-- content. Specific instances:
--   * sl₂ (L14): 2×2 traceless matrices, [A,B] = AB - BA
--   * so₃ (L15): 3-dim skew-symmetric matrices, [A,B] = AB - BA
--   * Bivector at HodgeDim4 (L6): ∧² of 4-dim F₂-space
--   * MonsterLieAlgebra (L19): Borcherds-Kac-Moody Lie algebra
--     associated to V♮ via Borcherds 1992
--
-- Per [[homology-cohomology-recursion]]: a Lie algebra's cohomology
-- H*(g) is computed via the Chevalley-Eilenberg complex; the
-- substrate's L3 ExteriorAlgebra primitive provides the underlying
-- graded space.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.LieAlgebra where

open import Substrate.Foundation.Level using (Level; _⊔_) renaming (suc to lsuc)
open import Substrate.Foundation.Eq using (_≡_)

open import Substrate.Category.AntiCommutativeAlgebra
  using (AntiCommutativeAlgebra)

private
  variable
    ℓ : Level

------------------------------------------------------------------------
-- The LieAlgebra record.
--
-- Layered specialisation of L1 AntiCommutativeAlgebra:
--   * acaBase : the underlying anti-commutative algebra (V + 0V + +V
--     + bracket _·_ + anti-commutativity)
--   * jacobi : the Jacobi identity
--     [x,[y,z]] + [y,[z,x]] + [z,[x,y]] ≡ 0V
--
-- The bracket _·_ from acaBase is the Lie bracket; common notation
-- [_,_] is derivable as an alias (introduced via re-export).
------------------------------------------------------------------------

record LieAlgebra : Set (lsuc ℓ) where
  constructor mkLieAlgebra
  field
    acaBase : AntiCommutativeAlgebra {ℓ}

  open AntiCommutativeAlgebra acaBase public

  field
    jacobi : (x y z : V) →
             ((x · (y · z)) +V ((y · (z · x)) +V (z · (x · y))))
             ≡ 0V

------------------------------------------------------------------------
-- Bracket notation alias.
--
-- The Lie bracket is the ACA product; standard notation is [_,_].
-- Exported as a convenience alias for downstream sites that prefer
-- the bracket form (e.g., sl₂'s [X,Y] = XY - YX).
------------------------------------------------------------------------

bracket : (L : LieAlgebra {ℓ}) →
          LieAlgebra.V L → LieAlgebra.V L → LieAlgebra.V L
bracket L x y = LieAlgebra._·_ L x y

------------------------------------------------------------------------
-- Capstone — Lie algebra primitive in place.
--
-- L2 of the L-arc. Foundation for:
--   * L6 Bivector.AsExterior (HodgeDim4 ∧²V instance)
--   * L8 LieAlgebra.Morphism (Lie homomorphism layer)
--   * L11-L13 root system / Cartan type bridge (the discrete side
--     of Coxeter ↔ Lie correspondence)
--   * L14 sl₂, L15 so₃ (concrete small-rank Lie algebras)
--   * L18 UniversalEnvelopingAlgebra (the right-adjoint to the
--     forgetful Assoc → Lie functor; gives the substrate's first
--     real adjunction at the algebra level)
--   * L19 MonsterLieAlgebra (Borcherds 1992 V♮-graded Lie algebra)
--
-- After L2: substrate has both commutative (CNAA / X3) and anti-
-- commutative (LieAlgebra / L2) algebraic primitives, spanning the
-- bilinear-product axis.
--
-- Per [[universal-property-discipline]]: future arc will name the
-- forgetful functor LieAlg → Set explicitly + its left adjoint (free
-- Lie algebra); L18 names the universal enveloping algebra functor
-- (Lie → Assoc) and its right adjoint.
--
-- Next: L3 ExteriorAlgebra (graded ACA at odd degrees).
------------------------------------------------------------------------
