------------------------------------------------------------------------
-- Substrate.Category.OrphanAudit
--
-- Substrate-side enumeration of REMAINING ORPHAN CANDIDATES — "X ↦
-- S(X)" assignments across the substrate that have not yet been
-- promoted to M1 Functor or M2 NaturalTransformation instances per
-- [[grothendieck-coherence-rule]].
--
-- M10 of the M-arc (part 2; part 1 = PrimitivesAll + PrimitiveInstances
-- refresh).
--
-- This module deliberately contains NO TYPE-LEVEL CONTENT (no records,
-- no values) — it is a structured commentary catalogue, the substrate's
-- standing checklist for the NEXT coherence arc (anticipated as N-arc
-- or similar).
--
-- Per [[grothendieck-coherence-rule]] + [[homology-cohomology-
-- recursion]]: orphan-audit is the SECOND-LEVEL cohomology over the
-- M-arc's first-level closure. Each iteration of the coherence-
-- closure recursion exposes a new layer of latent gaps; this
-- module documents the current view.
--
-- Per [[expose-generator-not-orbit]]: the audit names the GENERATORS
-- of the next-arc work (= each remaining orphan + its functorial
-- target); the ORBIT (= the concrete instance modules) lands later.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.OrphanAudit where

------------------------------------------------------------------------
-- 1. Remaining functorial closures (Functor-shaped orphans).
--
-- Substrate primitives whose "X ↦ S(X)" assignment is NOT yet named
-- as a substrate M1 Functor. Each item below is a candidate slice
-- for the next coherence arc.
--
-- HIGH PRIORITY (load-bearing for prior arcs):
--
--   * Aut(_) as functor: Z2 AutomorphismGroup is parametric on a V +
--     preservation predicate; the substrate-level functor "carrier
--     ↦ Aut(carrier)" is implicit but not named. Lift candidate:
--     Substrate.Category.AutomorphismGroup.AsFunctor with Aut : Sets
--     → Group as M1 Functor.
--
--   * CategoryOf(_) as 2-functor: Z5 CategoryOf produces a CategoryOf
--     from substrate-primitive data; the assignment is functorial in
--     the primitive data. Lift candidate: Substrate.Category.
--     CategoryOf.AsFunctor.
--
--   * GrothendieckConstruction as functor: Z3 ∫F takes a functor F :
--     Base → Cat and produces a total category. The assignment F ↦
--     ∫F is itself a functor (Cat^Base → Cat-over-Base). Lift
--     candidate: Substrate.Category.GrothendieckConstruction.AsFunctor.
--
--   * PFG as functor: T7 PrimeFactoredGauge takes a group + Sylow
--     decomposition + charts and produces a PFG. The assignment
--     could be made functorial in (group-morphism, Sylow-respecting).
--     Lift candidate: Substrate.Category.PrimeFactoredGauge.AsFunctor.
--
-- MEDIUM PRIORITY (algebra-level):
--
--   * S²-Lift, S¹-Lift (X1, X2): the discrete→continuous lift
--     primitives are assignments; lift candidates for the next arc
--     are S¹-Lift.AsFunctor and S²-Lift.AsFunctor.
--
--   * CartanType ↔ RootSystem: L11 + L12 are records; the
--     bidirectional bridge (CartanType ↦ RootSystem; RootSystem ↦
--     CartanType) is functorial in each direction. Lift candidates:
--     two functors + the equivalence-of-categories adjunction.
--
--   * JordanAlgebra extends CNAA: the underlying-CNAA functor
--     JordanAlgebra → CNAA (Jordan ⊂ CNAA) is implicit; M-arc
--     analog: Jordan-AsFunctor with underlying-CNAA-functor.
--
-- LOW PRIORITY (sporadic-side):
--
--   * HappyFamily.AsTree (Z8): the descent-tree is parametric per
--     HappyFamily member; the assignment HF-member ↦ DescentTree-
--     node is a functor from the HF index category to DescentTree
--     category. Lift candidate: HappyFamily.AsFunctor.
--
--   * Monster's 4 views as natural transformations: AsCoalgebra,
--     AsPresented, AsAutGriess, MonsterLieAlgebra are 4 substrate
--     identifications of M; the bridges between views are nat-trans
--     candidates (T4 GaloisAdjunction already bridges 1+2; Z9
--     bridges to 3; L19 connects to 4).
--
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 2. Remaining naturality witnesses (NaturalTransformation-shaped).
--
-- Substrate-level transformations that should be M2 NaturalTrans-
-- formation instances but are currently stated per-instance.
--
--   * Bijection-morphisms between F₂-Linear maps: the substrate's
--     Bijection primitive carries a 2-sided inverse; this IS a
--     dagger structure (M4 candidate) at the F₂-Linear category.
--     Lift candidate: Substrate.Algebra.F2.Linear.AsDaggerCategory.
--
--   * GaugeTorsor representatives as nat-trans: the 168-orbit at
--     HodgeDim4 (Reserved↔SelfDual) is a torsor; its actions on
--     adjacent functors (Λ², Hodge ★) form natural transformations
--     in the GL(3, F₂)-equivariance structure. Lift candidate:
--     Substrate.Algebra.GL3F2.GaugeAsNaturalTransformation.
--
--   * GaloisAdjunction's unit + counit (T4): currently the
--     adjunction's natural transformations are implicit in the
--     forward/backward functor pair; lift candidate is making them
--     M2 instances explicitly.
--
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 3. Remaining monoidal closures (M3 SymmetricMonoidal-shaped).
--
-- Substrate categories that have or should have ⊗ + I + σ structure.
--
--   * Vect (F₂-Linear): ⊗ = tensor product of vector spaces, I = F₂,
--     σ = swap. The substrate's F₂.Linear could be packaged as a
--     SymmetricMonoidal instance.
--
--   * ChainComplex / Cone categories: ⊗ = total complex of tensor.
--
--   * GradedAlgebra (= ExteriorAlgebra category): ⊗ = graded tensor
--     with sign rule, σ = (-1)^{|x||y|} · swap. This is the canonical
--     "graded commutative" example.
--
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 4. Remaining dagger closures (M4 DaggerCategory-shaped).
--
--   * F₂-Linear with † = transpose: canonical instance.
--   * HasOrder-at-order-2 endomaps: each is a dagger on a one-object
--     category (Hodge ★ at HodgeDim4 is the substrate's canonical).
--   * Bijection: forward + backward IS a dagger structure on Bij.
--
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 5. Capstone — orphan-audit standing checklist.
--
-- M10 (part 2) of the M-arc. With M10 landed:
--   * M-arc's 9 functorial closures (M1-M9) are in place
--   * The remaining orphan inventory above is documented for the
--     next coherence arc
--   * Each row of the audit is a candidate slice
--
-- Per [[grothendieck-coherence-rule]]: each Grothendieck lift will
-- reveal a NEW layer of orphans (above the current audit). The
-- substrate's standing pattern: audit → close highest-priority
-- gaps → audit → close → audit → close (recursive coherence
-- iteration; the user's "fold and reclose Grothendieck a few times").
--
-- Per [[homology-cohomology-recursion]]: this audit IS the
-- cohomology-level structure over the substrate's current homology
-- (= existing functorial closures); the next arc's homology will
-- become a new cohomology level over it.
--
-- No type-level content beyond this module. Treat as substrate-
-- internal documentation; consumers can read for orientation on the
-- coherence-closure trajectory.
------------------------------------------------------------------------
