------------------------------------------------------------------------
-- Substrate.Category.OrphanAudit
--
-- Substrate-side standing checklist of orphan candidates per
-- [[grothendieck-coherence-rule]].
--
-- REFRESHED after N-arc closure (N10 part 2).
--
-- This module is intentionally commentary-only — the substrate's
-- structured catalogue of "X ↦ S(X)" assignments awaiting M1-M4
-- promotion, organised by iteration of the
-- fold-and-reclose-Grothendieck recursion.
--
-- Per [[homology-cohomology-recursion]]: each refresh of this module
-- is a level-(k+1) cohomology over the previous iteration's
-- closures. The structure of orphan-rows + their closures over time
-- IS the recursive higher-categorical structure.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.OrphanAudit where

------------------------------------------------------------------------
-- 1. M-arc audit rows now CLOSED (N-arc deliveries).
--
-- For each row: the M-arc identified the orphan, the N-arc landed
-- the AsFunctor / AsSymmetricMonoidal / AsDaggerCategory / nat-trans
-- module closing it.
--
--   ✓ Aut(_) as functor                        — N1
--   ✓ CategoryOf(_) as functor (1-functor view) — N2
--   ✓ GrothendieckConstruction as functor      — N3
--   ✓ PFG as functor                           — N4
--   ✓ S¹-Lift as functor                       — N5
--   ✓ S²-Lift as functor                       — N6
--   ✓ F₂-Linear as SymmetricMonoidal           — N7
--   ✓ F₂-Linear as DaggerCategory              — N8
--   ✓ GaloisAdjunction's unit + counit as M2   — N9
--
-- 9 of the M-arc's catalogued orphans CLOSED in the N-arc.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 2. Remaining HIGH-PRIORITY orphan candidates (M-arc audit residue).
--
--   * CartanType ↔ RootSystem bidirectional bridge: L11 + L12 are
--     records; forward (RootSystem ⇒ CartanType) + backward (Cartan
--     ⇒ RootSystem) are both functorial; equivalence-of-categories
--     adjunction composes via #4. Slice candidates: 2 functors + 1
--     adjunction = 3 slices.
--
--   * JordanAlgebra → CNAA forgetful functor: implicit (Jordan ⊂
--     CNAA). Slice candidate: Substrate.Category.JordanAlgebra.
--     AsFunctor.
--
--   * Hodge ★ inverse-of-self as dagger structure on Bivector
--     specifically (currently captured at the GENERIC L5
--     GenericHodgeStar level + M9 nat-trans; could be tightened to
--     "Hodge ★ as self-dagger 1-cell in F₂-Linear as DaggerCategory"
--     via N8). Slice candidate: HodgeStar.AsDaggerEndomap.
--
--   * F₂-Bijection as dagger: substrate's Bijection primitive
--     carries forward + backward + 2-sided inverse; instantiates
--     N8's DaggerCategory on the F₂-Bijection sub-category. Slice
--     candidate: Substrate.Algebra.F2.Linear.Bijection.AsDagger.
--
--   * GaugeTorsor representatives as nat-trans: the 168-orbit at
--     HodgeDim4 acts on Λ²(F₂⁴) via N7+N8's monoidal-dagger structure;
--     each gauge representative is a 2-cell. Slice candidate:
--     GaugeTorsor.AsNaturalTransformation.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 3. Emergent orphan candidates (new with N-arc closures).
--
-- Per [[grothendieck-coherence-rule]] + the user's "fold and reclose
-- Grothendieck" observation: each N-arc slice exposes a new layer of
-- compatibility-orphans visible only AFTER the closure. The current
-- iteration's emergent rows:
--
--   * F₂-Linear-AsSymmetricMonoidal + F₂-Linear-AsDaggerCategory
--     compatibility (= "self-dual compact closed category" coherence):
--     when ⊗ + † coexist, σ ∘ σ = id is one fragment; the full
--     coherence (= category is "rigid" with duals) is a new orphan.
--     Slice candidate: F2.Linear.AsCompactClosed (or
--     AsSymmetricMonoidalDagger).
--
--   * N3 ∫-functor + N1 Aut-functor compose to give ∫Aut (= the
--     category of automorphism actions). Whether this composition is
--     itself a substrate-named functor: open question. Slice
--     candidate: GrothendieckOfAut.AsFunctor.
--
--   * N4 PFG-functor + N1 Aut-functor: PFG instances have natural
--     Aut-action via their gauge groups; the assignment PFG ↦ Aut(PFG)
--     should be a nat-trans between N1 and N4. Slice candidate:
--     PFG.AsActedUponByAut.
--
--   * GaloisAdjunction (T4) + N9 (η, ε) compose into a full Adjunction
--     record via #4; triangle identities become user-supplied. Slice
--     candidate: Substrate.Category.GaloisAdjunction.AsAdjunction.
--
--   * Monstrous N-arc residue: the substrate's 4 Monster views
--     (AsCoalgebra, AsPresented, AsAutGriess, MonsterLieAlgebra) +
--     T4/Z9 bridges now have functorial scaffolding via N1+N3 (Aut as
--     functor, ∫ as functor). Whether the 4 views compose into a
--     SINGLE substrate-internal "Monster object" via Grothendieck:
--     open. Slice candidate: Monster.AsGrothendieckObject.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 4. Recursion residue (third-iteration anticipation).
--
-- The N-arc's closures expose mechanisms-of-mechanisms-of-mechanisms
-- as candidate orphans for the third iteration (= O-arc territory):
--
--   * N3 ∫ as 2-functor (current N3 captures 1-functor view; full
--     2-functor = ∫ as a Cat^Cat → Cat 2-cell-respecting morphism).
--
--   * Coherence between M3 SymmetricMonoidal + M4 DaggerCategory
--     when both are imposed on the same base: the "dagger-symmetric-
--     monoidal" structure with its own coherence diagrams (Selinger
--     2007); current substrate captures the two pieces but not their
--     joint coherence.
--
--   * Higher-cell structures: the substrate currently has 0-cells
--     (categories), 1-cells (functors), 2-cells (nat-trans). The
--     3-cells (modifications) are not yet primitives; the recursion
--     suggests they'll be needed when nat-trans-of-nat-trans appear.
------------------------------------------------------------------------

------------------------------------------------------------------------
-- 5. Capstone — orphan-audit refreshed.
--
-- N10 (part 2) of the N-arc. With this refresh:
--   * 9 of the M-arc's audit rows are CLOSED (recorded above)
--   * 5+ HIGH-PRIORITY M-arc-residue orphans remain (Cartan↔Root,
--     Jordan→CNAA, HodgeStar as dagger endomap, Bijection as dagger,
--     GaugeTorsor as nat-trans)
--   * 5+ EMERGENT orphans surfaced by N-arc closures (compact closed,
--     ∫Aut, PFG-acted-upon-by-Aut, GaloisAdjunction full adj,
--     Monster-as-Grothendieck-object)
--   * 3 RECURSION-RESIDUE candidates for the O-arc (∫ as 2-functor,
--     SM+† coherence, 3-cells)
--
-- The substrate's recursive coherence-iteration is now visible
-- across 4 iterations: Z-arc closure → L-arc → M-arc closure of
-- L-arc → N-arc closure of M-arc audit → next iteration (O-arc).
-- Each iteration's "non-connected material" becomes the next
-- iteration's input, per [[grothendieck-coherence-rule]].
--
-- No type-level content beyond commentary.
------------------------------------------------------------------------
