------------------------------------------------------------------------
-- Substrate.Category.ReedMullerHierarchy
--
-- EE-arc: Reed-Muller code family RM(r, m) as a substrate primitive.
-- Parameters: order r, dimension m; length 2^m, dimension Σ C(m, i),
-- minimum distance 2^(m−r).
--
-- Per [[expose-generator-not-orbit]]: GL(m, F₂) is the gauge generator;
-- RM(r, m) is its invariant filtration over F₂^(2^m). Each r-step in
-- the hierarchy is one orbit-decomposition layer.
--
-- Per [[168-tower-as-fanout]] at m = 3: |GL(3, F₂)| = 168 = 2³ · 3 · 7
-- — the substrate's Sylow triple. RM(1, 3) = Hamming(8, 4) is the
-- GL(3, F₂)-invariant first-order code; the codec's EE2 empirical
-- finding is that compression gain lives in RM(2, 3) \ RM(1, 3).
--
-- Per the user's RM(1, 3) intuition (2026-05-21): F₇ at length 7 IS
-- Hamming(7, 4); extended to length 8 IS RM(1, 3). The substrate's
-- compression structure reaches one level higher in the hierarchy
-- than first-order RM would predict.
--
-- Per [[3plus1-parity-universal]]: RM(1, m) at any m has weights
-- {0, 2^(m−1), 2^m} — a generalised 3+1 at every dimension.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.ReedMullerHierarchy where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_; _*_; _∸_; _≤_; z≤n; s≤s)
open import Data.List using (List; []; _∷_; length)
open import Substrate.Foundation.Product using (_×_; _,_; Σ-syntax)
open import Substrate.Foundation.Eq using (_≡_; refl)

------------------------------------------------------------------------
-- Parameters of an RM code.

record RMParams : Set where
  field
    m : ℕ                -- dimension; length = 2^m
    r : ℕ                -- order; r ≤ m by convention

open RMParams public

-- length 2^m as a computation.

pow2 : ℕ → ℕ
pow2 zero    = 1
pow2 (suc n) = 2 * pow2 n

length-of : RMParams → ℕ
length-of p = pow2 (m p)

------------------------------------------------------------------------
-- Reed-Muller dimension k(r, m) = Σ_{i=0}^{r} C(m, i).
--
-- Stated structurally; concrete instances enumerate the formula or
-- use the binomial recursion C(n, k) = C(n−1, k−1) + C(n−1, k).

choose : ℕ → ℕ → ℕ
choose _ zero          = 1
choose zero (suc _)    = 0
choose (suc n) (suc k) = choose n k + choose n (suc k)

rm-dimension : RMParams → ℕ
rm-dimension p = go (r p)
  where
    go : ℕ → ℕ
    go zero    = choose (m p) zero
    go (suc r) = choose (m p) (suc r) + go r

-- Minimum distance 2^(m − r).

rm-min-distance : RMParams → ℕ
rm-min-distance p = pow2 (m p ∸ r p)

------------------------------------------------------------------------
-- A Reed-Muller code abstract record. The carrier is the F₂-linear
-- subspace of F₂^(length) generated by monomials of degree ≤ r.

record ReedMullerCode (p : RMParams) : Set₁ where
  field
    -- The codeword type.
    Codeword : Set
    -- Zero codeword.
    zero-cw  : Codeword
    -- Addition (F₂-linear).
    add      : Codeword → Codeword → Codeword
    -- Codewords form a group under addition.
    add-id-l : (c : Codeword) → add zero-cw c ≡ c
    add-inv  : (c : Codeword) → add c c ≡ zero-cw       -- F₂ involution

open ReedMullerCode public

------------------------------------------------------------------------
-- Inclusion lattice: RM(r, m) ↪ RM(r+1, m) for every r < m.
--
-- The embedding is the identity on codewords (every degree-≤-r
-- monomial is also a degree-≤-(r+1) monomial).

record InclusionLattice (m : ℕ) : Set₂ where
  field
    code-at  : (r : ℕ) → r ≤ m → ReedMullerCode (record { m = m ; r = r })
    embed    : (r : ℕ) → (r≤m : r ≤ m) → (sr≤m : suc r ≤ m) →
               Codeword (code-at r r≤m) → Codeword (code-at (suc r) sr≤m)
    embed-respects-zero :
      (r : ℕ) → (r≤m : r ≤ m) → (sr≤m : suc r ≤ m) →
      embed r r≤m sr≤m (zero-cw (code-at r r≤m)) ≡
        zero-cw (code-at (suc r) sr≤m)

open InclusionLattice public

------------------------------------------------------------------------
-- GL(m, F₂) action on codewords.
--
-- RM(r, m) is GL(m, F₂)-invariant: any linear bijection of F₂^m
-- induces a permutation of the 2^m bit positions; the image of any
-- RM(r, m) codeword under this permutation is again an RM(r, m)
-- codeword.
--
-- Per [[expose-generator-not-orbit]]: this IS the generator
-- structure of which RM(r, m) is the orbit decomposition.

record GLAction (p : RMParams) : Set₁ where
  field
    code     : ReedMullerCode p
    GLMat    : Set                      -- an element of GL(m, F₂)
    apply    : GLMat → Codeword code → Codeword code
    -- Identity element acts trivially.
    identity : GLMat
    apply-id : (c : Codeword code) → apply identity c ≡ c

open GLAction public

------------------------------------------------------------------------
-- Connection to Cl(ℝⁿ) Clifford emission (DD9).
--
-- A grade-k blade in Cl(ℝⁿ) at n = 2^m corresponds to a codeword
-- bitmask of Hamming weight k. The codec's empirical finding
-- (EE2): compression gain on substrate corpora lives in the
-- RM(2, 3) \\ RM(1, 3) layer = the EVEN-WEIGHT, NON-AFFINE byte
-- masks. The affine RM(1, 3) layer (weights {0, 4, 8}) provides
-- no compression on tested corpora; the structure is in the
-- RM(2, 3) parity-code layer above it.

record CliffordGradeConnection (p : RMParams) : Set₁ where
  field
    code  : ReedMullerCode p
    -- A codeword's "grade" is its Hamming weight as a basis blade.
    grade : Codeword code → ℕ
    -- Zero codeword has grade 0.
    grade-zero : grade (zero-cw code) ≡ 0

open CliffordGradeConnection public

------------------------------------------------------------------------
-- Diminishing-return statement (EE12 empirical).
--
-- Per [[chain-walk-blocks-rotation-factor]]: the chain walk operates
-- at nibble (4-bit) granularity. Above scale 4 (length 16), there is
-- no additional structure for RM(r, m) masks to align with — the
-- chain walk's units are fixed.
--
-- Stated structurally: ∀ corpus, ∃ scale_max such that searching
-- RM(r, m) at m > scale_max provides no compression gain over RM(r,
-- scale_max). Empirical scale_max ≈ 4 on natural data; ≈ 3 on
-- substrate-internal corpora.
--
-- Per [[negative-findings-corpus-bound]]: the claim is bounded to
-- tested corpora and tested scales.

------------------------------------------------------------------------
-- Sporadic-code off-axis statement (EE13 empirical).
--
-- The binary Golay [24, 12, 8] code's 4096 codewords provide ZERO
-- compression gain on every tested corpus because the 3-byte (24-bit)
-- frame is OFF-AXIS from the chain walk's nibble-aligned structure.
--
-- This is the GENERATOR-vs-ORBIT principle restated:
-- only codes aligned with the substrate's natural F₂ⁿ generator
-- axes (= GL(m, F₂)-invariant RM family at m matching the chain
-- walk's granularity) can contribute compression structure.
-- Sporadic codes lie OFF the generator axis, even when they are
-- mathematically "richer" (perfect, more codewords, exceptional
-- symmetry group).
--
-- Per [[expose-generator-not-orbit]]: this is the principle's
-- empirical face at the level of codec gauge axes.
------------------------------------------------------------------------
