------------------------------------------------------------------------
-- Substrate.Category.SylowDecomposition
--
-- Substrate primitive bundling a group's prime-factor + Sylow subgroup
-- structure + joint-generation property. Foundational for
-- Substrate.Category.PrimeFactoredGauge (T1).
--
-- Per [[prime-factored-gauge-arc]]: the load-bearing piece of the
-- multi-route equivariance generalisation is that the SYLOWS JOINTLY
-- GENERATE G. This holds for both:
--   * abelian groups (where Sylows are normal and G = ∏ Sylows;
--     the Chinese Remainder Theorem case)
--   * simple non-abelian groups (where Sylows are non-normal but
--     no proper subgroup contains representatives of all prime
--     orders — the GL(3, F₂) ≅ PSL(2, 7) case)
--
-- This record packages the data; specific group theorems (Sylow's
-- theorems, classification of finite simple groups, etc.) are
-- external. What's INTERNAL is the joint-generation witness.
--
-- Per [[composite-torsion-euler-substrate]]: Euclid + Extended Euclid
-- are the algorithmic backbone for joint-action composition + CRT-style
-- decomposition. This primitive names the structural target their
-- algorithmic content addresses.
--
-- Per [[expose-generator-not-orbit]]: the generated-subgroup predicate
-- exposes the SYLOWS AS GENERATORS rather than enumerating the
-- subgroup's elements.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.SylowDecomposition where

open import Level using (Level; _⊔_) renaming (suc to lsuc)
open import Substrate.Foundation.Fin using (Fin)
open import Substrate.Foundation.Nat using (ℕ)
open import Substrate.Foundation.Product using (Σ; _,_)

private
  variable
    ℓ : Level

------------------------------------------------------------------------
-- 1. InGenerated — the subgroup generated by a predicate P : G → Set.
--
-- Inductively defined: g ∈ ⟨P⟩ iff g is either (a) in P, (b) the
-- identity, or (c) a product of two such elements.
--
-- This is the standard "generated subgroup" inductive type. Inverse
-- closure is NOT enforced at the predicate level; for the
-- SylowDecomposition use case, each Sylow is closed under inverse
-- (it's a subgroup), so inverse closure of the joint predicate
-- follows from inverse closure of each Sylow.
--
-- The base predicate's level matches G's level; the resulting
-- inductive type also lives at level ℓ. (Substrate convention:
-- predicates over Set ℓ live at Set ℓ where possible.)
------------------------------------------------------------------------

data InGenerated {ℓ : Level} {G : Set ℓ}
                 (P : G → Set ℓ)
                 (_·G_ : G → G → G) (εG : G) : G → Set ℓ where
  base    : (g : G) → P g → InGenerated P _·G_ εG g
  ident   : InGenerated P _·G_ εG εG
  product : (a b : G) →
            InGenerated P _·G_ εG a →
            InGenerated P _·G_ εG b →
            InGenerated P _·G_ εG (a ·G b)

------------------------------------------------------------------------
-- 2. SylowDecomposition — the record.
--
-- Parameters: a group (G, _·G_, εG) and a count n of distinct primes
-- in |G|'s factorization.
--
-- Bundles:
--   * primes : Fin n → ℕ           — the n distinct prime divisors
--   * multiplicity : Fin n → ℕ     — the exponents k_i in |G| = ∏ p_i^k_i
--   * Sylow : Fin n → (G → Set)    — membership predicate for each Sylow
--   * joint-generated              — every g ∈ G is in the subgroup
--                                     generated by ⋃ Sylow
--
-- Presupposed (not internal): primes distinct + |G| matches product +
-- Sylow i is a Sylow-p_i subgroup of correct order. Substrate-pattern
-- minimum-axiom record; the user supplies a coherent Sylow structure.
--
-- INTERNAL (load-bearing): joint-generated. This is the property the
-- multi-route equivariance theorem (T5 in the arc) needs to derive
-- G-equivariance from per-Sylow chart-equivariance.
------------------------------------------------------------------------

record SylowDecomposition
  (G : Set ℓ)
  (_·G_ : G → G → G)
  (εG : G)
  (n : ℕ) : Set (lsuc ℓ) where
  constructor mkSylowDecomposition
  field
    primes          : Fin n → ℕ
    multiplicity    : Fin n → ℕ
    Sylow           : Fin n → (G → Set ℓ)
    joint-generated : (g : G) →
                      InGenerated (λ x → Σ (Fin n) (λ i → Sylow i x))
                                  _·G_ εG g

open SylowDecomposition public

------------------------------------------------------------------------
-- 3. Capstone — primitive in place.
--
-- T0 of the prime-factored-gauge arc per
-- [[prime-factored-gauge-arc]]. With this primitive landed, T1
-- (PrimeFactoredGauge) can compose SylowDecomposition + GTorsor +
-- atlas to deliver the unifying costructure for the
-- multi-route equivariance generalisation.
--
-- Concrete instances expected (T6, T7, T8 of the arc):
--   * GL(3, F₂): 168 = 2³·3·7 — Sylow-2 (S₄'s), Sylow-3, Sylow-7
--     (Singer cycle). Joint-generation = the multi-route theorem
--     from [[multi-route-equivariance-recovery]].
--   * HodgeDim4 GaugeTorsor: same group, applied at the original
--     gauge problem site.
--   * Monster M: 2^46·3^20·...·71 with Sylow witnesses populated from
--     external data; joint-generation cited from CFSG.
--   * Abelian Z/(p₁p₂...pₙ): each Sylow is Z/pᵢ; joint-generation
--     trivial via CRT product decomposition.
--
-- Per [[shadow-architecture]]: this is the foundational primitive
-- enabling T1's costructure. DBE-dominant slice.
------------------------------------------------------------------------
