------------------------------------------------------------------------
-- Substrate.Codes.Hamming.H-7-4-3
--
-- M-7 of the Cocycles structural-migration plan. The Hamming code
-- [7, 4, 3]: length 7, dimension 4, minimum distance 3 (single-bit
-- error correction).
--
-- Defined as a KernelCode: codewords v : Vector 7 satisfy
-- H v ≡ 𝟎ⱽ, where H : Vector 7 → Vector 3 is the parity-check
-- matrix whose columns are the 7 nonzero vectors of F₂³ (taken in
-- "binary representation of the position index" order).
--
-- Standard column ordering (1-indexed positions, columns = binary
-- representations of 1..7, LSB-first):
--   col 1 = (1, 0, 0)
--   col 2 = (0, 1, 0)
--   col 3 = (1, 1, 0)
--   col 4 = (0, 0, 1)
--   col 5 = (1, 0, 1)
--   col 6 = (0, 1, 1)
--   col 7 = (1, 1, 1)
--
-- Encoded as `apply H (basis i) = col(i+1)` since our Fin 7 indexing
-- is 0-based.
--
-- Connection to RM(1, 3) (M-6): the extended Hamming code [8, 4, 4]
-- = RM(1, 3) is obtained from Hamming [7, 4, 3] by adding an overall
-- parity bit; their dual relation (Hamming^⊥ = simplex code,
-- generated by parity-check rows) is the structural bridge to
-- Fano plane PG(2, 2) (M-9).
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Codes.Hamming.H-7-4-3 where

open import Data.Fin using (Fin; zero; suc)
open import Data.Vec using ([]; _∷_)

open import Substrate.Algebra.F2
open import Substrate.Algebra.F2.Vector
open import Substrate.Algebra.F2.Linear.FromImages
open import Substrate.Algebra.F2.Code

------------------------------------------------------------------------
-- The 7 columns of the parity-check matrix H.
------------------------------------------------------------------------

col₁ col₂ col₃ col₄ col₅ col₆ col₇ : Vector 3
col₁ = 𝟙 ∷ 𝟘 ∷ 𝟘 ∷ []
col₂ = 𝟘 ∷ 𝟙 ∷ 𝟘 ∷ []
col₃ = 𝟙 ∷ 𝟙 ∷ 𝟘 ∷ []
col₄ = 𝟘 ∷ 𝟘 ∷ 𝟙 ∷ []
col₅ = 𝟙 ∷ 𝟘 ∷ 𝟙 ∷ []
col₆ = 𝟘 ∷ 𝟙 ∷ 𝟙 ∷ []
col₇ = 𝟙 ∷ 𝟙 ∷ 𝟙 ∷ []

------------------------------------------------------------------------
-- The column dispatcher (0-indexed Fin 7 → 1-indexed column).
------------------------------------------------------------------------

H-cols : Fin 7 → Vector 3
H-cols zero                                  = col₁
H-cols (suc zero)                            = col₂
H-cols (suc (suc zero))                      = col₃
H-cols (suc (suc (suc zero)))                = col₄
H-cols (suc (suc (suc (suc zero))))          = col₅
H-cols (suc (suc (suc (suc (suc zero)))))    = col₆
H-cols (suc (suc (suc (suc (suc (suc _)))))) = col₇

------------------------------------------------------------------------
-- The Hamming [7, 4, 3] code as a KernelCode.
--
-- The parity-check linear map H : Vector 7 → Vector 3 is built via
-- linear-from-images, so apply H (basis i) = H-cols i = col(i+1).
------------------------------------------------------------------------

Hamming-7-4-3 : KernelCode 7 3
Hamming-7-4-3 = record { parity-check = linear-from-images H-cols }
