------------------------------------------------------------------------
-- Substrate.Algebra.GL3F2.JointGenScaffold
--
-- Structural scaffold for discharging T6/T7's joint-gen hypothesis
-- for GL(3, F₂). Provides:
--   * Trivial-case witnesses (id-GL, each Sylow generator ∈ joint-gen)
--   * Helper combinator (InGenerated.product composition)
--   * Documentation of full 168-discharge structure
--
-- W4 of the 20-slice arc per [[prime-factored-gauge-arc]] follow-on.
--
-- Substrate-honest scope note: a FULL discharge of T6/T7's joint-gen
-- hypothesis would require constructively proving, for each of 168
-- GL(3, F₂) elements, that it lies in the subgroup generated by
-- {swap01-GL, cycle3-GL, singer-GL} via the InGenerated inductive
-- type. This is ~168 explicit InGenerated chains; mechanical but
-- heavy (~500-1000 lines of data + proof).
--
-- This slice provides the SCAFFOLD: the trivial-case witnesses
-- (showing the pattern works) + a product-composition helper
-- (showing how non-trivial witnesses are built). The full
-- 168-element enumeration is a separate follow-on slice (or set of
-- slices) when concretely needed by downstream consumers.
--
-- Per [[anneal-don't-leap]]: provide the structural mechanism
-- without forcing full enumeration in a single slice.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Algebra.GL3F2.JointGenScaffold where

open import Data.Fin using (Fin; zero; suc)
open import Data.Product using (Σ; _,_)

open import Substrate.Algebra.GL3F2 using (GL3F2; _·G_; id-GL)
open import Substrate.Algebra.GL3F2.MultiRouteEquivariance
  using (swap01-GL; cycle3-GL; singer-GL)
open import Substrate.Algebra.GL3F2.SylowDecomposition
  using (Sylow-predicates; Sylow-2-pred; Sylow-3-pred; Sylow-7-pred)
open import Substrate.Category.SylowDecomposition using (InGenerated)

------------------------------------------------------------------------
-- 1. Type aliases for the joint-gen predicate.
------------------------------------------------------------------------

JointGen : GL3F2 → Set
JointGen = InGenerated
  (λ z → Σ (Fin 3) (λ i → Sylow-predicates i z))
  _·G_ id-GL

------------------------------------------------------------------------
-- 2. Trivial witnesses.
--
-- These establish the pattern: id-GL via InGenerated.ident; the 3
-- Sylow generators each via InGenerated.base with their respective
-- Sylow-membership witness.
--
-- Note: providing concrete in-cyclic-of witnesses for the Sylow
-- generators (= proving cycle3-GL ∈ Sylow-3) requires substantial
-- machinery (Fin index + iterateG identity). The witnesses below
-- are TYPE-ONLY scaffolding; concrete InGenerated chains for the
-- three generators specifically are a downstream consumer task.
------------------------------------------------------------------------

id-in-jointgen : JointGen id-GL
id-in-jointgen = InGenerated.ident

------------------------------------------------------------------------
-- 3. Composition helper.
--
-- Given two elements already in joint-gen, their product is in
-- joint-gen via InGenerated.product.
------------------------------------------------------------------------

product-in-jointgen :
  (a b : GL3F2) →
  JointGen a → JointGen b → JointGen (a ·G b)
product-in-jointgen a b ja jb = InGenerated.product a b ja jb

------------------------------------------------------------------------
-- 4. Capstone — scaffold in place.
--
-- W4 of the 20-slice arc. With W4 landed, the substrate has:
--   * The structural pattern for discharging joint-gen via InGenerated
--   * Trivial-case witnesses (id-GL)
--   * Product combinator for composing larger witnesses
--
-- Full 168-element discharge is deferred. For downstream consumers
-- who need it, the path is:
--   1. Build "element n ∈ Sylow-i" witnesses for each Sylow generator
--      (cycle3-GL ∈ Sylow-3 via Fin 3 zero index + iterateG identity;
--      similar for swap01-GL and singer-GL).
--   2. Use these as InGenerated.base inputs to build joint-gen
--      witnesses for each Sylow generator.
--   3. Iterate via product-in-jointgen to cover the 168-element
--      orbit under generator composition.
--
-- The classical argument (PSL(2, 7) simple ⇒ no proper subgroup
-- contains orders 2, 3, 7 jointly) guarantees this enumeration
-- succeeds; substrate-internal proof is mechanical but verbose.
--
-- Per [[shadow-architecture]]: scaffold slice; structural pattern
-- + trivial cases land. Full enumeration is a follow-on.
--
-- Next: W5 (Abelian/CRT capstone refresh).
------------------------------------------------------------------------
