------------------------------------------------------------------------
-- Substrate.Algebra.GL3F2.SylowDecomposition
--
-- GL(3, F₂)'s Sylow decomposition: 168 = 2³ · 3 · 7 with cyclic
-- prime-power generators from the multi-route arc (swap01-GL of
-- order 2; cycle3-GL of order 3; singer-GL of order 7).
--
-- T6 of the prime-factored-gauge arc per
-- [[prime-factored-gauge-arc]]. Retrofits the existing multi-route
-- arc's structural content into the generic SylowDecomposition
-- primitive (T0).
--
-- Discipline note: we use CYCLIC SUB-SYLOWS at each prime, not full
-- Sylow subgroups. The full Sylow-2 of GL(3, F₂) is D₈ of order 8;
-- using ⟨swap01-GL⟩ of order 2 captures one CYCLIC subgroup within
-- Sylow-2. This is structurally sufficient for the multi-route
-- generation theorem (per [[multi-route-equivariance-recovery]]:
-- elements of orders 2, 3, 7 jointly generate the simple group of
-- order 168 — full Sylows not required). The naming "Sylow" follows
-- T0's record convention; full-Sylow construction is a follow-on.
--
-- The joint-generation property is TAKEN AS A HYPOTHESIS (= a
-- constructor parameter) — the constructive proof for GL(3, F₂)
-- requires either enumeration of all 168 elements or a structural
-- argument citing PSL(2, 7) simplicity. Both are out of scope for
-- this slice; T6 provides the SylowDecomposition AS A FUNCTION OF
-- the joint-generation witness.
--
-- Once a downstream consumer provides joint-generated, T7 wraps the
-- result with the existing HodgeDim4 GaugeTorsor to give the full
-- PrimeFactoredGauge instance.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Algebra.GL3F2.SylowDecomposition where

open import Substrate.Foundation.Fin.Fin
open import Substrate.Foundation.Fin.To
open import Substrate.Foundation.Fin.Literals using (₁; ₂; ₈)
open import Substrate.Foundation.Nat using (ℕ)
open import Substrate.Foundation.Product using (Σ; _,_)
open import Substrate.Foundation.Eq using (_≡_)

open import Substrate.Algebra.F2.Vector using (Vector)
open import Substrate.Algebra.GL3F2
  using (GL3F2; _·G_; id-GL; applyG; iterateG)
open import Substrate.Algebra.GL3F2.MultiRouteEquivariance.Cycle3GL using (cycle3-GL)
open import Substrate.Algebra.GL3F2.MultiRouteEquivariance.SingerGL using (singer-GL)
open import Substrate.Algebra.GL3F2.MultiRouteEquivariance.Swap01GL using (swap01-GL)
open import Substrate.Category.SylowDecomposition
  using (SylowDecomposition; mkSylowDecomposition; InGenerated)

------------------------------------------------------------------------
-- 1. Pointwise equivalence on GL3F2.
--
-- Same as HodgeDim4.ReservedBridge.GaugeTorsor._≈G_; inlined here to
-- avoid HodgeDim4 dependency.
------------------------------------------------------------------------

infix 4 _≈G_

_≈G_ : GL3F2 → GL3F2 → Set
g₁ ≈G g₂ = (v : Vector 3) → applyG g₁ v ≡ applyG g₂ v

------------------------------------------------------------------------
-- 2. Cyclic-sub-Sylow membership predicates.
--
-- For each Sylow prime p ∈ {2, 3, 7}, the predicate "g is in the
-- cyclic subgroup of order p generated by the corresponding Sylow
-- generator from the multi-route arc."
------------------------------------------------------------------------

in-cyclic-of : (n : ℕ) (gen : GL3F2) → GL3F2 → Set
in-cyclic-of n gen g = Σ (Fin n) (λ k → g ≈G iterateG (toℕ k) gen)

Sylow-2-pred : GL3F2 → Set
Sylow-2-pred = in-cyclic-of 2 swap01-GL

Sylow-3-pred : GL3F2 → Set
Sylow-3-pred = in-cyclic-of 3 cycle3-GL

Sylow-7-pred : GL3F2 → Set
Sylow-7-pred = in-cyclic-of 7 singer-GL

------------------------------------------------------------------------
-- 3. The three Sylow predicates indexed by Fin 3.
------------------------------------------------------------------------

Sylow-predicates : Fin 3 → GL3F2 → Set
Sylow-predicates zero             = Sylow-2-pred
Sylow-predicates ₁       = Sylow-3-pred
Sylow-predicates ₂ = Sylow-7-pred

------------------------------------------------------------------------
-- 4. The 3 Sylow primes and multiplicities (cyclic-sub-Sylow choice).
------------------------------------------------------------------------

Sylow-primes : Fin 3 → ℕ
Sylow-primes zero             = 2
Sylow-primes ₁       = 3
Sylow-primes ₂ = 7

-- Multiplicity = 1 for our cyclic-sub-Sylow choice (order p, not p^k).
-- For FULL Sylow-2 (= D₈) we'd use multiplicity 3; for cyclic-Z/2
-- sub-Sylow, multiplicity is effectively 1. Documented as a known
-- discrepancy with classical "Sylow theory."
Sylow-multiplicities : Fin 3 → ℕ
Sylow-multiplicities zero             = 1  -- cyclic Z/2 ⊂ Sylow-2 (D₈)
Sylow-multiplicities ₁       = 1  -- full Sylow-3 = Z/3
Sylow-multiplicities ₂ = 1  -- full Sylow-7 = Z/7

------------------------------------------------------------------------
-- 5. SylowDecomposition constructor: takes the joint-generation
-- witness as a hypothesis.
--
-- The joint-generation property — that every GL3F2 element is in the
-- subgroup generated by the union of Sylow predicates — is the
-- substrate-side content of the multi-route equivariance theorem at
-- the structure-of-G level. Per [[multi-route-equivariance-recovery]]:
-- this holds for GL(3, F₂) by CFSG + Sylow theorems.
--
-- The constructive proof requires either enumeration of all 168
-- elements or a structural argument citing PSL(2, 7) simplicity;
-- both out of scope for T6. The constructor takes joint-generated
-- as input; downstream consumers (or a future enumeration slice)
-- supply the proof.
------------------------------------------------------------------------

GL3F2-SylowDecomposition-from-joint :
  (joint-gen :
    (g : GL3F2) →
    InGenerated (λ z → Σ (Fin 3) (λ i → Sylow-predicates i z))
                _·G_ id-GL g) →
  SylowDecomposition GL3F2 _·G_ id-GL 3 Sylow-predicates
GL3F2-SylowDecomposition-from-joint joint-gen = mkSylowDecomposition Sylow-primes Sylow-multiplicities joint-gen

------------------------------------------------------------------------
-- 6. Capstone — Sylow-decomposition framework in place for GL3F2.
--
-- T6 of the prime-factored-gauge arc per
-- [[prime-factored-gauge-arc]]. With T6 landed, the Sylow predicates
-- + the parametric constructor are available. T7 will combine this
-- with the existing HodgeDim4 GaugeTorsor to deliver the full
-- PrimeFactoredGauge instance.
--
-- Outstanding obligation: the joint-generated witness. Acceptable
-- discharge paths:
--   * External: cite [[multi-route-equivariance-recovery]] which
--     states it as a meta-theorem (PSL(2, 7) simple ⇒ no proper
--     subgroup contains orders 2, 3, 7 jointly).
--   * Internal: enumerate all 168 GL3F2 elements + per-element
--     chain (~hundreds of lines; mechanical but heavy).
-- For T7, the cite path is adequate; T7 takes joint-generated as
-- a downstream parameter or supplies a placeholder identified as
-- an external citation.
--
-- Per [[shadow-architecture]]: thin retrofit slice; structural
-- content was already in the multi-route arc, T6 just packages it
-- in the generic T0 primitive.
------------------------------------------------------------------------
