------------------------------------------------------------------------
-- Substrate.Category.PrimeFactoredGauge.MultiRouteEquivariance
--
-- The generic multi-route equivariance theorem: any PrimeFactoredGauge
-- recovers equivariance from per-Sylow charts via the atlas-of-charts
-- mechanism. The CONSTRUCTIVE content is the Sylow-product chain that
-- decomposes any gauge element — substrate-side "extended Euclid for
-- groups."
--
-- T5 of the prime-factored-gauge arc per
-- [[prime-factored-gauge-arc]]. With T0-T4 in place, this slice is a
-- thin wrapper around T1's `atlas-decomposition` derived function,
-- formalising it as a named theorem at the substrate level.
--
-- The theorem:
--
--   For any PrimeFactoredGauge τ over (G, X), and any two orbit
--   points x, y ∈ X, there exists a gauge element g ∈ G such that:
--     1. act g x ≈X y                                 (existence)
--     2. g is in the subgroup generated by ⋃ Sylow    (decomposition)
--   The Sylow-product chain in (2) IS the atlas-of-charts
--   decomposition.
--
-- This formalises the substrate-side content of:
-- - [[multi-route-equivariance-recovery]]: now generic, not just
--   GL(3, F₂)-specific
-- - [[composite-torsion-euler-substrate]]: extended Euclid + CRT as
--   the algorithmic backbone for joint-action composition
-- - [[expose-generator-not-orbit]]: the chain is composed of Sylow
--   generators, not orbit-enumerated
--
-- Per [[universal-property-discipline]]: the theorem is the universal
-- property's load-bearing consequence. Any PFG instance inherits it
-- automatically; no per-instance equivariance proof needed.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.PrimeFactoredGauge.MultiRouteEquivariance where

open import Level using (Level; _⊔_)
open import Substrate.Foundation.Fin using (Fin)
open import Substrate.Foundation.Nat using (ℕ)
open import Substrate.Foundation.Product using (Σ; _,_; proj₁; proj₂)

open import Substrate.Category.GTorsor using (act; transitive)
open import Substrate.Category.SylowDecomposition
  using (SylowDecomposition; Sylow; joint-generated; InGenerated)
open import Substrate.Category.PrimeFactoredGauge
  using (PrimeFactoredGauge; factorization; torsor; atlas-decomposition)

private
  variable
    ℓG ℓX ℓEG ℓEX : Level

------------------------------------------------------------------------
-- 1. The generic multi-route equivariance theorem.
--
-- Restates T1's atlas-decomposition as a named structural theorem.
-- The proof body is trivial (= atlas-decomposition itself); the
-- VALUE is naming the result so downstream consumers can cite it
-- generically.
------------------------------------------------------------------------

multi-route-equivariance :
  {G : Set ℓG} {X : Set ℓX}
  {_·G_ : G → G → G} {εG : G}
  {_≈G_ : G → G → Set ℓEG} {_≈X_ : X → X → Set ℓEX}
  {n : ℕ}
  (τ : PrimeFactoredGauge G X _·G_ εG _≈G_ _≈X_ n) →
  (x y : X) →
  Σ G (λ g →
    Σ (_≈X_ (act (torsor τ) g x) y) (λ _ →
      InGenerated (λ z → Σ (Fin n) (λ i → Sylow (factorization τ) i z))
                  _·G_ εG g))
multi-route-equivariance τ x y = atlas-decomposition τ x y

------------------------------------------------------------------------
-- 2. Convenient projections.
--
-- Pull out the parts of the multi-route witness as named functions
-- for downstream readability.
------------------------------------------------------------------------

-- The gauge element connecting two orbit points.
gauge-element :
  {G : Set ℓG} {X : Set ℓX}
  {_·G_ : G → G → G} {εG : G}
  {_≈G_ : G → G → Set ℓEG} {_≈X_ : X → X → Set ℓEX}
  {n : ℕ}
  (τ : PrimeFactoredGauge G X _·G_ εG _≈G_ _≈X_ n) →
  X → X → G
gauge-element τ x y = proj₁ (multi-route-equivariance τ x y)

-- The Sylow-decomposition chain witnessing that the gauge element
-- lies in the subgroup generated by the Sylows. The substrate-side
-- "extended Euclid for groups" content.
sylow-chain :
  {G : Set ℓG} {X : Set ℓX}
  {_·G_ : G → G → G} {εG : G}
  {_≈G_ : G → G → Set ℓEG} {_≈X_ : X → X → Set ℓEX}
  {n : ℕ}
  (τ : PrimeFactoredGauge G X _·G_ εG _≈G_ _≈X_ n) →
  (x y : X) →
  InGenerated (λ z → Σ (Fin n) (λ i → Sylow (factorization τ) i z))
              _·G_ εG (gauge-element τ x y)
sylow-chain τ x y = proj₂ (proj₂ (multi-route-equivariance τ x y))

------------------------------------------------------------------------
-- 3. Capstone — generic theorem in place.
--
-- T5 of the prime-factored-gauge arc per
-- [[prime-factored-gauge-arc]]. With T5 landed, the substrate
-- exposes the generic multi-route equivariance content for ANY
-- PrimeFactoredGauge instance:
--
--   * gauge-element τ x y      — THE gauge element connecting x → y
--   * sylow-chain τ x y         — the Sylow-product decomposition
--                                  of that gauge element
--
-- These two functions together give the substrate-side formulation
-- of "extended Euclid for groups" — any equivariance question
-- reduces to a sequence of per-Sylow chart applications.
--
-- Concrete instances expected (T6, T7, T8):
--   * GL(3, F₂): the multi-route arc's structural content
--     re-derived via the generic theorem instead of per-instance.
--   * HodgeDim4 GaugeTorsor: 168 bridges as orbit points; gauge
--     element between any two = Sylow-product chain over Sylow-2,
--     Sylow-3, Sylow-7 generators.
--   * Monster: gauge elements between conjugacy-class
--     representatives; chains decomposed via Monster's prime-
--     factored Sylow structure (cited from ATLAS).
--
-- Per [[shadow-architecture]]: T5 is a thin DBE-derivation slice
-- following from T0-T4. The substantive work was in T1 (the
-- atlas-decomposition construction); T5 names it.
------------------------------------------------------------------------
