------------------------------------------------------------------------
-- Substrate.Algebra.F2.SymBilinForm.CongruenceCompose
--
-- The congruence-action composition law:
--
--   congruence-act (T₁ ∘L T₂) M  ≡pointwise  congruence-act T₂ (congruence-act T₁ M)
--
-- proved at generic n. Combined with FixedPoint-of-compose from
-- Substrate.Category.Coalgebra (primitive #1), this closes the
-- StabiliserClosure automation: at any n, the stabiliser of a fixed
-- point under a Coxeter group's congruence action is generated by
-- the FixedPoint witnesses for the Coxeter generators alone — every
-- composition's stabilisation is derived mechanically.
--
-- The substantive content is the **bilinear-form-of-congruence-act
-- aux lemma**:
--
--   bilinear-form-of (congruence-act T M) v w  ≡  bilinear-form-of M (apply T v) (apply T w)
--
-- — "evaluating the congruence-acted form at (v, w) is the same as
-- evaluating the original form at (T v, T w)." This is the universal
-- property of congruence-act at the bilinear-form-of level.
--
-- Proof path:
--   1. Decompose v, w via basis-decomp; push T through using
--      preserves-sum + preserves-*ₛ.
--   2. Use bilinearity (sum + scalar in both arguments) to expand
--      the RHS double sum into the matching LHS form.
--   3. Reconcile inner factor order via ·-comm + ·-assoc.
--
-- Per `feedback_universal_property_discipline`: the aux lemma IS the
-- universal property of congruence-act; congruence-compose follows
-- by instantiating at v = apply T₂ (basis i), w = apply T₂ (basis j).
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Algebra.F2.SymBilinForm.CongruenceCompose where

open import Data.Fin using (Fin; zero; suc)
open import Data.Nat using (ℕ)
open import Data.Vec using (lookup)
open import Function using (_∘_)
open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; trans; cong; cong₂)

open import Substrate.Algebra.F2
open import Substrate.Algebra.F2.Vector
open import Substrate.Algebra.F2.Vector.Universal
  using (sum; sum-F₂; sum-F₂-cong; basis-decomp)
open import Substrate.Algebra.F2.Linear
open import Substrate.Algebra.F2.Linear.Universal using (preserves-sum; sum-cong)
open import Substrate.Algebra.F2.SymBilinForm
  using (BilinForm; bilinear-form-of; congruence-act)
open import Substrate.Algebra.F2.SymBilinForm.Bilinearity
  using (bilinear-form-of-+ⱽ-left; bilinear-form-of-+ⱽ-right;
         bilinear-form-of-*ₛ-left; bilinear-form-of-*ₛ-right;
         sum-F₂-scalar)

------------------------------------------------------------------------
-- N-1: bilinear-form-of vanishes on 𝟎ⱽ (each side).
--
-- Both follow from scalar-respect with c = 𝟘: 𝟎ⱽ ≡ 𝟘 *ₛ 𝟎ⱽ, then
-- 𝟘 · anything ≡ 𝟘.
------------------------------------------------------------------------

bilinear-form-of-𝟎ⱽ-right :
  ∀ {n} (M : BilinForm n) (u : Vector n) →
  bilinear-form-of M u 𝟎ⱽ ≡ 𝟘
bilinear-form-of-𝟎ⱽ-right M u =
  trans (cong (bilinear-form-of M u) (sym (*ₛ-absorbˡ 𝟎ⱽ)))
  (trans (bilinear-form-of-*ₛ-right M 𝟘 u 𝟎ⱽ)
         (·-absorbˡ (bilinear-form-of M u 𝟎ⱽ)))

bilinear-form-of-𝟎ⱽ-left :
  ∀ {n} (M : BilinForm n) (w : Vector n) →
  bilinear-form-of M 𝟎ⱽ w ≡ 𝟘
bilinear-form-of-𝟎ⱽ-left M w =
  trans (cong (λ x → bilinear-form-of M x w) (sym (*ₛ-absorbˡ 𝟎ⱽ)))
  (trans (bilinear-form-of-*ₛ-left M 𝟘 𝟎ⱽ w)
         (·-absorbˡ (bilinear-form-of M 𝟎ⱽ w)))

------------------------------------------------------------------------
-- N-2: bilinear-form-of distributes over indexed sum (each side).
--
-- Induction on the index range k. Base: bilinear-form-of-𝟎ⱽ-*.
-- Step: bilinear-form-of-+ⱽ-* + IH.
------------------------------------------------------------------------

bilinear-form-of-sum-right :
  ∀ {n k} (M : BilinForm n) (u : Vector n) (f : Fin k → Vector n) →
  bilinear-form-of M u (sum f) ≡ sum-F₂ (λ j → bilinear-form-of M u (f j))
bilinear-form-of-sum-right {k = ℕ.zero}  M u f = bilinear-form-of-𝟎ⱽ-right M u
  where import Data.Nat as ℕ
bilinear-form-of-sum-right {k = ℕ.suc _} M u f =
  trans (bilinear-form-of-+ⱽ-right M u (f zero) (sum (f ∘ suc)))
        (cong (bilinear-form-of M u (f zero) +_)
              (bilinear-form-of-sum-right M u (f ∘ suc)))
  where import Data.Nat as ℕ

bilinear-form-of-sum-left :
  ∀ {n k} (M : BilinForm n) (f : Fin k → Vector n) (w : Vector n) →
  bilinear-form-of M (sum f) w ≡ sum-F₂ (λ i → bilinear-form-of M (f i) w)
bilinear-form-of-sum-left {k = ℕ.zero}  M f w = bilinear-form-of-𝟎ⱽ-left M w
  where import Data.Nat as ℕ
bilinear-form-of-sum-left {k = ℕ.suc _} M f w =
  trans (bilinear-form-of-+ⱽ-left M (f zero) (sum (f ∘ suc)) w)
        (cong (bilinear-form-of M (f zero) w +_)
              (bilinear-form-of-sum-left M (f ∘ suc) w))
  where import Data.Nat as ℕ

------------------------------------------------------------------------
-- N-3: Double-scalar helper.
--
-- bilinear-form-of M (a *ₛ v) (b *ₛ w) ≡ a · (b · bilinear-form-of M v w)
-- Combines left-scalar then right-scalar.
------------------------------------------------------------------------

bilinear-form-of-both-scalars :
  ∀ {n} (M : BilinForm n) (a b : F₂) (v w : Vector n) →
  bilinear-form-of M (a *ₛ v) (b *ₛ w) ≡ a · (b · bilinear-form-of M v w)
bilinear-form-of-both-scalars M a b v w =
  trans (bilinear-form-of-*ₛ-left M a v (b *ₛ w))
        (cong (a ·_) (bilinear-form-of-*ₛ-right M b v w))

------------------------------------------------------------------------
-- N-4: The aux lemma — bilinear-form-of and congruence-act commute
-- via T.
--
--   bilinear-form-of (congruence-act T M) v w
--     ≡ bilinear-form-of M (apply T v) (apply T w)
--
-- Strategy:
--   * RHS → double-sum form (by basis-decomp + T's linearity + bilinearity).
--   * LHS → same double-sum form (by sum-F₂-scalar reverse + ·-comm).
------------------------------------------------------------------------

bilinear-form-of-congruence-act :
  ∀ {n} (T : Linear n n) (M : BilinForm n) (v w : Vector n) →
  bilinear-form-of (congruence-act T M) v w
    ≡ bilinear-form-of M (apply T v) (apply T w)
bilinear-form-of-congruence-act {n} T M v w =
  trans lhs-to-canonical (sym rhs-to-canonical)
  where
    -- Convenient abbreviation for the bilinear-form-of M evaluated at
    -- the (T eᵢ, T eⱼ) basis pair — i.e., the (i,j) entry of
    -- (congruence-act T M) by definition.
    bf : Fin n → Fin n → F₂
    bf i j = bilinear-form-of M (apply T (basis i)) (apply T (basis j))

    -- The canonical double-sum form both LHS and RHS will be brought
    -- to.
    canonical : F₂
    canonical =
      sum-F₂ {n} (λ i →
        sum-F₂ {n} (λ j → lookup v i · (lookup w j · bf i j)))

    -- apply T u as a sum over basis: u ≡ Σᵢ uᵢ *ₛ basis i (basis-decomp);
    -- apply T pushes through via preserves-sum + preserves-*ₛ.
    apply-T-sum :
      (u : Vector n) →
      apply T u ≡ sum (λ i → lookup u i *ₛ apply T (basis i))
    apply-T-sum u =
      trans (cong (apply T) (basis-decomp u))
      (trans (preserves-sum T (λ i → lookup u i *ₛ basis i))
             (sum-cong (λ i → preserves-*ₛ T (lookup u i) (basis i))))

    -- RHS-to-canonical chain:
    --   bilinear-form-of M (apply T v) (apply T w)
    -- = bilinear-form-of M (Σᵢ vᵢ *ₛ Teᵢ) (Σⱼ wⱼ *ₛ Teⱼ)         [apply-T-sum]
    -- = sum-F₂ (i → bilinear-form-of M (vᵢ *ₛ Teᵢ) (Σⱼ wⱼ *ₛ Teⱼ)) [sum-left]
    -- = sum-F₂ (i → sum-F₂ (j → bilinear-form-of M (vᵢ*ₛTeᵢ) (wⱼ*ₛTeⱼ)))
    --                                                              [sum-right under cong]
    -- = sum-F₂ (i → sum-F₂ (j → vᵢ · (wⱼ · bf i j)))               [both-scalars]
    rhs-to-canonical :
      bilinear-form-of M (apply T v) (apply T w) ≡ canonical
    rhs-to-canonical =
      trans (cong₂ (bilinear-form-of M) (apply-T-sum v) (apply-T-sum w))
      (trans (bilinear-form-of-sum-left M
               (λ i → lookup v i *ₛ apply T (basis i))
               (sum (λ j → lookup w j *ₛ apply T (basis j))))
        (sum-F₂-cong {n} (λ i →
          trans (bilinear-form-of-sum-right M
                  (lookup v i *ₛ apply T (basis i))
                  (λ j → lookup w j *ₛ apply T (basis j)))
                (sum-F₂-cong {n} (λ j →
                  bilinear-form-of-both-scalars M
                    (lookup v i) (lookup w j)
                    (apply T (basis i)) (apply T (basis j)))))))

    -- LHS-to-canonical:
    --   bilinear-form-of (congruence-act T M) v w
    -- = sum-F₂ (λ i → vᵢ · sum-F₂ (λ j → bf i j · wⱼ))   [definition; (cong-act T M)(i,j) = bf i j]
    -- = sum-F₂ (λ i → vᵢ · sum-F₂ (λ j → wⱼ · bf i j))   [·-comm under inner cong]
    -- = sum-F₂ (λ i → sum-F₂ (λ j → vᵢ · (wⱼ · bf i j))) [sym sum-F₂-scalar]
    lhs-to-canonical :
      bilinear-form-of (congruence-act T M) v w ≡ canonical
    lhs-to-canonical =
      sum-F₂-cong {n} (λ i →
        trans (cong (lookup v i ·_)
                    (sum-F₂-cong {n} (λ j →
                      ·-comm (bf i j) (lookup w j))))
              (sym (sum-F₂-scalar (lookup v i)
                                  (λ j → lookup w j · bf i j))))

------------------------------------------------------------------------
-- N-5: congruence-compose-pointwise — the composition law at the
-- pointwise level (no function extensionality required).
------------------------------------------------------------------------

congruence-compose-pointwise :
  ∀ {n} (T₁ T₂ : Linear n n) (M : BilinForm n) (i j : Fin n) →
  congruence-act (T₁ ∘L T₂) M i j
    ≡ congruence-act T₂ (congruence-act T₁ M) i j
congruence-compose-pointwise T₁ T₂ M i j =
  -- LHS = bilinear-form-of M (apply (T₁ ∘L T₂) eᵢ) (apply (T₁ ∘L T₂) eⱼ)
  --     = bilinear-form-of M (apply T₁ (apply T₂ eᵢ)) (apply T₁ (apply T₂ eⱼ))
  --       [definition of ∘L's apply]
  -- RHS = bilinear-form-of (congruence-act T₁ M) (apply T₂ eᵢ) (apply T₂ eⱼ)
  --     = bilinear-form-of M (apply T₁ (apply T₂ eᵢ)) (apply T₁ (apply T₂ eⱼ))
  --       [aux lemma at v = apply T₂ eᵢ, w = apply T₂ eⱼ]
  sym (bilinear-form-of-congruence-act T₁ M
         (apply T₂ (basis i)) (apply T₂ (basis j)))

------------------------------------------------------------------------
-- N-6: Capstone — the dependency chain is closed.
--
-- congruence-compose-pointwise + FixedPoint-of-compose from
-- primitive #1 automate the StabiliserClosure cascade at any n.
-- Given FixedPoint witnesses for a group's generators acting via
-- congruence on a fixed point M, every composition's stabilisation
-- is derived mechanically.
--
-- For dim 3's stabiliser of metric-id:
--   * s₁-stabilises-metric-id and s₂-stabilises-metric-id are
--     already retrofitted as FixedPoint instances (in
--     HodgeDim3.MetricGauge.Stabiliser).
--   * s₁∘s₂-stabilises-metric-id (currently in StabiliserClosure.agda
--     as a 166-LoC per-cycle proof) becomes derivable from
--       FixedPoint-of-compose ∘ congruence-compose-pointwise
--     once the SymBilinForm-3 ↔ SymBilinForm 3 bridge is in place.
--   * The remaining 3 stabiliser elements (s₂∘s₁, s₁∘s₂∘s₁,
--     s₂∘s₁∘s₂) follow by repeated application, mechanically
--     completing the 6-element S₃ stabiliser.
--
-- Per `feedback_categorical_name_first`: the categorical primitive
-- FixedPoint-of-compose, the universal property
-- congruence-compose-pointwise, and the substrate-level FixedPoint
-- witnesses for Coxeter generators jointly derive the full
-- stabiliser subgroup. The substrate's per-cycle StabiliserClosure
-- proofs reduce to corollary lines once retrofitted.
--
-- Deferred follow-ons:
--
--   * `is-symmetric-congruence-act` — congruence-act preserves
--     symmetry of the input bilinear form. Analogous to
--     bilinear-form-of-congruence-act but using symmetry of M
--     and ·-comm to swap argument order.
--
--   * `bridges-dim-3-dim-4` — round-trip equivalences SymBilinForm-3
--     ↔ SymBilinForm 3 and SymBilinForm-4 ↔ SymBilinForm 4. Once
--     these land, the existing dim-3 / dim-4 proofs demote to
--     instantiations of the SymBilinForm.* generic theorems.
--
--   * Retrofit StabiliserClosure.agda to use FixedPoint-of-compose
--     + congruence-compose-pointwise.
------------------------------------------------------------------------
