------------------------------------------------------------------------
-- Substrate.Groups.FreeCyclic-Coxeter
--
-- The free monoid on one generator, presented as a Coxeter group with
-- NO relations. Plays the role of ℕ (count of generator applications)
-- in the substrate's Coxeter framework.
--
-- Structurally: ⟨a | (no relations)⟩. Every word in {a}* is in
-- canonical form; normalize is the identity. The element `a` has
-- INFINITE order (no aⁿ = ε relation).
--
-- Used by: the cyclic-cover construction (this module's primary
-- purpose). For a cyclic group Z/n, the universal cover is the
-- "FreeCyclic + Z/n" 2-D structure via DirectProduct — phase from
-- Z/n, cycle counter from FreeCyclic.
--
-- Per the 2-D word algebra arc: this is the "cycle counter" axis.
-- The phase axis is one of the existing Zₙ-Coxeter instances; the
-- cycle counter has no wraparound (counts how many full cycles deep).
--
-- Per [[feedback-roll-our-own-via-word-algebra]]: substrate-native
-- representation of ℕ within the Coxeter framework. Avoids needing
-- to bridge ℕ as a separate algebraic structure.
--
-- Per [[feedback-categorical-name-first]]: this IS the free monoid on
-- one generator. Coxeter framing surfaces the "no-relation" case as
-- a valid Coxeter instance, completing the Coxeter family (Z/2 with
-- a² = ε, Z/3 with a³ = ε, ..., Z/∞ = FreeCyclic with NO relation).
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Groups.FreeCyclic-Coxeter where

open import Substrate.Groups.Coxeter.Word
open import Substrate.Foundation.Eq
  using (_≡_; refl; cong; trans; sym)
open import Substrate.Foundation.Nat using (ℕ; zero; suc)
open import Substrate.Foundation.Negation using (¬_)

------------------------------------------------------------------------
-- 1. FreeCyclic-specific data.
------------------------------------------------------------------------

data Gen : Set where
  a : Gen

-- Every word is canonical (no relations to satisfy).
data Canonical-Free : Word Gen → Set where      -- ⟦shape:0c35b127 c-any⟧
  c-any : (w : Word Gen) → Canonical-Free w

------------------------------------------------------------------------
-- 2. The insert step: cons (no wraparound, since no relation).
------------------------------------------------------------------------

insert : Gen → Word Gen → Word Gen
insert g w = g ∷ w

insert-canonical : (g : Gen) {w : Word Gen} → Canonical-Free w → Canonical-Free (insert g w)
insert-canonical g (c-any w) = c-any (g ∷ w)


open import Substrate.Groups.Coxeter.ListPresentation
  Gen Canonical-Free (c-any []) insert insert-canonical public
------------------------------------------------------------------------
-- 3. Open ListPresentation with FreeCyclic's atoms.
------------------------------------------------------------------------


------------------------------------------------------------------------
-- 4. Per-relation obligations.
--
-- canonical-is-fixed: normalize is identity by induction on the word.
-- insert-append-lemma: refl (insert just conses).
------------------------------------------------------------------------

canonical-is-fixed-Free : {w : Word Gen} → Canonical-Free w → normalize w ≡ w
canonical-is-fixed-Free {w = []}     (c-any _) = refl
canonical-is-fixed-Free {w = x ∷ xs} (c-any _) =
  cong (x ∷_) (canonical-is-fixed-Free {w = xs} (c-any xs))

insert-append-lemma-Free :
  (g : Gen) {w : Word Gen} (w₂ : Word Gen) → Canonical-Free w →
  normalize (insert g w ++ w₂) ≡ insert g (normalize (w ++ w₂))
insert-append-lemma-Free g w₂ _ = refl


open WithLemmas canonical-is-fixed-Free insert-append-lemma-Free public
------------------------------------------------------------------------
-- 5. Open WithLemmas to inherit the full abstract Core surface.
------------------------------------------------------------------------


------------------------------------------------------------------------
-- 6. The INFINITE ORDER of `a`, as a CONSTRUCTIVE theorem (Ⓞ).
--
-- The defining feature of FreeCyclic — a's order is infinite, the contrast
-- to Zₙ-Coxeter's nth-power-identity — is NOT a missing relation ("there is
-- no k>0 with aᵏ=ε; the absence IS the content" was a negation-by-absence,
-- the LEM reading the substrate rejects). It is GENERATED by a positive
-- invariant: LENGTH.
--
-- aᵏ = `a ∷ a ∷ … ∷ []` (k applications of the insert step). Since `insert`
-- just conses and every word is `Canonical-Free`, length faithfully tracks the
-- power: len aᵏ ≡ k. ε = [] has length 0. So distinct powers are distinct
-- words (`pow-injective`), and aᵏ ≡ ε forces k ≡ 0 — for k>0, absurd
-- (`a-infinite-order`). "aᵏ is not ε" reads "not ONLY at the value grade —
-- their LENGTHS differ" (the M40NoIso pattern: transport a positive invariant
-- through the would-be equation; here len through aᵏ ≡ ε). The "cycle counter
-- never wraps" is exactly FreeCyclic-as-ℕ: aᵏ is the witness path of length k,
-- `len` its step count, and the path never returns to the base [].
------------------------------------------------------------------------

-- aᵏ: k iterations of the insert (witnessing) step on the empty word.
pow : ℕ → Word Gen
pow zero    = []
pow (suc k) = insert a (pow k)

-- the length = number of generator-applications (steps) of a word.
len : Word Gen → ℕ
len []      = zero
len (_ ∷ w) = suc (len w)

-- THE POSITIVE INVARIANT: aᵏ has length exactly k.
pow-length : (k : ℕ) → len (pow k) ≡ k
pow-length zero    = refl
pow-length (suc k) = cong suc (pow-length k)

-- POSITIVE STRUCTURE: distinct powers are distinct words — length determines
-- the power, so FreeCyclic ≅ ℕ on the generator. (Infinite order = this
-- injectivity, not an absent relation.)
pow-injective : (j k : ℕ) → pow j ≡ pow k → j ≡ k
pow-injective j k eq =
  trans (sym (pow-length j)) (trans (cong len eq) (pow-length k))

-- INFINITE ORDER (the negative pole, GENERATED): no positive power is the
-- identity. pow (suc k) ≡ [] (= pow zero) would force suc k ≡ 0 by injectivity.
a-infinite-order : (k : ℕ) → ¬ (pow (suc k) ≡ [])
a-infinite-order k eq with pow-injective (suc k) zero eq
... | ()
