------------------------------------------------------------------------
-- Substrate.WitnessTower.B3Split
--
-- The last piece of full B3, computed over the iterated enumeration: the
-- 4 Klein-fours of S₄ split by the CYCLE TYPES of their elements into
--   * 1 NORMAL GAUGE V₄  = {id} ∪ {the 3 double-transpositions}
--                          (signature: all three non-identity elements (2,2))
--   * 3 INTERFACE V₄s    = {id, d, t₁, t₂}, one double-transposition d and
--                          two transpositions (signature: 1×(2,2)+2×(2,1,1))
-- and the SEAM: gauge ∩ interface = {id, d}, a single V₂ — the interface's
-- unique double-transposition, which is automatically in the gauge (the
-- gauge IS all the double-transpositions). This is the substrate-native
-- transcription of scratch/B3-shared-v2-proof.py.
--
-- Method (no subgroup-set dedup needed — the /6 is the dedup, recorded as
-- a witnessed identity): classify each Klein-generating ordered pair (a,b)
-- by how many of {a, b, ab} are double-transpositions. A gauge subgroup
-- shows 3 (every element (2,2)); an interface shows 1. Each subgroup is
-- generated by 6 ordered pairs, so #subgroups = #pairs / 6. All facts live
-- at rung 4 (the (2,2) signature first exists there), so the cycle-type
-- tests are at Perm 4.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.B3Split where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_) renaming (_≟_ to _≟ℕ_)
open import Substrate.Foundation.Bool using (Bool; true; false; _∧_; not; if_then_else_)
open import Substrate.Foundation.Eq using (_≡_; refl)

open import Substrate.WitnessTower.Enumerate using (Perm; perms; mapL; concatMapL; lengthL)
open import Substrate.WitnessTower.FirstAppearance using (compose; ⌊_⌋; filterL; _≡ᵇ_)
open import Substrate.WitnessTower.KleinCensus using (klein-pair)
open import Substrate.WitnessTower.CycleType
  using (cycle-type; _≟ᵛ_; ty-double; ty-transp)

------------------------------------------------------------------------
-- 0. Element cycle-type tests (rung 4) + a Bool→ℕ tally.
------------------------------------------------------------------------

is-double : Perm 4 → Bool
is-double σ = ⌊ cycle-type σ ≟ᵛ ty-double ⌋

is-transp : Perm 4 → Bool
is-transp σ = ⌊ cycle-type σ ≟ᵛ ty-transp ⌋

bToℕ : Bool → ℕ
bToℕ true  = 1
bToℕ false = zero

-- iterate a Bool-predicate count over all ordered pairs of perms 4.
count-pairs : (Perm 4 → Perm 4 → Bool) → ℕ
count-pairs p =
  lengthL (filterL (λ b → b)
    (concatMapL (λ a → mapL (λ b → p a b) (perms 4)) (perms 4)))

------------------------------------------------------------------------
-- 1. Classify a Klein-generating pair by #double-transpositions in {a,b,ab}.
------------------------------------------------------------------------

triple-doubles : Perm 4 → Perm 4 → ℕ
triple-doubles a b =
  bToℕ (is-double a) + (bToℕ (is-double b) + bToℕ (is-double (compose a b)))

triple-transps : Perm 4 → Perm 4 → ℕ
triple-transps a b =
  bToℕ (is-transp a) + (bToℕ (is-transp b) + bToℕ (is-transp (compose a b)))

klein-pairs-with-doubles : (d : ℕ) → ℕ
klein-pairs-with-doubles d =
  count-pairs (λ a b → klein-pair a b ∧ ⌊ triple-doubles a b ≟ℕ d ⌋)

------------------------------------------------------------------------
-- 2. The split (refl over the enumeration). 6 gauge pairs (→1 subgroup),
--    18 interface pairs (→3 subgroups), none with exactly 2.
------------------------------------------------------------------------

gauge-pairs-4 : klein-pairs-with-doubles 3 ≡ 6
gauge-pairs-4 = refl

interface-pairs-4 : klein-pairs-with-doubles 1 ≡ 18
interface-pairs-4 = refl

no-two-doubles-4 : klein-pairs-with-doubles 2 ≡ 0
no-two-doubles-4 = refl

-- #subgroups = #pairs / 6, recorded as witnessed identities:
gauge-six          : 6 ≡ klein-pairs-with-doubles 3          -- 1 × 6
gauge-six          = refl
interface-eighteen : 6 + (6 + 6) ≡ klein-pairs-with-doubles 1  -- 3 × 6
interface-eighteen = refl

------------------------------------------------------------------------
-- 3. Gauge closure: the 3 double-transpositions are closed under product
--    (any two distinct compose to the third), so {id}∪{3 (2,2)s} really is
--    the gauge V₄, and ALL double-transpositions live in it.
------------------------------------------------------------------------

-- ordered pairs of distinct double-transpositions (distinct as
-- PERMUTATIONS — they all share the (2,2) cycle type, so distinctness must
-- be on the element, not the type).
dt-pairs : ℕ
dt-pairs =
  count-pairs (λ a b → is-double a ∧ (is-double b ∧ not (a ≡ᵇ b)))

-- of those, the ones whose product is ALSO a double-transposition.
dt-pairs-closed : ℕ
dt-pairs-closed =
  count-pairs (λ a b → is-double a ∧ (is-double b ∧ (not (a ≡ᵇ b)
                                                     ∧ is-double (compose a b))))

gauge-closure   : dt-pairs-closed ≡ dt-pairs
gauge-closure   = refl
gauge-closure-6 : dt-pairs-closed ≡ 6
gauge-closure-6 = refl

------------------------------------------------------------------------
-- 4. The SEAM. Every interface meets the gauge in exactly one
--    non-identity element: its unique double-transposition d (a gauge
--    member by §3), the two transpositions being NON-members (the gauge
--    has only (2,2) non-identity elements). So gauge ∩ interface =
--    {id, d} ≅ V₂. We confirm the FULL interface signature (1 double +
--    2 transpositions), so the "two elements outside the gauge" half is
--    checked too — the seam is the single shared d.
------------------------------------------------------------------------

interface-full-sig : ℕ
interface-full-sig =
  count-pairs (λ a b → klein-pair a b
                     ∧ (⌊ triple-doubles a b ≟ℕ 1 ⌋ ∧ ⌊ triple-transps a b ≟ℕ 2 ⌋))

-- all 18 interface pairs have signature {seam (2,2)} + {two (2,1,1)}:
-- gauge ∩ interface = exactly one shared (2,2) = a V₂ seam.
seam-signature : interface-full-sig ≡ 18
seam-signature = refl

-- the total reconciles: 6 (gauge) + 18 (interface) = 24 Klein pairs.
b3-reconcile : klein-pairs-with-doubles 3 + klein-pairs-with-doubles 1 ≡ 24
b3-reconcile = refl
