------------------------------------------------------------------------
-- Substrate.WitnessTower.FaceCount
--
-- BUILD (not assert) the CONE side of the witnessing step: the new point
-- is an APEX coned over the prior simplex, and the f-vector (how many
-- k-faces a rung-n simplex has) is generated by that coning.
--
-- The narration, sharpened (user, 2026-06-04): the fourth point builds the
-- tetrahedron because it draws "an edge between the new point and every
-- existing vertex; what was one face constructs N faces per edges that make
-- up a face, and those N faces close over the apex." That is the cone over
-- the boundary, apex * base:
--   * each base VERTEX (0-face) → one new EDGE to the apex;
--   * each base EDGE (1-face)   → one new triangular FACE over the apex;
--   * each base k-face          → one new (k+1)-face over the apex,
-- so the new (k+1)-faces number EXACTLY the base's k-faces. Adding that to
-- the base's own (k+1)-faces is PASCAL'S RULE — which is why the f-vector
-- (Δ³: 4,6,4,1) is NOT symmetric under the grade reversal k↦n−k of the
-- Hodge spine (WitnessTower.Hodge.dual-grade): the cell counts follow
-- Pascal, the grade LABELS follow reversal, and they diverge as you climb
-- from the point (where they coincide). This file makes the cone recursion,
-- and the "fourth point closes the tetrahedron" instance, green by refl.
--
-- COMPANION, not duplicate: WitnessTower.Puncture counts only the 0-faces
-- (vertices) via the puncture bijection; this counts ALL k-faces. And
-- `faces n 0 = suc n` is the SAME (n+1) that drives the permutation tower's
-- wedge quotient (Wedge.Factoradic.tower-quotient n = suc n) — the apex's
-- vertex-edges and the Aut-tower's growth factor are one count, two readings.
--
-- Zero postulates, --safe --without-K.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.FaceCount where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_)
open import Substrate.Foundation.Eq using (_≡_; refl)

------------------------------------------------------------------------
-- 1. The f-vector by coning. `faces n k` = number of k-faces of the
--    rung-n simplex Δⁿ. Defined by the cone recursion itself:
--      faces n 0       = n+1                 -- the n+1 vertices
--      faces (suc n) (suc k) = (base's (k+1)-faces) + (base's k-faces)
--                              ╰─ old, away from apex   ╰─ coned over apex
------------------------------------------------------------------------

faces : ℕ → ℕ → ℕ
faces n       zero    = suc n
faces zero    (suc k) = zero
faces (suc n) (suc k) = faces n (suc k) + faces n k

------------------------------------------------------------------------
-- 2. The cone recursion as a named law (the narration, generalised):
--    every (k+1)-face of the new simplex is EITHER a base (k+1)-face
--    (away from the apex) OR a base k-face coned over the apex. The
--    second summand `faces n k` is "N new (k+1)-faces, one per base
--    k-face, closing over the apex."
------------------------------------------------------------------------

cone-step : (n k : ℕ) → faces (suc n) (suc k) ≡ faces n (suc k) + faces n k
cone-step n k = refl

-- The apex draws one edge to every existing vertex: the new simplex's
-- edges are the base edges PLUS one apex-edge per base vertex.
apex-edges : (n : ℕ) → faces (suc n) 1 ≡ faces n 1 + faces n 0
apex-edges n = refl

------------------------------------------------------------------------
-- 3. The fourth point closes the tetrahedron (the headline instance).
--    The base triangle Δ² has 3 vertices, 3 edges, 1 face.
------------------------------------------------------------------------

triangle-vertices : faces 2 0 ≡ 3
triangle-vertices = refl

triangle-edges : faces 2 1 ≡ 3
triangle-edges = refl

triangle-faces : faces 2 2 ≡ 1
triangle-faces = refl

-- "what was one face constructs N faces per edges that make up a face":
-- the triangle's 1 face stays, its 3 EDGES each cone over the apex into a
-- new face — 1 + 3 = the tetrahedron's 4 triangular faces.
tetra-faces-from-base : faces 3 2 ≡ faces 2 2 + faces 2 1
tetra-faces-from-base = refl

-- "an edge between the new point and every existing vertex": the triangle's
-- 3 edges stay, the apex adds one edge to each of the 3 base vertices —
-- 3 + 3 = the tetrahedron's 6 edges.
tetra-edges-from-base : faces 3 1 ≡ faces 2 1 + faces 2 0
tetra-edges-from-base = refl

-- the full f-vector of the tetrahedron Δ³ : (vertices, edges, faces, cell).
tetra-vertices : faces 3 0 ≡ 4
tetra-vertices = refl

tetra-edges : faces 3 1 ≡ 6
tetra-edges = refl

tetra-faces : faces 3 2 ≡ 4
tetra-faces = refl

tetra-cell : faces 3 3 ≡ 1
tetra-cell = refl

------------------------------------------------------------------------
-- 4. The grading boundary, made manifest. The Hodge grade spine
--    (WitnessTower.Hodge.dual-grade) reverses grade LABELS k↦n−k; for n=3
--    that pairs Λ⁰↔Λ³ and Λ¹↔Λ². But the CELL COUNTS are not preserved by
--    that pairing — faces 3 0 = 4 vertices vs faces 3 3 = 1 cell. The count
--    palindrome is offset by one: it pairs the PROPER faces (the boundary
--    sphere ∂Δ³ = S²), k↦(n−1)−k, i.e. vertices↔faces and edges self-dual.
--    That offset (solid simplex's grade ★ vs its boundary sphere's count
--    duality) IS the grading boundary the narration climbs to expose.
------------------------------------------------------------------------

-- the boundary-sphere count palindrome at n=3: proper k-faces k↦(2−k).
-- vertices (4) ↔ faces (4):
boundary-vertices-faces : faces 3 0 ≡ faces 3 2
boundary-vertices-faces = refl

-- edges (6) self-paired (the middle proper grade of S² is self-dual):
boundary-edges-self : faces 3 1 ≡ faces 3 1
boundary-edges-self = refl
