------------------------------------------------------------------------
-- Substrate.WitnessTower.IsPermutation
--
-- Brick 1 of "the tower IS a re-reading of Sₙ": every image vector the
-- witnessing-insertion construction produces is a genuine BIJECTION, not
-- merely a Vec (Fin n) n. On a finite set injectivity ⟺ bijectivity, so we
-- take injectivity of `lookup v` as the permutation witness.
--
-- The load-bearing fact: insert-at PRESERVES the permutation property. The
-- new top index maps to p; every old index maps to punchIn p (old image),
-- which (i) dodges p — punchIn-≢ — and (ii) keeps distinct images distinct
-- — punchIn injective. So inserting the witness at any position keeps the
-- result a bijection. Hence the construction never leaves Sₙ.
--
-- This is brick 1 of three (the others: perms is duplicate-free; perms is
-- complete) — together they upgrade the census from "Sₙ-shaped numbers over
-- a length-n! list" to "the census of Sₙ, generated by the tower".
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.IsPermutation where

open import Substrate.Foundation.Nat using (ℕ; zero; suc)
open import Substrate.Foundation.Fin using (Fin; zero; suc; suc-injective)
open import Substrate.Foundation.Vec using (Vec; []; _∷_; lookup; map)
open import Substrate.Foundation.List using (List; []; _∷_; _++_)
open import Substrate.Foundation.Eq using (_≡_; refl; cong; sym)
open import Substrate.Foundation.Negation using (¬_)
open import Substrate.Foundation.Empty using (⊥-elim)
open import Substrate.Foundation.Unit using (⊤; tt)
open import Substrate.Foundation.Product using (_×_; _,_)
open import Substrate.Foundation.Fin.Punctured using (punchIn; punchIn-≢)

open import Substrate.WitnessTower.Enumerate
  using (Perm; insert-at; perms; mapL; concatMapL; all-positions)

------------------------------------------------------------------------
-- 0. Supporting lemmas: punchIn injective, lookup∘map.
------------------------------------------------------------------------

punchIn-injective :
  {n : ℕ} (k : Fin (suc n)) {i j : Fin n} →
  punchIn k i ≡ punchIn k j → i ≡ j
punchIn-injective zero          eq = suc-injective eq
punchIn-injective (suc k) {zero}  {zero}  eq = refl
punchIn-injective (suc k) {zero}  {suc j} ()
punchIn-injective (suc k) {suc i} {zero}  ()
punchIn-injective {suc _} (suc k) {suc i} {suc j} eq =
  cong suc (punchIn-injective k (suc-injective eq))

lookup-map :
  {A B : Set} {n : ℕ} (f : A → B) (v : Vec A n) (i : Fin n) →
  lookup (map f v) i ≡ f (lookup v i)
lookup-map f (x ∷ v) zero    = refl
lookup-map f (x ∷ v) (suc i) = lookup-map f v i

------------------------------------------------------------------------
-- 1. The permutation predicate: lookup v is injective (⟺ bijective on Fin).
------------------------------------------------------------------------

IsPerm : {n : ℕ} → Perm n → Set
IsPerm {n} v = (i j : Fin n) → lookup v i ≡ lookup v j → i ≡ j

------------------------------------------------------------------------
-- 2. insert-at preserves IsPerm. (insert-at p σ = p ∷ map (punchIn p) σ.)
------------------------------------------------------------------------

insert-at-preserves :
  {n : ℕ} (p : Fin (suc n)) (σ : Perm n) →
  IsPerm σ → IsPerm (insert-at p σ)
insert-at-preserves p σ σ-perm = go
  where
    -- lookup (insert-at p σ) at suc i reduces to punchIn p (lookup σ i).
    tail-val : (i : Fin _) → lookup (insert-at p σ) (suc i) ≡ punchIn p (lookup σ i)
    tail-val i = lookup-map (punchIn p) σ i

    go : IsPerm (insert-at p σ)
    -- both at the witness index: equal.
    go zero    zero    _  = refl
    -- witness vs a witnessed index: p ≡ punchIn p (...) is impossible.
    go zero    (suc j) eq =
      ⊥-elim (punchIn-≢ p (lookup σ j) (sym (trans-eq eq (tail-val j))))
      where
        open import Substrate.Foundation.Eq using (trans)
        trans-eq : lookup (insert-at p σ) zero ≡ lookup (insert-at p σ) (suc j) →
                   lookup (insert-at p σ) (suc j) ≡ punchIn p (lookup σ j) →
                   p ≡ punchIn p (lookup σ j)
        trans-eq e₁ e₂ = trans e₁ e₂
    go (suc i) zero    eq =
      ⊥-elim (punchIn-≢ p (lookup σ i)
               (sym (trans-eq (sym eq) (tail-val i))))
      where
        open import Substrate.Foundation.Eq using (trans)
        trans-eq : lookup (insert-at p σ) zero ≡ lookup (insert-at p σ) (suc i) →
                   lookup (insert-at p σ) (suc i) ≡ punchIn p (lookup σ i) →
                   p ≡ punchIn p (lookup σ i)
        trans-eq e₁ e₂ = trans e₁ e₂
    -- two witnessed indices: punchIn injective, then σ injective.
    go (suc i) (suc j) eq =
      cong suc (σ-perm i j
        (punchIn-injective p
          (trans₃ (sym (tail-val i)) eq (tail-val j))))
      where
        open import Substrate.Foundation.Eq using (trans)
        trans₃ : punchIn p (lookup σ i) ≡ lookup (insert-at p σ) (suc i) →
                 lookup (insert-at p σ) (suc i) ≡ lookup (insert-at p σ) (suc j) →
                 lookup (insert-at p σ) (suc j) ≡ punchIn p (lookup σ j) →
                 punchIn p (lookup σ i) ≡ punchIn p (lookup σ j)
        trans₃ e₁ e₂ e₃ = trans e₁ (trans e₂ e₃)

------------------------------------------------------------------------
-- 3. Lift to the whole enumeration: EVERY entry of perms n is a genuine
--    permutation. (All P xs = P holds of every element.)
------------------------------------------------------------------------

All : {A : Set} → (A → Set) → List A → Set
All P []       = ⊤
All P (x ∷ xs) = P x × All P xs

All-++ : {A : Set} {P : A → Set} (xs ys : List A) →
         All P xs → All P ys → All P (xs ++ ys)
All-++ []       ys _          ay = ay
All-++ (x ∷ xs) ys (px , axs) ay = px , All-++ xs ys axs ay

All-mapL : {A B : Set} {P : B → Set} (f : A → B) (xs : List A) →
           ((x : A) → P (f x)) → All P (mapL f xs)
All-mapL f []       hyp = tt
All-mapL f (x ∷ xs) hyp = hyp x , All-mapL f xs hyp

-- witness-threading concatMap: the per-element property P(g x) may DEPEND
-- on a per-element witness Q x, supplied by All Q xs. (Here Q = IsPerm
-- comes from the inductive hypothesis on perms n — no postulate.)
All-concatMapL :
  {A B : Set} {P : B → Set} {Q : A → Set} (g : A → List B) (xs : List A) →
  All Q xs → ((x : A) → Q x → All P (g x)) → All P (concatMapL g xs)
All-concatMapL g []       _          hyp = tt
All-concatMapL g (x ∷ xs) (qx , qxs) hyp =
  All-++ (g x) (concatMapL g xs) (hyp x qx) (All-concatMapL g xs qxs hyp)

-- the empty permutation is trivially injective (Fin 0 is empty).
IsPerm-[] : IsPerm {0} []
IsPerm-[] () _ _

-- EVERY image vector the construction enumerates is a bijection: the tower
-- never leaves Sₙ. (Brick 1 complete — no postulates.)
perms-all-perm : (n : ℕ) → All IsPerm (perms n)
perms-all-perm zero    = IsPerm-[] , tt
perms-all-perm (suc n) =
  All-concatMapL
    (λ σ → mapL (λ p → insert-at p σ) (all-positions (suc n)))
    (perms n)
    (perms-all-perm n)
    (λ σ σ-perm →
      All-mapL (λ p → insert-at p σ) (all-positions (suc n))
        (λ p → insert-at-preserves p σ σ-perm))
