------------------------------------------------------------------------
-- Substrate.WitnessTower.KleinCensus
--
-- The second half of the full B3 count (the first half — 9 involutions by
-- cycle-type — is WitnessTower.FirstAppearance): the 4 Klein-four
-- subgroups of S₄, counted over the SAME iterated enumeration (perms 4),
-- carrying the computation up the tower rather than hardcoding S₄.
--
-- A Klein-four {id, a, b, ab} is determined by any two DISTINCT COMMUTING
-- involutions a, b (then ab is the third non-identity element, also an
-- involution). Each subgroup is generated by exactly 6 ordered pairs
-- (a,b) drawn from its 3 non-identity elements (3·2 = 6). So
--
--   #Klein-four subgroups  =  (#ordered commuting distinct involution pairs) / 6.
--
-- First-appearance signal (the point of the exercise): the Klein-four
-- group debuts at rung 4. Below it there are ZERO such pairs (rung 3 has
-- only 3 involutions, no two of which commute to a third involution), so
-- the V₄ object's first appearance is exactly rung 4 — the same inductive
-- seam the double-transposition debut marks in FirstAppearance.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.KleinCensus where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_)
open import Substrate.Foundation.Bool using (Bool; _∧_; not)
open import Substrate.Foundation.Eq using (_≡_; refl)

open import Substrate.WitnessTower.Enumerate
  using (Perm; perms; mapL; concatMapL; lengthL)
open import Substrate.WitnessTower.FirstAppearance
  using (is-involution; compose; _≡ᵇ_; filterL; ⌊_⌋)

------------------------------------------------------------------------
-- 1. The commuting-distinct-involution-pair predicate on a pair (a,b).
------------------------------------------------------------------------

-- a and b commute: ab = ba.
commute : {n : ℕ} → Perm n → Perm n → Bool
commute a b = compose a b ≡ᵇ compose b a

-- (a,b) generates a Klein-four: both involutions, distinct, and commuting.
-- (When a,b are distinct commuting involutions, ab is automatically an
-- involution ≠ id, a, b — so {id,a,b,ab} ≅ V₄.)
klein-pair : {n : ℕ} → Perm n → Perm n → Bool
klein-pair a b =
  is-involution a ∧ (is-involution b ∧ (not (a ≡ᵇ b) ∧ commute a b))

------------------------------------------------------------------------
-- 2. Count ordered Klein-generating pairs over the enumeration of rung n.
------------------------------------------------------------------------

klein-pairs : (n : ℕ) → ℕ
klein-pairs n =
  lengthL (filterL (λ b → b)
            (concatMapL (λ a → mapL (klein-pair a) (perms n)) (perms n)))

------------------------------------------------------------------------
-- 3. The census, refl over the enumeration. Each Klein-four is generated
--    by 6 ordered pairs, so klein-pairs / 6 = #subgroups.
------------------------------------------------------------------------

-- Rung 3 (S₃): no Klein-four — zero generating pairs.
klein-pairs-3-absent : klein-pairs 3 ≡ 0
klein-pairs-3-absent = refl

-- Rung 4 (S₄): 24 generating pairs = 4 subgroups × 6 ordered pairs each.
-- The V₄ group DEBUTS at rung 4.
klein-pairs-4 : klein-pairs 4 ≡ 24
klein-pairs-4 = refl

-- Hence #Klein-four subgroups in S₄ = 24 / 6 = 4 (dossier B3: 1 normal
-- gauge V₄ + 3 interface V₄s). The division is recorded as the witnessed
-- identity 4 × 6 ≡ klein-pairs 4.
klein-fours-count-4 : 4 + (4 + (4 + (4 + (4 + 4)))) ≡ klein-pairs 4
klein-fours-count-4 = refl
