------------------------------------------------------------------------
-- Substrate.WitnessTower.SignGrade2Generated
--
-- ◆ip-abel-α-Sₙ — the Sₙ instance of the "even ≠ prime" lemma: an EVEN
-- Coxeter derivation (signW g ≡ false) is a product of grade-2 words, and
-- conversely. This RELOCATES the ex-hardest crux (Aₙ generated by 3-cycles)
-- into two bounded new objects — flatten + signW-flatten — after which the
-- pairing is the trivial ParityKernel.Universal even↔pair.
--
--   flatten       — CoxGen derivation tree → in-order Word of sadj positions
--   signW-flatten — the Bool sign parity of the tree = the F₂ count-parity of
--                   the flattened word (tree xor-fold ≡ list parity)
--   even→grade2   — signW g ≡ false → Gr2Gen (flatten g)   [the relocated crux]
--   grade2→even   — Gr2Gen (flatten g) → signW g ≡ false   [the easy direction]
--
-- HONEST BOUNDARY: this is over the WORD/flatten normal form. flatten is the
-- single genuinely-new object (CoxGen is a binary tree; no CoxGen→Word existed);
-- everything downstream is the universal §even↔pair. It does NOT yet give
-- Aₙ = [Sₙ,Sₙ] as groups (that assembly = ◆ip-abel-cap).
--
-- --safe --without-K, no postulates/holes.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.SignGrade2Generated where

open import Substrate.Foundation.Nat using (ℕ; suc; _+_)
open import Substrate.Foundation.Fin.Fin
open import Substrate.Foundation.Bool using (Bool; false; _xor_)
open import Substrate.Foundation.Eq using (_≡_; refl; trans; sym; cong; cong₂)
open import Substrate.Algebra.F2 using (F₂; 𝟘) renaming (_+_ to _+F_)
open import Substrate.Algebra.F2.FromBool using (bool→F₂; F₂→bool; bool→F₂-xor; bool→F₂→bool)
open import Substrate.Algebra.N-to-F2-Parity using (parity; parity-+)
open import Substrate.Groups.Coxeter.Word using (Word; []; _∷_; _++_)
open import Substrate.Algebra.ParityKernel.Universal
  using (count; wpar; Gr2Gen; Gr2Gen→even; even→Gr2Gen)
open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral
  using (CoxGen; cox-id; cox-s; cox-∘; inj1)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermSign using (signW)

------------------------------------------------------------------------
-- 1. flatten — the CoxGen derivation tree → its in-order Word of sadj positions
--    (the FIRST CoxGen → Word normal form; CoxGen is a binary tree).
------------------------------------------------------------------------

flatten : {n : ℕ} {τ : Perm n} → CoxGen τ → Word (Fin n)
flatten cox-id      = []
flatten (cox-s j)   = inj1 j ∷ []
flatten (cox-∘ g h) = flatten g ++ flatten h

count-++ : {n : ℕ} (a b : Word (Fin n)) → count (a ++ b) ≡ count a + count b
count-++ []      b = refl
count-++ (x ∷ a) b = cong suc (count-++ a b)

------------------------------------------------------------------------
-- 2. signW-flatten — the tree's Bool sign parity = the flattened word's F₂
--    count-parity. Tree xor-fold ≡ list parity, via bool→F₂-xor + parity-+.
------------------------------------------------------------------------

signW-flatten : {n : ℕ} {τ : Perm n} (g : CoxGen τ) →
                bool→F₂ (signW g) ≡ wpar (flatten g)
signW-flatten cox-id    = refl
signW-flatten (cox-s j) = refl
signW-flatten (cox-∘ g h) =
  trans (bool→F₂-xor (signW g) (signW h))
    (trans (cong₂ _+F_ (signW-flatten g) (signW-flatten h))
      (trans (sym (parity-+ (count (flatten g)) (count (flatten h))))
             (cong parity (sym (count-++ (flatten g) (flatten h))))))

------------------------------------------------------------------------
-- 3. THE GRADE-2 CHARACTERIZATION of even Coxeter derivations.
------------------------------------------------------------------------

-- EASY: a grade-2-generated (paired) word has even sign.
grade2→even : {n : ℕ} {τ : Perm n} (g : CoxGen τ) →
              Gr2Gen (flatten g) → signW g ≡ false
grade2→even g gr =
  trans (sym (bool→F₂→bool (signW g)))
        (cong F₂→bool (trans (signW-flatten g) (Gr2Gen→even gr)))

-- THE RELOCATED CRUX: an even CoxGen derivation flattens to a grade-2-generated
-- word (⇒ every even perm is a product of grade-2 words, via coxeter-complete).
even→grade2 : {n : ℕ} {τ : Perm n} (g : CoxGen τ) →
              signW g ≡ false → Gr2Gen (flatten g)
even→grade2 g e =
  even→Gr2Gen (flatten g) (trans (sym (signW-flatten g)) (cong bool→F₂ e))
