------------------------------------------------------------------------
-- Substrate.WitnessTower.SignAbelianization
--
-- ⟡ip-abelianization (the reachable, tower-native core). "Route B (the sign
-- homomorphism) is F₂-terminal because Sₙ's abelianisation is Z/2" — the deep
-- classical fact. Its HEART, provable from what is already proven: the abelian
-- quotient keeps only the length PARITY (Z/2), NOT the length itself (Z).
--
--   · signW-invariant — the length PARITY is DERIVATION-INVARIANT: any two
--     Coxeter words for the SAME permutation have equal signW (= sign, via
--     sign-wd). This IS the well-defined Z/2 abelianisation character.
--   · length is NOT invariant — a concrete witness (matching the total-dichotomy
--     discipline of SignZ2Coordinates): the identity has a length-0 derivation
--     (cox-id) AND a length-2 one (a generator times itself, reduced by sadj-
--     involution). Their signW AGREES (both false); their lengthW DIFFERS (0 vs
--     2). So length does not descend to the group — only its parity does.
--
-- Together: Sₙ^ab retains exactly the parity = Z/2, tower-native, from proven
-- pieces (sign-wd + the tp-involutivity behind sadj).
--
-- HONEST REMAINDER (a labeled arc, NOT an obstruction). The FULL claim — the sign
-- is the UNIQUE nontrivial abelian character (no character finer than Z/2, i.e.
-- Aₙ = [Sₙ,Sₙ]) — needs group infrastructure this tree does not yet have: a Perm
-- INVERSE (SnGroup notes it unbuilt), commutators, and Aₙ generated by 3-cycles
-- (each a commutator). A genuine multi-piece construction; scoped, not walled.
--
-- --safe --without-K, no postulates/holes.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.SignAbelianization where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_)
open import Substrate.Foundation.Fin using (Fin)
open import Substrate.Foundation.Eq using (_≡_; refl; trans; sym; cong)
open import Substrate.Foundation.Bool using (Bool; false)
open import Substrate.Foundation.Negation using (¬_)
open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.FirstAppearance using (id-perm; compose)
open import Substrate.WitnessTower.SnGroup using (apply; apply-compose; apply-id; apply-injective)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermSign
  using (signW; sign-wd; sadj-realizes; tp; tp-inv)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral
  using (sadj; CoxGen; cox-id; cox-s; cox-∘)

------------------------------------------------------------------------
-- 1. THE ABELIANISATION CHARACTER — the length parity is derivation-invariant.
--    Any two Coxeter words for the same τ have equal signW (= sign τ). This is
--    the well-defined Z/2 character Sₙ → Z/2 = Sₙ^ab (as far as it is expressible).
------------------------------------------------------------------------

signW-invariant : {n : ℕ} {τ : Perm n} (g g' : CoxGen τ) → signW g ≡ signW g'
signW-invariant g g' = trans (sym (sign-wd g)) (sign-wd g')

------------------------------------------------------------------------
-- 2. LENGTH IS NOT INVARIANT — only its parity is. The word length as a ℕ, and
--    a concrete pair of derivations of the SAME element with different length.
------------------------------------------------------------------------

-- the Coxeter word length (count of generators) as a ℕ (not just its parity).
lengthW : {n : ℕ} {τ : Perm n} → CoxGen τ → ℕ
lengthW cox-id      = 0
lengthW (cox-s j)   = 1
lengthW (cox-∘ g h) = lengthW g + lengthW h

-- an adjacent transposition is an involution: sadj n j ∘ sadj n j = id.
-- (Lifted from tp-inv via sadj-realizes — the index map tp is self-inverse.)
sadj-involution : {n : ℕ} (j : Fin n) → compose (sadj n j) (sadj n j) ≡ id-perm (suc n)
sadj-involution {n} j = apply-injective (λ i →
  trans (apply-compose (sadj n j) (sadj n j) i)
    (trans (cong (apply (sadj n j)) (sadj-realizes n j i))
      (trans (sadj-realizes n j (tp j i))
        (trans (tp-inv j i) (sym (apply-id i))))))

-- the length-2 derivation: a generator times itself. By sadj-involution it
-- derives the identity — the same element as the length-0 cox-id.
double-gen : {n : ℕ} (j : Fin n) → CoxGen (compose (sadj n j) (sadj n j))
double-gen j = cox-∘ (cox-s j) (cox-s j)

derives-identity : {n : ℕ} (j : Fin n) → compose (sadj n j) (sadj n j) ≡ id-perm (suc n)
derives-identity = sadj-involution

-- LENGTH differs — 2 vs 0 — for two derivations of the (equal) identity.
lengthW-differs : {n : ℕ} (j : Fin n) →
                  ¬ (lengthW (double-gen j) ≡ lengthW (cox-id {suc n}))
lengthW-differs j ()

-- yet the PARITY (signW) agrees — both false — witnessing that only the parity,
-- not the length, descends to the group. That coarsening IS Sₙ^ab ≅ Z/2.
signW-agrees : {n : ℕ} (j : Fin n) → signW (double-gen j) ≡ signW (cox-id {suc n})
signW-agrees j = refl
