------------------------------------------------------------------------
-- Substrate.WitnessTower.Sn
--
-- CAPSTONE: "the witness tower IS a re-reading of Sₙ", as a machine-checked
-- bijection. The witnessing-insertion enumeration perms n, indexed by its
-- own positions Fin (length = n!), is:
--   * sound      — every index gives a genuine permutation   (brick 1)
--   * injective  — distinct indices give distinct permutations (brick 2)
--   * surjective — every permutation is some index            (brick 3)
-- over an index set of size n! (the length fold). That IS the Lehmer
-- bijection Fin (n!) ≅ Sₙ, here with Sₙ = the genuine bijections on Fin n
-- (image vectors v with lookup v injective). The list index is the rank;
-- enumerate is unrank. No div/mod, no postulates.
--
-- So the counts the censuses computed are not "Sₙ-shaped numbers over a
-- length-n! list" — they are the counts of Sₙ, generated BY the tower's
-- defining move. The re-reading is proved.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Sn where

open import Substrate.Foundation.Nat using (ℕ; zero; suc)
open import Substrate.Foundation.Fin using (Fin; zero; suc)
open import Substrate.Foundation.Eq using (_≡_; refl; cong; sym; subst)
open import Substrate.Foundation.Empty using (⊥-elim)
open import Substrate.Foundation.Negation using (¬_)
open import Substrate.Foundation.Product using (Σ; _,_)
open import Substrate.Foundation.List using (List; []; _∷_)

open import Substrate.WitnessTower.Enumerate
  using (Perm; perms; lengthL; factorial; perms-length)
open import Substrate.WitnessTower.IsPermutation using (IsPerm; All; perms-all-perm)
open import Substrate.WitnessTower.Complete using (_∈_; here; there; perms-complete)
open import Substrate.WitnessTower.DuplicateFree using (NoDup; perms-nodup)
  renaming (_∷_ to _◅_)

------------------------------------------------------------------------
-- 0. List indexing + its interaction with All / membership / NoDup.
------------------------------------------------------------------------

lookupL : {A : Set} (xs : List A) → Fin (lengthL xs) → A
lookupL (x ∷ xs) zero    = x
lookupL (x ∷ xs) (suc i) = lookupL xs i

lookupL-All :
  {A : Set} {P : A → Set} {xs : List A} →
  All P xs → (i : Fin (lengthL xs)) → P (lookupL xs i)
lookupL-All {xs = x ∷ xs} (px , pxs) zero    = px
lookupL-All {xs = x ∷ xs} (px , pxs) (suc i) = lookupL-All pxs i

lookupL→∈ : {A : Set} (xs : List A) (i : Fin (lengthL xs)) → lookupL xs i ∈ xs
lookupL→∈ (x ∷ xs) zero    = here
lookupL→∈ (x ∷ xs) (suc i) = there (lookupL→∈ xs i)

lookupL-injective :
  {A : Set} {xs : List A} → NoDup xs →
  {i j : Fin (lengthL xs)} → lookupL xs i ≡ lookupL xs j → i ≡ j
lookupL-injective (x∉xs ◅ nd) {zero}  {zero}  eq = refl
lookupL-injective (x∉xs ◅ nd) {zero}  {suc j} eq =
  ⊥-elim (x∉xs (subst (_∈ _) (sym eq) (lookupL→∈ _ j)))
lookupL-injective (x∉xs ◅ nd) {suc i} {zero}  eq =
  ⊥-elim (x∉xs (subst (_∈ _) eq (lookupL→∈ _ i)))
lookupL-injective (x∉xs ◅ nd) {suc i} {suc j} eq = cong suc (lookupL-injective nd eq)

∈→Fin : {A : Set} {x : A} {xs : List A} → x ∈ xs → Fin (lengthL xs)
∈→Fin here      = zero
∈→Fin (there p) = suc (∈→Fin p)

lookupL∘∈→Fin :
  {A : Set} {x : A} {xs : List A} (p : x ∈ xs) → lookupL xs (∈→Fin p) ≡ x
lookupL∘∈→Fin here      = refl
lookupL∘∈→Fin (there p) = lookupL∘∈→Fin p

------------------------------------------------------------------------
-- 1. The bijection Fin (n!) ≅ Sₙ. enumerate = unrank.
------------------------------------------------------------------------

module _ (n : ℕ) where

  -- the index set has size n! (the length fold).
  card : lengthL (perms n) ≡ factorial n
  card = perms-length n

  -- unrank: an index of perms n ↦ the permutation there.
  enumerate : Fin (lengthL (perms n)) → Perm n
  enumerate = lookupL (perms n)

  -- SOUND: every enumerated vector is a genuine permutation (brick 1).
  enumerate-is-perm : (i : Fin (lengthL (perms n))) → IsPerm (enumerate i)
  enumerate-is-perm = lookupL-All (perms-all-perm n)

  -- INJECTIVE: distinct indices give distinct permutations (brick 2).
  enumerate-injective :
    {i j : Fin (lengthL (perms n))} → enumerate i ≡ enumerate j → i ≡ j
  enumerate-injective = lookupL-injective (perms-nodup n)

  -- SURJECTIVE: every permutation is enumerated (brick 3).
  enumerate-surjective :
    (σ : Perm n) → IsPerm σ →
    Σ (Fin (lengthL (perms n))) (λ i → enumerate i ≡ σ)
  enumerate-surjective σ perm =
    ∈→Fin (perms-complete n σ perm) , lookupL∘∈→Fin (perms-complete n σ perm)
