------------------------------------------------------------------------
-- Substrate.Logic.Evidence.ElAtlas.OrbitCloudRung2  (Ⓟ.2 — rung-2 orbit cardinality = 2)
--
-- The orbit cloud at rung 2 (K₃): POINT_CLOUD §0, "rung 2 → collapses to 2".
-- K₃ has 3 oriented edges {e01, e02, e12} and a 1-DIMENSIONAL cycle space,
-- generated by the loop 0→1→2→0:  c = e01 − e02 + e12  (edge coords (1,−1,1)).
--
-- A vertex frame σ ∈ S₃ acts on edge space by the SIGNED permutation
-- e_{ij} ↦ ±e_{σi σj} (orientation), and on the 1-dim cycle space this is just
-- the SIGN of σ: even frames fix c, odd frames send c ↦ −c. So the orbit of c
-- under all 3! = 6 frames is exactly {c, −c} — cardinality 2.
--
-- The two S₃ generators (= OrbitCloud's `rot`, `swap` frames), with their
-- cycle-space action DERIVED as oriented edge permutations:
--   rot = (0 1 2):  e01↦e12, e02↦−e01, e12↦−e02  ⇒ (v0,v1,v2) ↦ (−v1, −v2, v0)
--   swap = (0 1):   e01↦−e01, e02↦e12, e12↦e02    ⇒ (v0,v1,v2) ↦ (−v0, v2, v1)
-- The orbit is shown CLOSED in {c, −c} under both generators (so it is ⊆ that
-- 2-set), the two points are DISTINCT, and both are realised (c, and −c = swap·c)
-- — hence the orbit is exactly {c, −c}, |orbit| = 2. (Ⓟ.3: rung 3 → 22.)
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Logic.Evidence.ElAtlas.OrbitCloudRung2 where

open import Substrate.Foundation.Vec using (Vec; _∷_; [])
open import Substrate.Foundation.Eq using (_≡_; refl; cong)
open import Substrate.Foundation.Empty using (⊥)
open import Substrate.Foundation.Product using (_×_; _,_)
open import Substrate.Algebra.Z using (ℤ; +_; -ℤ_)

------------------------------------------------------------------------
-- Edge space of K₃ and the cycle generator c (+ its reversal −c).
------------------------------------------------------------------------

Edge3 : Set
Edge3 = Vec ℤ 3                                 -- coords on (e01, e02, e12)

c negc : Edge3
c    = (+ 1) ∷ (-ℤ (+ 1)) ∷ (+ 1) ∷ []          -- the loop  e01 − e02 + e12
negc = (-ℤ (+ 1)) ∷ (+ 1) ∷ (-ℤ (+ 1)) ∷ []     -- its reversal −c

------------------------------------------------------------------------
-- The cycle-space (signed-edge) action of the two S₃ generators.
------------------------------------------------------------------------

act-rot act-swap : Edge3 → Edge3
act-rot  (v0 ∷ v1 ∷ v2 ∷ []) = (-ℤ v1) ∷ (-ℤ v2) ∷ v0 ∷ []
act-swap (v0 ∷ v1 ∷ v2 ∷ []) = (-ℤ v0) ∷ v2 ∷ v1 ∷ []

------------------------------------------------------------------------
-- The orbit of c is CLOSED in {c, −c} under both generators: rot (even) fixes
-- both, swap (odd) exchanges them. So orbit ⊆ {c, −c}, and both are realised.
------------------------------------------------------------------------

rot-fixes : (act-rot c ≡ c) × (act-rot negc ≡ negc)
rot-fixes = refl , refl

swap-flips : (act-swap c ≡ negc) × (act-swap negc ≡ c)
swap-flips = refl , refl

------------------------------------------------------------------------
-- The two orbit points are DISTINCT — so |orbit| = 2 exactly.
------------------------------------------------------------------------

vhead : Edge3 → ℤ
vhead (x ∷ _) = x

c≢negc : c ≡ negc → ⊥
c≢negc eq with cong vhead eq
... | ()
