------------------------------------------------------------------------
-- Substrate.Algebra.Lie.sl2
--
-- The Lie algebra sl(2) — 2×2 traceless matrices with bracket
-- [A, B] = AB - BA. Module-parametric per substrate convention:
-- the underlying LieAlgebra + the three basis elements E, H, F and
-- the standard sl₂ relations are user-supplied; the substrate names
-- the structure as "sl₂" via this module.
--
-- L14 of the L-arc. First concrete L2 [[LieAlgebra]] instance + first
-- substrate Lie algebra. Cartan type A₁ (rank 1, m matrix is the 1×1
-- matrix (1)).
--
-- Standard sl₂ relations (Chevalley basis):
--   [H, E] = 2 E
--   [H, F] = -2 F
--   [E, F] = H
-- Anti-commutativity gives [E, H] = -2 E, [F, H] = 2 F, [F, E] = -H.
--
-- Per [[continuous-via-discrete-inference-rules]]: the carrier is
-- abstract (user-supplied via the LieAlgebra parameter); the
-- substrate captures the structural identification of L as sl₂
-- via the basis + relations.
--
-- Per [[expose-generator-not-orbit]]: the GENERATORS are the three
-- basis elements E, H, F + the relations; the orbit is the full
-- sl₂ representation theory (= sl₂-modules, Verma modules, etc.).
--
-- Concrete consumers supply the LieAlgebra (e.g., 2×2-traceless
-- matrices over ℝ / ℂ; or polynomial bracket on ℂ[x] generated by
-- ∂/∂x, x∂/∂x, x²∂/∂x) + the three witness elements + the relation
-- equations.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

open import Level using (Level)
open import Substrate.Category.CartanType using (CartanType; mkCartanType)
open import Substrate.Category.LieAlgebra using (LieAlgebra)
open import Substrate.Foundation.Eq using (_≡_; refl)
open import Substrate.Foundation.Fin using (Fin)
open import Substrate.Foundation.Nat using (ℕ)

module Substrate.Algebra.Lie.sl2
  -- The substrate-internal LieAlgebra value witnessing sl₂.
  (L : LieAlgebra {Level.zero})
  -- The three Chevalley basis elements.
  (E H F : LieAlgebra.V L)
  -- The standard sl₂ relations (Chevalley basis form).
  -- [H, E] = 2 E = E +V E
  (HE-eq : LieAlgebra._·_ L H E ≡
           LieAlgebra._+V_ L E E)
  -- [H, F] + 2 F = 0V (= [H, F] = -2 F, expressed without negation)
  (HF-eq : LieAlgebra._+V_ L
             (LieAlgebra._·_ L H F)
             (LieAlgebra._+V_ L F F) ≡ LieAlgebra.0V L)
  -- [E, F] = H
  (EF-eq : LieAlgebra._·_ L E F ≡ H)
  where

------------------------------------------------------------------------
-- 1. sl₂ as a LieAlgebra.
--
-- Direct re-export — the substrate-side formal target is the
-- supplied LieAlgebra value, named structurally as sl₂.
------------------------------------------------------------------------

sl2-LieAlgebra : LieAlgebra
sl2-LieAlgebra = L

------------------------------------------------------------------------
-- 2. sl₂'s Cartan type: A₁.
--
-- Rank 1; the 1×1 m-matrix is (m_00 = 1). The CartanType A₁ is
-- the simplest non-empty Coxeter system: a single generator s with
-- s² = e.
------------------------------------------------------------------------

A1-rank : ℕ
A1-rank = 1

A1-m : Fin A1-rank → Fin A1-rank → ℕ
A1-m _ _ = 1

A1-m-diag : (i : Fin A1-rank) → A1-m i i ≡ 1
A1-m-diag _ = refl

A1-m-symm : (i j : Fin A1-rank) → A1-m i j ≡ A1-m j i
A1-m-symm _ _ = refl

sl2-CartanType : CartanType
sl2-CartanType = mkCartanType A1-rank A1-m A1-m-diag A1-m-symm

------------------------------------------------------------------------
-- 3. Capstone — sl₂ as L-arc concrete Lie algebra.
--
-- L14 of the L-arc. The substrate's first concrete Lie algebra
-- instance. With L14 landed:
--   * L2 LieAlgebra has a concrete instance (sl₂)
--   * L12 CartanType has a concrete instance (A₁)
--   * L13 Coxeter.AsCartanType is exercised at A₁
--
-- Per [[universal-property-discipline]]: the substrate captures sl₂
-- via the basis (E, H, F) + relations. The concrete realisations
-- (matrices over ℝ / ℂ; differential operators on ℂ[x]; quaternion-
-- imaginary-part) are supplied per consumer.
--
-- Per [[torsion-element-universal]]: sl₂ has a natural torsion
-- structure via the Cartan element H; (exp H) generates the maximal
-- torus. The substrate's HasOrder primitive applies once a concrete
-- realisation is in scope.
--
-- Next: L15 so₃ (= sl₂ over ℝ, real form; same A₁ Cartan type).
------------------------------------------------------------------------
