------------------------------------------------------------------------
-- Substrate.Category.UniversalProperty.Phase2
--
-- UP20 of the UP-topos arc per [scratch/up_topos_arc_plan.md].
--
-- Phase-2 capstone: site structure on UPCategory.
--
-- ===================================================================
-- PHASE-2 SUMMARY (UP11-UP20)
-- ===================================================================
--
--   UP11  Site.agda            Generic Site record + CoverData
--   UP12  Coverage.agda        UPCover record + Covering condition
--   UP13  Sieve.agda           Sieve record + max-Sieve
--   UP14  SieveClosure.agda    sieve generated by a UPCover
--   UP15  Pretopology.agda     Grothendieck pretopology record
--   UP16  CoverageAxioms.agda  identity / stability / transitivity
--   UP17  ConcreteCovers.agda  trivial-cover instance
--   UP18  Refinement.agda      Refines relation between covers
--   UP19  Saturation.agda      Saturated pretopology
--   UP20  Phase2.agda          this file
--
-- Phase-3 (UP21-UP30): presheaves + sheaves on UPCategory.
-- Phase-4 (UP31-UP40): Grothendieck topos.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.UniversalProperty.Phase2 where

open import Substrate.Category.Site                                public
  using (Site; CoverData)
open import Substrate.Category.UniversalProperty.Coverage          public
  using (UPCover)
open import Substrate.Category.UniversalProperty.Sieve             public
  using (Sieve; max-Sieve)
open import Substrate.Category.UniversalProperty.SieveClosure      public
  using (FactorsThroughCover; generated-Sieve; factor-precompose)
open import Substrate.Category.UniversalProperty.Pretopology       public
  using (UPPretopology)
open import Substrate.Category.UniversalProperty.CoverageAxioms    public
  using (singleton-id-Cover)
open import Substrate.Category.UniversalProperty.ConcreteCovers    public
  using (trivial-cover)
open import Substrate.Category.UniversalProperty.Refinement        public
  using (Refines)
open import Substrate.Category.UniversalProperty.Saturation        public
  using (Saturated)
