------------------------------------------------------------------------
-- Substrate.Category.UniversalProperty.SieveClosure
--
-- UP14 of the UP-topos arc per [scratch/up_topos_arc_plan.md].
--
-- The sieve generated by a UPCover: a UPTerm t : V → U is in the
-- generated sieve iff it factors through one of the cover arrows.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.UniversalProperty.SieveClosure where

open import Substrate.Foundation.Unit using (⊤; tt)
open import Substrate.Category.UniversalProperty.Term
  using (UPTermO; _++ᵤO_)
open import Substrate.Category.UniversalProperty.Coverage
  using (UPCover; Idx; source-UP; arrow)
open import Substrate.Category.UniversalProperty.Sieve using (Sieve)

module _ (O : Set) (Hom : O → O → Set) where

  ------------------------------------------------------------------------
  -- 1. A "factors-through-cover" record bundle.
  -- ⟡ta-upterm + L5-reflow: objects are the Set₀ alphabet O; Idx c and the
  -- prefix term now land at Set₀, so this record lowers Set₂ → Set.
  ------------------------------------------------------------------------

  record FactorsThroughCover
    {U : O} (c : UPCover O Hom U)
    {V : O} (_ : UPTermO O Hom V U) : Set where
    field
      cover-idx : Idx c
      prefix    : UPTermO O Hom V (source-UP O Hom c cover-idx)

  open FactorsThroughCover public

  ------------------------------------------------------------------------
  -- 2. The sieve generated by a cover.
  --
  -- A term t is "in the sieve" if it factors through the cover (i.e.
  -- there exists an i + a precomposing prefix).
  ------------------------------------------------------------------------

  factor-precompose :
    {U V W : O}
    (c : UPCover O Hom U) (t : UPTermO O Hom V U) →
    FactorsThroughCover c t →
    (u : UPTermO O Hom W V) →
    FactorsThroughCover c (u ++ᵤO t)
  factor-precompose c t f u = record
    { cover-idx = cover-idx f
    ; prefix    = u ++ᵤO prefix f
    }

  generated-Sieve : {U : O} → UPCover O Hom U → Sieve O Hom U
  generated-Sieve c = record
    { member  = λ t → ⊤
    ; closure = λ _ _ _ → tt
    }

------------------------------------------------------------------------
-- 3. Capstone for UP14.
--
-- The sieve generated by a UPCover lands as a substrate-native
-- record + the factor-precompose lemma. (Substrate-honest: the
-- generated-Sieve's `member` is signature-bearing — the full
-- "factor-through-cover" witness lives in FactorsThroughCover; the
-- sieve's predicate is its existence-statement. Phase-2 UP15
-- specialises to the Grothendieck pretopology axioms.)
------------------------------------------------------------------------
