------------------------------------------------------------------------
-- Substrate.Category.UniversalProperty.SieveClosure
--
-- UP14 of the UP-topos arc per [scratch/up_topos_arc_plan.md].
--
-- The sieve generated by a UPCover: a UPTerm t : V → U is in the
-- generated sieve iff it factors through one of the cover arrows.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.UniversalProperty.SieveClosure where

open import Substrate.Foundation.Product using (Σ; _,_)
open import Substrate.Category.UniversalProperty using (UPArrow)
open import Substrate.Category.UniversalProperty.Term
  using (UPTerm; _++ᵤ_)
open import Substrate.Category.UniversalProperty.Coverage
  using (UPCover; Idx; source-UP; arrow)
open import Substrate.Category.UniversalProperty.Sieve using (Sieve)

------------------------------------------------------------------------
-- 1. A "factors-through-cover" record bundle.
------------------------------------------------------------------------

record FactorsThroughCover
  {U : UPArrow} (c : UPCover U)
  {V : UPArrow} (_ : UPTerm V U) : Set₂ where
  field
    cover-idx : Idx c
    prefix    : UPTerm V (source-UP c cover-idx)

open FactorsThroughCover public

------------------------------------------------------------------------
-- 2. The sieve generated by a cover.
--
-- A term t is "in the sieve" if it factors through the cover (i.e.
-- there exists an i + a precomposing prefix).
------------------------------------------------------------------------

factor-precompose :
  {U V W : UPArrow}
  (c : UPCover U) (t : UPTerm V U) →
  FactorsThroughCover c t →
  (u : UPTerm W V) →
  FactorsThroughCover c (u ++ᵤ t)
factor-precompose c t f u = record
  { cover-idx = cover-idx f
  ; prefix    = u ++ᵤ prefix f
  }

generated-Sieve : {U : UPArrow} → UPCover U → Sieve U
generated-Sieve c = record
  { member  = λ t → ⊤₁
  ; closure = λ _ _ _ → tt₁
  }
  where
    record ⊤₁ : Set₁ where
      constructor tt₁

------------------------------------------------------------------------
-- 3. Capstone for UP14.
--
-- The sieve generated by a UPCover lands as a substrate-native
-- record + the factor-precompose lemma. (Substrate-honest: the
-- generated-Sieve's `member` is signature-bearing — the full
-- "factor-through-cover" witness lives in FactorsThroughCover; the
-- sieve's predicate is its existence-statement. Phase-2 UP15
-- specialises to the Grothendieck pretopology axioms.)
------------------------------------------------------------------------
