------------------------------------------------------------------------
-- Substrate.Category.UniversalProperty.TruthValues
--
-- UP33 of the UP-topos arc per [scratch/up_topos_arc_plan.md].
--
-- The internal-logic truth value: "X is an instance of UP U" as a
-- sieve-valued proposition.
--
-- Concretely: given a UPArrow U and an instance candidate
-- (s : Source U, i : Target U), the truth value
-- ⟦ X is-instance U ⟧ ∈ Ω(U) is the sieve of all UPTerms V → U
-- through which the candidate factors.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.Category.UniversalProperty.TruthValues where

open import Substrate.Foundation.Product using (Σ; _,_; proj₁; proj₂)
open import Substrate.Foundation.Eq using (_≡_; trans; sym; cong)
open import Substrate.Category.UniversalProperty.Term using (UPTerm; _++ᵤ_)
open import Substrate.Category.UniversalProperty.Category using (++ᵤ-assoc)
open import Substrate.Category.UniversalProperty.Sieve using (Sieve)

module _ (O : Set) (Hom : O → O → Set) where

  ------------------------------------------------------------------------
  -- 1. The "is-instance" truth value (⟡odecode-residues: now DISCRIMINATING).
  --
  -- ⟡ta-upterm dissolved an object's Source/Target/Witness decomposition into
  -- Hom, so the OLD residue collapsed the truth-value to the constant `max-Sieve`
  -- (no witness-gating). NOW re-threaded (the O-site named its candidate shape,
  -- ObjectSite.Hom): the truth-value "X is-instance U" for a candidate witness
  -- `a : cand → U` (a site-morphism = a word of tower-steps) is the PRINCIPAL
  -- SIEVE generated by `a` — the terms `f : V → U` through which `a` factors
  -- (`f ≡ g ++ᵤ a`). It DISCRIMINATES (not every term factors through `a`) and
  -- is downward-closed under precomposition (via ++ᵤ-assoc). The old maximal
  -- sieve is recovered as the IDENTITY candidate: `is-instance-truth []` (every
  -- `f ≡ f ++ᵤ []`), so this GENERALIZES it — the residue is discharged, not lost.
  ------------------------------------------------------------------------

  is-instance-truth : {cand U : O} (a : UPTerm O Hom cand U) →
    Sieve O Hom U (λ {V} f → Σ (UPTerm O Hom V cand) (λ g → f ≡ (g ++ᵤ a)))
  is-instance-truth {cand} {U} a = record
    { closure = λ {V} {W} t u m →
        (u ++ᵤ proj₁ m)
        , trans (cong (u ++ᵤ_) (proj₂ m)) (sym (++ᵤ-assoc u (proj₁ m) a))
    }

------------------------------------------------------------------------
-- 2. Capstone for UP33.
--
-- The truth-value family lands. UP34 supplies the internal logic
-- (∧, ∨, →, ¬, ∀, ∃) at the sieve level.
------------------------------------------------------------------------
