"""Eliza.SylowChain — semidirect decomposition + Sylow-product chain.

Mirrors the Sylow-decomposition part of `multi-route-equivariance`:
given g ∈ S₄, produce a chain witness `g ∈ InGenerated(⋃ Sylow)`. The
chain is a word over the named Sylow generators (V₄-generators and
S₃-section generators); together they generate S₄.

The substrate template:
  S₄ = V₄ ⋊ S₃           (semidirect product; V₄ ⊴ S₄)
  every g ∈ S₄ writes uniquely as g = v · s with v ∈ V₄, s ∈ S₃-section

Section choice (a chirality, per [[ordering-is-chirality-choice]]):
  S₃-section = permutations fixing the 4th element {(1,2,3,4),
    (2,1,3,4), (1,3,2,4), (2,3,1,4), (3,1,2,4), (3,2,1,4)}.

Per [[multi-route-equivariance-recovery]] / `MultiRouteEquivariance
.agda`: the chain IS the atlas-of-charts decomposition. Each component
(v, s) is the contribution of one Sylow's chart.

Further decomposition (S₃ = Z/3 ⋊ Z/2): a finer chain may break s into
(s_3, s_2) with s_3 ∈ Sylow-3, s_2 ∈ Sylow-2-section-in-S₃. We expose
both granularities; downstream uses the granularity it needs.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

from eliza.alphabets import (
    Chamber, ORIGIN, perm_compose, perm_inverse,
)


# --- V₄ ⊴ S₄: the 4 Klein-four elements ----------------------------------

V4_E:   Chamber = (1, 2, 3, 4)
V4_α:   Chamber = (2, 1, 4, 3)   # (12)(34)
V4_β:   Chamber = (3, 4, 1, 2)   # (13)(24)
V4_γ:   Chamber = (4, 3, 2, 1)   # (14)(23)

V4_ELEMENTS: Tuple[Chamber, ...] = (V4_E, V4_α, V4_β, V4_γ)
V4_SET = frozenset(V4_ELEMENTS)


# --- S₃-section: permutations fixing position 4 (chirality choice) -------
#
# The 6 S₃-section elements: permute {1,2,3}, fix 4. These cosets of V₄
# in S₄ exhaust S₄/V₄ ≅ S₃.

S3_E:    Chamber = (1, 2, 3, 4)
S3_12:   Chamber = (2, 1, 3, 4)    # (1 2)
S3_23:   Chamber = (1, 3, 2, 4)    # (2 3)
S3_13:   Chamber = (3, 2, 1, 4)    # (1 3)
S3_123:  Chamber = (2, 3, 1, 4)    # (1 2 3)
S3_132:  Chamber = (3, 1, 2, 4)    # (1 3 2)

S3_SECTION: Tuple[Chamber, ...] = (S3_E, S3_12, S3_23, S3_13, S3_123, S3_132)
S3_SET = frozenset(S3_SECTION)


# --- Sylow-3 ≤ S₃-section: order-3 cyclic, {(1,2,3), (1,3,2), e} --------

SYLOW3_ELEMENTS: Tuple[Chamber, ...] = (S3_E, S3_123, S3_132)
SYLOW3_SET = frozenset(SYLOW3_ELEMENTS)

# Sylow-2-in-S₃: a coset representative of S₃/Sylow-3, order 2. Choose
# the transposition (1 2). The other order-2 elements of S₃ ((2,3) and
# (1,3)) are in the other cosets.
S3_SYLOW2_COSET_REP: Chamber = S3_12


# --- Named Sylow generators (the ⋃ Sylow of MultiRouteEquivariance) ----

# V₄ is generated by α, β; γ = αβ (order-2 each, with γ = αβ).
V4_GENERATORS: Tuple[Chamber, ...] = (V4_α, V4_β)

# Sylow-3 is generated by a single 3-cycle.
SYLOW3_GENERATOR: Chamber = S3_123

# Sylow-2-in-S₃ is generated by the transposition (1 2).
S3_SYLOW2_GENERATOR: Chamber = S3_12


# --- C3: semidirect_decompose -------------------------------------------


@dataclass(frozen=True)
class SemidirectDecomposition:
    """g ∈ S₄ written uniquely as g = v · s with v ∈ V₄, s ∈ S₃-section."""
    v: Chamber
    s: Chamber

    def reconstruct(self) -> Chamber:
        return perm_compose(self.v, self.s)


def semidirect_decompose(g: Chamber) -> SemidirectDecomposition:
    """Given g ∈ S₄, find unique v ∈ V₄, s ∈ S₃-section with g = v · s.

    s is determined by the coset gV₄, which is determined by where g
    sends position 4 in {1,2,3,4}. Concretely: s ∈ S₃-section is the
    unique element in the same coset as g, found by enumeration over
    the 6 sections (small).

    v is then g · s⁻¹ ∈ V₄.
    """
    for s in S3_SECTION:
        v = perm_compose(g, perm_inverse(s))
        if v in V4_SET:
            return SemidirectDecomposition(v=v, s=s)
    raise ValueError(f"no semidirect decomposition for {g} — bug in V₄ or section table")


# --- C4: SylowChain word ------------------------------------------------


@dataclass(frozen=True)
class SylowChain:
    """A word over Sylow generators witnessing g ∈ InGenerated(⋃ Sylow).

    Structure: (v_part, s3_part, s2_part) where:
      * v_part  ∈ V₄ (a single element; V₄ is small enough to take wholesale)
      * s3_part ∈ Sylow-3 (a single 3-cycle power: e / (123) / (132))
      * s2_part ∈ {e, (1 2)} (the Sylow-2-coset-rep in S₃)

    Length conventions:
      * v_part word length: 0 if e, 1 if α or β, 2 if γ = α·β.
      * s3_part word length: 0 if e, 1 if (1 2 3), 2 if (1 3 2) = (1 2 3)².
      * s2_part word length: 0 if e, 1 if (1 2).

    Total chain length is the sum; minimum = 0 (identity), max = 4.
    """
    v: Chamber                 # V₄ element
    s3: Chamber                # Sylow-3 element ∈ SYLOW3_ELEMENTS
    s2: Chamber                # Sylow-2-coset element ∈ {S3_E, S3_12}

    def reconstruct(self) -> Chamber:
        """Product in the chain order: v · s3 · s2."""
        return perm_compose(perm_compose(self.v, self.s3), self.s2)

    @property
    def v_length(self) -> int:
        if self.v == V4_E: return 0
        if self.v in (V4_α, V4_β): return 1
        return 2  # V4_γ = α·β

    @property
    def s3_length(self) -> int:
        if self.s3 == S3_E: return 0
        if self.s3 == S3_123: return 1
        return 2  # S3_132 = (1 2 3)²

    @property
    def s2_length(self) -> int:
        return 0 if self.s2 == S3_E else 1

    @property
    def word_length(self) -> int:
        return self.v_length + self.s3_length + self.s2_length

    def __repr__(self) -> str:
        return (f"SylowChain(v={self.v}, s3={self.s3}, s2={self.s2}, "
                f"|w|={self.word_length})")


def build_chain(g: Chamber) -> SylowChain:
    """Decompose g into its Sylow chain.

    Procedure:
      1. semidirect_decompose: g = v · s with v ∈ V₄, s ∈ S₃-section.
      2. Within s, further decompose s = s3 · s2 with s3 ∈ Sylow-3,
         s2 ∈ {e, (1 2)}.
    Step 2 is finite enumeration over the 6×2 = 12 candidate (s3, s2)
    pairs; only those reconstructing s are valid, and the unique-coset
    structure guarantees one exists.
    """
    dec = semidirect_decompose(g)
    for s3 in SYLOW3_ELEMENTS:
        for s2 in (S3_E, S3_SYLOW2_COSET_REP):
            if perm_compose(s3, s2) == dec.s:
                return SylowChain(v=dec.v, s3=s3, s2=s2)
    raise ValueError(f"no Sylow chain for {g}: V₄ part = {dec.v}, S₃ part = {dec.s}")


# --- C5: ChainEquivarianceWitness ---------------------------------------


@dataclass
class ChainEquivarianceWitness:
    """Algebraic gate for the chain machinery.

    Three substrate-honest properties, all verified by exhaustive
    enumeration over the 24-element S₄ (cheap):

    (1) Round-trip: build_chain(g).reconstruct() == g for all g ∈ S₄.
    (2) Coverage: every g ∈ S₄ has a chain (i.e., InGenerated holds).
    (3) Uniqueness: build_chain is functional (single chain per g).

    No gt involvement. The chain transmits equivariance OVER the
    carrier (S₄), and these three properties are the substrate-side
    `multi-route-equivariance` claim at this carrier.
    """

    def verify(self) -> Tuple[bool, dict]:
        from eliza.manifold import Manifold
        m = Manifold()
        chambers = m.nodes
        round_trip_failures = 0
        chains: List[SylowChain] = []
        for g in chambers:
            chain = build_chain(g)
            chains.append(chain)
            if chain.reconstruct() != g:
                round_trip_failures += 1
        # Coverage: chains exist for every element (build_chain raises if not).
        coverage_ok = len(chains) == 24
        # Uniqueness: (v, s3, s2) triples are distinct across the 24 chambers.
        triples = {(c.v, c.s3, c.s2) for c in chains}
        unique_ok = len(triples) == 24

        length_distribution: dict = {}
        for c in chains:
            length_distribution[c.word_length] = (
                length_distribution.get(c.word_length, 0) + 1
            )

        ok = (round_trip_failures == 0) and coverage_ok and unique_ok
        return ok, {
            "round_trip_failures": round_trip_failures,
            "coverage": len(chains),
            "unique_triples": len(triples),
            "length_distribution": length_distribution,
        }


# --- Self-check ----------------------------------------------------------


def self_check(verbose: bool = True) -> bool:
    witness = ChainEquivarianceWitness()
    ok, report = witness.verify()

    if verbose:
        print("=== SylowChain — chain equivariance witness ===")
        print(f"  round-trip failures: {report['round_trip_failures']} / 24")
        print(f"  coverage:            {report['coverage']} / 24")
        print(f"  unique chain triples: {report['unique_triples']} / 24")
        print(f"  word-length distribution: {report['length_distribution']}")
        print(f"\nResult: {'OK' if ok else 'FAIL'}")
    return ok


if __name__ == "__main__":
    import sys
    sys.exit(0 if self_check() else 1)
