#!/usr/bin/env python3
# gen_reuse_index.py — mechanically generate catalog/reuse-index.md, the substrate's
# REUSE GUARD: a name -> canonical-home index of every data/record STRUCTURE, so a
# re-implementer (LLM or human) can look up "does X already exist, and where" BEFORE
# re-deriving it. The discoverability fix for the class of re-implementations the z47 arc
# surfaced (a Klein four-group already in Groups.V4, a continued-fraction real already in
# Algebra.R.Trace, a wedge already in Algebra.Wedge, a stream map now in
# Algebra.R.Trace.StreamMap, ...).
#
# The structure list is read from the TYPECHECKED .agdai cores via
# jea_agdai.core_intern_agdai (the same elaborated-core reader jea_pysim uses) — NOT by
# string-matching .agda source: the core gives the real Datatype/Record classification and
# full qnames, catching nested structures a col-0 regex misses. .agda is read only for the
# one-line human description (comments are not in the core). Markdown, not an Agda module:
# an index module would transitively import the whole repo and explode build time.
#
# Consume: grep catalog/reuse-index.md for your concept (V4 / Real / Wedge / Monoid /
# Stream / Trace / DivStr / ...). Regenerate: scripts/gen_reuse_index.py (idempotent, ~2min).
import os, re, sys, glob

ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_AG  = os.path.join(ROOT, "agda", "_build", "2.8.0", "agda")
SUB_AGDAI = os.path.join(BUILD_AG, "Substrate")
DOC       = os.path.join(ROOT, "catalog", "reuse-index.md")
sys.path.insert(0, os.path.join(ROOT, "jea", "metalanguage"))
from jea_pyalg import Intern          # noqa: E402
import jea_agdai                      # noqa: E402

shapetag = re.compile(r"⟦shape:[^⟧]*⟧")
decl_c   = re.compile(r"^\s*(?:data|record)\s+([^\s({:]+).*?--(.*)$")
idxkind  = re.compile(r"Registry|Generators|Index|Catalogue|Catalog|Bridge")

def agdai_module(p):
    rel = os.path.relpath(p, BUILD_AG)                 # Substrate/X/Y.agdai
    return rel[:-len(".agdai")].replace(os.sep, ".")

def agda_source(mod):
    return os.path.join(ROOT, "agda", mod.replace(".", os.sep) + ".agda")

def mod_purpose(text):
    for ln in text.splitlines()[:45]:
        s = ln.strip()
        if s.startswith("--") and "—" in s:            # "-- Substrate.X.Y — purpose"
            return s.lstrip("-").strip().split("—", 1)[1].strip()
    for ln in text.splitlines()[:45]:
        s = ln.strip().lstrip("-").strip()
        if len(s) > 12 and re.search(r"[a-z]", s) and not s.startswith("Substrate.") \
           and not set(s) <= set("- "):
            return s
    return ""

structs, idxmods, namehomes, failed = [], [], {}, 0
for dp, _, fns in os.walk(SUB_AGDAI):
    for fn in sorted(fns):
        if not fn.endswith(".agdai"):
            continue
        p   = os.path.join(dp, fn)
        mod = agdai_module(p)
        # --- structures from the typechecked core ---
        try:
            kinds = jea_agdai.core_intern_agdai(p, Intern()).get("kinds", {})
        except Exception:
            failed += 1
            continue
        core = [(q, k) for q, k in kinds.items() if k in ("Datatype", "Record")]
        if not core:
            continue
        # --- descriptions + purpose from the .agda source (best-effort) ---
        src = agda_source(mod)
        purpose, comments = "", {}
        if os.path.exists(src):
            text = open(src, encoding="utf-8").read()
            purpose = mod_purpose(text)
            for ln in text.splitlines():
                m = decl_c.match(ln)
                if m:
                    comments[m.group(1)] = shapetag.sub("", m.group(2)).strip()
        if idxkind.search(mod.rsplit(".", 1)[-1]):
            idxmods.append((mod, purpose))
        for q, k in core:
            name = q.rsplit(".", 1)[-1]
            desc = comments.get(name, "") or purpose
            structs.append((name, "data" if k == "Datatype" else "record", mod, desc))
            namehomes.setdefault(name, set()).add(mod)

structs.sort(key=lambda x: (x[0].lower(), x[2]))
nmods = len(set(s[2] for s in structs))
amb   = {n: h for n, h in namehomes.items() if len(h) > 1}

out = ["# Reuse index — the substrate's structures, by name\n",
       "_Auto-generated by `scripts/gen_reuse_index.py` from the typechecked `.agdai` cores "
       "(jea_agdai) — do not edit; regenerate._\n",
       "**Consult BEFORE building a new `data`/`record`.** Grep this file for the concept you're "
       "about to reinvent — `V4`, `Real`, `Wedge`, `Monoid`, `Stream`, `Trace`, `DivStr`, `Setoid`, "
       "`Newman`, … — to find its canonical home, then instantiate / relate-by-iso the existing "
       "structure instead of re-deriving it (the CLAUDE.md reuse-search discipline; structural "
       "search is `python jea/metalanguage/jea_pysim.py … --clusters`). A name with several homes → "
       "see *Multiply-homed* and pick by shape.\n",
       f"_{len(structs)} structures across {nmods} modules; {len(amb)} names multiply-homed"
       + (f"; {failed} cores unreadable" if failed else "") + "._\n",
       "## Start here — index / registry / bridge modules\n"]
for mod, purpose in sorted(set(idxmods)):
    out.append(f"- `{mod}`" + (f" — {purpose}" if purpose else ""))
out += ["", f"## Multiply-homed names ({len(amb)}) — one name, several structures; pick by shape\n"]
for n in sorted(amb, key=str.lower):
    out.append(f"- `{n}` — " + ", ".join(f"`{m}`" for m in sorted(amb[n])))
out += ["", "## Structures (data / record), alphabetical by name\n",
        "| name | kind | home | what |", "|---|---|---|---|"]
for name, kind, mod, desc in structs:
    d = re.sub(r"\s+", " ", desc).replace("|", r"\|")[:100]
    out.append(f"| `{name}` | {kind} | `{mod}` | {d} |")

os.makedirs(os.path.dirname(DOC), exist_ok=True)
open(DOC, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"reuse-index: {len(structs)} structures, {nmods} modules, {len(amb)} multiply-homed, "
      f"{len(set(idxmods))} index modules, {failed} unreadable -> catalog/reuse-index.md")
