#!/usr/bin/env python3
"""gen_build_makefiles.py — emit one Makefile per source directory for a
memory-confined, per-file Agda build.

WHY THIS SHAPE (read before changing):

  * The All.agda OOM is LOAD-bound: one process that imports the whole
    repo deserializes ~1200 interfaces at ~40x inflation
    (memory: project_oom_load_bound_finding_2026_06). The fix is to never
    co-resident the closure. This build runs ONE `agda` process PER FILE,
    so peak RSS is bounded by the single heaviest file's closure
    (~304 MB for PrimitiveInstances), not the sum.

  * make is a DISPATCHER, not a staleness tracker. make's mtime model
    (rebuild if X.agdai older than X.agda) is UNRELIABLE for Agda, whose
    staleness is TRANSITIVE: X.agdai can be newer than X.agda yet stale
    because something X imports changed — an edge make cannot see. So we
    do NOT let make decide freshness. make always invokes `agda` on every
    file; AGDA decides cached-vs-recheck (correctly, transitively) and
    no-ops fresh files cheaply (measured 0.08–0.74 s/file cached). This
    removes the only part that could cause silent staleness — the exact
    "too easy to not update everything" failure mode shard scripts have.

  * ANTI-DRIFT (the user's core concern): both FILES and SUBDIRS are
    listed EXPLICITLY in each generated Makefile (no globs). A new .agda
    file or a new directory that the generator has not seen trips
    `--check` (wired into pre-commit), and at build time a listed-but-
    absent or present-but-unlisted entry fails LOUDLY. Sync is never
    silent: if the tree and the makefiles disagree, the build blows up.

USAGE:
  scripts/gen_build_makefiles.py            # (re)generate makefiles
  scripts/gen_build_makefiles.py --check    # exit 1 if any Makefile is
                                            # missing or out of sync (CI/hook)

Then build (from agda/):
  make                  # check whole tree, per-file, capped, (add -jN for parallel)
  make -C Substrate/Groups   # check one subtree
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGDA_DIR = os.path.join(ROOT, "agda")
SRC = os.path.join(AGDA_DIR, "Substrate")
MEM_CAP = "1024m"           # per-file RTS heap cap; worst file ~304 MB → 3x headroom
MARKER = "# GENERATED by scripts/gen_build_makefiles.py — do not edit by hand."


def dirs_with_agda(start):
    """All directories under `start` that (transitively) contain .agda."""
    keep = set()
    for dp, _, fs in os.walk(start):
        if "_build" in dp.split(os.sep):
            continue
        if any(f.endswith(".agda") for f in fs):
            d = dp
            while d and d >= start:
                keep.add(d)
                if d == start:
                    break
                d = os.path.dirname(d)
    return sorted(keep)


def local_agda(d):
    return sorted(f for f in os.listdir(d) if f.endswith(".agda"))


def child_dirs(d, all_dirs):
    return sorted(
        name for name in os.listdir(d)
        if os.path.join(d, name) in all_dirs
    )


def makefile_text(d, all_dirs):
    files = local_agda(d)
    subs = child_dirs(d, all_dirs)
    rel_to_agda = os.path.relpath(d, AGDA_DIR)
    depth = len(rel_to_agda.split(os.sep))
    up = os.sep.join([".."] * depth)

    L = []
    L.append(MARKER)
    L.append("# Per-file, memory-confined Agda check for this directory.")
    L.append("# make = dispatcher only: it ALWAYS invokes agda per file; agda")
    L.append("# decides cached-vs-recheck (transitively correct). FILES and")
    L.append("# SUBDIRS are listed explicitly — a tree/makefile mismatch fails")
    L.append("# loudly (re-run scripts/gen_build_makefiles.py).")
    L.append("")
    L.append("AGDA ?= agda")
    L.append("AGDA_FLAGS ?= --safe --without-K")
    L.append(f"MEM_CAP ?= {MEM_CAP}")
    L.append(f"AGDA_ROOT := {up}")
    L.append("")
    L.append("FILES := " + " ".join(files))
    L.append("SUBDIRS := " + " ".join(subs))
    L.append("")
    L.append(".PHONY: all files subdirs $(SUBDIRS) check-sync clean")
    L.append("")
    L.append("all: check-sync subdirs files")
    L.append("")
    # Drift guard: the set of .agda on disk must equal $(FILES); likewise dirs.
    L.append("# Blow up if the directory's actual contents differ from this")
    L.append("# generated listing (new/removed file or subdir → regenerate).")
    L.append("check-sync:")
    # Normalise BOTH sides through identical newline-list + drop-empties +
    # sort, so a directory with no direct .agda (empty FILES) compares
    # equal to an empty `ls` instead of tripping on a stray space.
    L.append("\t@disk_files=`ls *.agda 2>/dev/null | sort`; \\")
    L.append("\t listed=`printf '%s\\n' $(FILES) | sed '/^$$/d' | sort`; \\")
    L.append("\t if [ \"$$disk_files\" != \"$$listed\" ]; then \\")
    L.append("\t   echo 'ERROR: $(CURDIR): .agda files differ from generated FILES list.'; \\")
    L.append("\t   echo '  on disk : '\"`echo $$disk_files | tr '\\n' ' '`\"; \\")
    L.append("\t   echo '  listed  : '\"`echo $$listed | tr '\\n' ' '`\"; \\")
    L.append("\t   echo '  Run scripts/gen_build_makefiles.py.'; exit 1; \\")
    L.append("\t fi")
    L.append("")
    L.append("# One agda process PER FILE, RTS heap-capped, invoked from agda/")
    L.append("# so the .agda-lib / _build resolve. Always runs; agda no-ops if")
    L.append("# the interface is already current.")
    L.append("files:")
    L.append("\t@for f in $(FILES); do \\")
    L.append("\t  echo \"  check $(CURDIR)/$$f\"; \\")
    L.append("\t  $(AGDA) $(AGDA_FLAGS) +RTS -M$(MEM_CAP) -RTS -i $(AGDA_ROOT) $(CURDIR)/$$f || exit 1; \\")
    L.append("\tdone")
    L.append("")
    L.append("subdirs: $(SUBDIRS)")
    L.append("")
    for s in subs:
        L.append(f"{s}:")
        L.append(f"\t@if [ ! -f $@/Makefile ]; then \\")
        L.append(f"\t  echo 'ERROR: $(CURDIR)/$@ has no generated Makefile (new directory?).'; \\")
        L.append(f"\t  echo '  Run scripts/gen_build_makefiles.py.'; exit 1; \\")
        L.append(f"\tfi")
        L.append(f"\t@$(MAKE) -C $@")
        L.append("")
    L.append("clean:")
    for s in subs:
        L.append(f"\t@$(MAKE) -C {s} clean 2>/dev/null || true")
    L.append("\t@true")
    L.append("")
    return "\n".join(L)


def root_text(all_dirs):
    return "\n".join([
        MARKER,
        "# Top-level entry: per-file, memory-confined Agda build.",
        "# `make` checks the whole Substrate tree, one agda process per file.",
        "# Correctness is Agda's (re-checks stale deps transitively); make only",
        "# bounds RAM and provides parallelism (-jN). See",
        "# scripts/gen_build_makefiles.py.",
        "",
        ".PHONY: all clean check check-makefiles check-defproof check-vacuity check-index check-import check-decltag check-carrier advise",
        "all:",
        "\t@$(MAKE) -C Substrate",
        "clean:",
        "\t@$(MAKE) -C Substrate clean",
        "# Aggregate invariant GATE (same checks the pre-commit hook runs):",
        "# def/proof separation + makefile-tree sync + UP non-vacuity + shape index. Blocking.",
        "check: check-defproof check-makefiles check-vacuity check-index check-import check-decltag check-carrier",
        "\t@echo 'all invariant checks passed.'",
        "# Verify the makefile tree is in sync with the source tree.",
        "check-makefiles:",
        "\t@python3 ../scripts/gen_build_makefiles.py --check",
        "# Verify def/proof separation (definition-providers import no proof modules).",
        "check-defproof:",
        "\t@../scripts/check_def_proof_separation.sh",
        "# Verify no vacuous (⊤-collapse) universal properties outside the sanctioned two.",
        "check-vacuity:",
        "\t@../scripts/check_up_nonvacuity.sh",
        "# Verify the shape-node collision index is current (names→shapes, visible).",
        "check-index:",
        "\t@python3 ../scripts/sppf_node_index.py --check",
        "# Ratchet: no NEW bare imports of genuinely-ambiguous names (specialize by shape).",
        "check-import:",
        "\t@python3 ../scripts/check_import_shape.py --quiet",
        "# Every genuinely-ambiguous declaration carries a visible shape tag.",
        "check-decltag:",
        "\t@python3 ../scripts/decl_shape_tag.py",
        "# Canonical operators live in their carrier's home, one-per-file (no forks/buckets).",
        "check-carrier:",
        "\t@python3 ../scripts/check_carrier_locality.py --quiet",
        "# ADVISORY (non-blocking): judgment reports, deliberately NOT in `check` /",
        "# the hook (each has real false positives, so they inform, never gate):",
        "#   * theorem-per-file pressure (signature counts)",
        "#   * categorical grounding (domain algebraic modules w/ no Category dep)",
        "advise:",
        "\t@../scripts/check_file_sizes.sh",
        "\t@../scripts/check_categorical_grounding.sh",
        "",
    ])


def main():
    check = "--check" in sys.argv
    all_dirs = dirs_with_agda(SRC)
    targets = {os.path.join(d, "Makefile"): makefile_text(d, all_dirs) for d in all_dirs}
    targets[os.path.join(AGDA_DIR, "Makefile")] = root_text(all_dirs)

    if check:
        problems = []
        for path, body in targets.items():
            if not os.path.exists(path):
                problems.append("missing: " + os.path.relpath(path, ROOT))
            elif open(path, encoding="utf8").read() != body:
                problems.append("stale:   " + os.path.relpath(path, ROOT))
        # also: any dir with .agda that has NO Makefile target (defensive)
        if problems:
            print("gen_build_makefiles --check: FAILED")
            for p in problems:
                print("  " + p)
            print("Run scripts/gen_build_makefiles.py to regenerate.")
            sys.exit(1)
        print(f"gen_build_makefiles --check: OK ({len(targets)} makefiles current)")
        sys.exit(0)

    written = 0
    for path, body in targets.items():
        old = open(path, encoding="utf8").read() if os.path.exists(path) else None
        if old != body:
            open(path, "w", encoding="utf8").write(body)
            written += 1
    print(f"gen_build_makefiles: wrote/updated {written} of {len(targets)} makefiles "
          f"across {len(all_dirs)} source dirs.")


if __name__ == "__main__":
    main()
