#!/usr/bin/env python3
# gen_reuse_graph.py — the structure REFINEMENT/REFERENCE graph: nodes = data/record
# structures, edge X -> Y iff X's elaborated core REFERENCES Y (Y is a component/parent X is
# built on). Extracted from the RAW agdai_shim cores, whose nodes carry qname references
# (constructor/qname/children) — the interned form (gen_reuse_index) is shape-normalized and
# drops them. Complements the flat reuse-index (name->home) + its parallel-detector with the
# EDGE layer the other-LLM asked for (DivStr <- GradedDivStr <- ...), and yields the
# "highly-reused primitive vs never-refined" degree ranking.
#
# Emits, in formats the LLM-consumer is fluent in (trained-on) + that have tooling:
#   catalog/reuse-graph.dot — every structure->structure edge (GraphViz; queryable/renderable).
#   catalog/reuse-graph.md  — a Mermaid slice of the top reuse-primitives + their refiners,
#                             plus the in/out-degree ranking.
# Regenerate: scripts/gen_reuse_graph.py [path-substring-filter]  (~3min full; runs the shim raw).
import os, sys, json, subprocess, collections

ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD_AG  = os.path.join(ROOT, "agda", "_build", "2.8.0", "agda")
SUB_AGDAI = os.path.join(BUILD_AG, "Substrate")
SHIM      = os.path.join(ROOT, "jea", "metalanguage", "agdai_shim")
DOT       = os.path.join(ROOT, "catalog", "reuse-graph.dot")
MD        = os.path.join(ROOT, "catalog", "reuse-graph.md")
FILT      = sys.argv[1] if len(sys.argv) > 1 else ""

def shim_raw(agdai):
    r = subprocess.run([SHIM, os.path.abspath(agdai)], capture_output=True, text=True,
                       cwd=os.path.dirname(agdai))
    return r.stdout if r.returncode == 0 else None

struct_kind, refs, failed = {}, {}, 0     # qname->'data'/'record'; struct-qname->set(refd qnames)
for dp, _, fns in os.walk(SUB_AGDAI):
    for fn in sorted(fns):
        if not fn.endswith(".agdai") or (FILT and FILT not in os.path.join(dp, fn)):
            continue
        out = shim_raw(os.path.join(dp, fn))
        if out is None:
            failed += 1
            continue
        nodes, defmarks = {}, []
        for line in out.splitlines():
            try:
                rec = json.loads(line)
            except Exception:
                continue
            if "unit" in rec:
                defmarks.append((rec["unit"], rec["root"], rec.get("kind")))
            elif "id" in rec:
                nodes[rec["id"]] = (rec.get("qname"), rec.get("children", []))
        for unit, root, kind in defmarks:
            if kind not in ("Datatype", "Record"):
                continue
            struct_kind[unit] = "data" if kind == "Datatype" else "record"
            seen, refd, stack = set(), set(), [root]
            while stack:
                i = stack.pop()
                if i in seen or i not in nodes:
                    continue
                seen.add(i)
                qn, ch = nodes[i]
                if qn:
                    refd.add(qn)
                stack.extend(ch)
            refs[unit] = refd

structs = set(struct_kind)

def owner_struct(qn):                      # longest prefix of qn that is itself a structure
    parts = qn.split(".")
    for j in range(len(parts), 0, -1):
        p = ".".join(parts[:j])
        if p in structs:
            return p
    return None

edges = set()
for x, rs in refs.items():
    for r in rs:
        y = owner_struct(r)
        if y and y != x:
            edges.add((x, y))

indeg  = collections.Counter(y for _, y in edges)
outdeg = collections.Counter(x for x, _ in edges)
short  = lambda q: q.rsplit(".", 1)[-1]
home   = lambda q: q.rsplit(".", 1)[0]

# --- DOT: every edge (tooling) ---
dl = ['digraph reuse {', '  rankdir=LR; node [shape=box, fontsize=9];',
      '  // structure X -> Y : X is built on / refines Y. Auto-generated: scripts/gen_reuse_graph.py']
for q, k in sorted(struct_kind.items()):
    dl.append(f'  "{q}" [label="{short(q)}\\n{home(q)}"{"" if k=="record" else ", style=rounded"}];')
for x, y in sorted(edges):
    dl.append(f'  "{x}" -> "{y}";')
dl.append("}")
os.makedirs(os.path.dirname(DOT), exist_ok=True)
open(DOT, "w", encoding="utf-8").write("\n".join(dl) + "\n")

# --- MD: Mermaid slice of the top reuse-primitives + refiners, + degree ranking ---
TOPN = 12
prims = [q for q, _ in indeg.most_common(TOPN)]
prims_set = set(prims)
ml = ["# Reuse graph — structure refinement (who is built on whom)\n",
      "_Auto-generated by `scripts/gen_reuse_graph.py` from the RAW `.agdai` cores (qname references "
      "intact; the interned form is shape-normalized and loses them) — do not edit; regenerate._\n",
      f"_{len(struct_kind)} structures, {len(edges)} refinement edges"
      + (f"; {failed} cores unreadable" if failed else "") + "._\n",
      "**Reading:** `X --> Y` means X's elaborated core is built on Y (Y is a field/parameter/component "
      "of X). Before reinventing a structure, check whether the thing you want already **refines** an "
      "existing primitive here. Full graph: `catalog/reuse-graph.dot` (GraphViz). Mermaid slice below = "
      "the top reuse-primitives (highest in-degree — the most-built-on) and their direct refiners.\n",
      "## Most-reused primitives (in-degree) — the centers everything is built on\n",
      "| structure | ← refined by | home |", "|---|---:|---|"]
for q, d in indeg.most_common(25):
    ml.append(f"| `{short(q)}` | {d} | `{home(q)}` |")
ml += ["", "## Most-composite structures (out-degree) — built on the most others\n",
       "| structure | → builds on | home |", "|---|---:|---|"]
for q, d in outdeg.most_common(15):
    ml.append(f"| `{short(q)}` | {d} | `{home(q)}` |")
ml += ["", f"## Mermaid — top {TOPN} primitives + their refiners\n", "```mermaid", "graph LR"]
def nid(q):                                # mermaid-safe node id
    return "n" + str(abs(hash(q)) % (10 ** 9))
emitted = set()
for x, y in sorted(edges):
    if y in prims_set:                     # edges INTO a top primitive (its refiners)
        for q in (x, y):
            if q not in emitted:
                ml.append(f'  {nid(q)}["{short(q)}"]')
                emitted.add(q)
        ml.append(f"  {nid(x)} --> {nid(y)}")
ml += ["```", ""]
open(MD, "w", encoding="utf-8").write("\n".join(ml) + "\n")

print(f"reuse-graph: {len(struct_kind)} structures, {len(edges)} edges, {failed} unreadable "
      f"-> catalog/reuse-graph.dot + .md")
if FILT:
    print("top in-degree:", [(short(q), d) for q, d in indeg.most_common(8)])
