#!/usr/bin/env python3
"""gen_build_makefiles.py — emit a SINGLE flat import-DAG Makefile (agda/Flat.mk)
plus a thin root agda/Makefile, for a memory-confined, per-file Agda build.

WHY THIS SHAPE (read before changing):

  * The All.agda OOM is LOAD-bound: one process that imports the whole
    repo deserializes ~1200 interfaces at ~40x inflation
    (memory: project_oom_load_bound_finding_2026_06). The fix is to never
    co-resident the closure. This build runs ONE `agda` process PER FILE,
    so peak RSS is bounded by the single heaviest file's closure
    (~304 MB for PrimitiveInstances), not the sum.

  * ⟡make-import-dag — ONE flat makefile, per-module `m/<Module>` phony
    target carrying its DIRECT-import prerequisites, so `make -j` builds in
    true IMPORT-DAG topological order (a module's imports land as fresh
    .agdai FIRST, independents run concurrently). This replaced the 280
    per-DIRECTORY recursive makefiles, whose ordering encoded only the
    directory tree — 99.6% of the real import edges were UNORDERED, so a
    cold `make -j` built imports on-the-fly IN-PROCESS (inflated heap, an
    OOM storm, and mis-attributed offenders under interleaved -j logs).

  * EDGES ARE SOURCE-PARSED, not catalog.db. catalog.db's `module_edges`
    is SEMANTIC (elaborated-core name-references) and DROPS build-required
    edges (e.g. V4-as-PFG imports Foundation.Nat in source but the ℕ refs
    normalize away in the core). Source-parsing `open import`/`import` is
    the SOUND super-set of direct build deps, always fresh (no catalog.db
    dependency, no bootstrap cycle), and needs no special-casing for the
    ~111 def-less `open import … public` re-export aggregators (their
    children ARE in their source).

  * make is a DISPATCHER, not a staleness tracker. The m/<Module> targets
    are .PHONY, so make ALWAYS invokes `agda` per file; AGDA decides
    cached-vs-recheck (correctly, TRANSITIVELY — an edge make's mtime model
    cannot see) and no-ops fresh files cheaply (0.08–0.74 s cached). A
    STALE import edge (source gained an import since the last regen) costs
    only parallelism-on-one-edge, NEVER soundness: agda re-checks the dep
    in-process. So freshness is Agda's; make only orders + bounds RAM.

  * ANTI-DRIFT: MODULES is listed EXPLICITLY (no globs). The whole-tree
    check-sync recipe blows up loudly if the on-disk .agda set differs from
    the generated MODULES, and `--check` (wired into pre-commit) fails if
    Flat.mk / the root Makefile are stale. Sync is never silent.

USAGE:
  scripts/gen_build_makefiles.py            # (re)generate agda/Flat.mk + agda/Makefile
  scripts/gen_build_makefiles.py --check    # exit 1 if either is missing or stale (CI/hook)

Then build (from agda/):
  make            # whole tree, per-file, RAM-capped, import-DAG-ordered (add -jN)
  make -f Flat.mk m/Substrate.Foundation.Fin   # one module (+ its import closure)
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _agdatext import strip   # noqa: E402  (single-source Agda comment stripper)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGDA_DIR = os.path.join(ROOT, "agda")
SRC = os.path.join(AGDA_DIR, "Substrate")
MEM_CAP = "256m"            # ⟡cap-384: per-file RTS heap cap (was 1024m). make (shim→membudget)
                            # is the SINGLE build path: membudget cgroup caps maxRSS≤384 (owns retry),
                            # this +RTS -M caps GHC heap≤256. Whole tree passes; a >256 heap module
                            # must seal its heavy neutrals opaque or prove cheaper (⟡cap-384 forcing fn).
MARKER = "# GENERATED by scripts/gen_build_makefiles.py — do not edit by hand."
SHIM_DIR = os.path.join(ROOT, "scripts", "agda-shim")   # the membudget agda wrapper

# source-parse: an `open import`/`import` line's first token is the imported module path.
IMPRE = re.compile(r"^\s*(?:open\s+import|import)\s+([A-Za-z0-9_.'-]+)", re.M)


def _shim_block():
    """Makefile lines that put the membudget agda-shim on PATH (idempotent) so `make` ALWAYS routes agda
    through the controlled+instrumented wrapper — RAM-budget semaphore (make -j self-throttles, no manual
    `source membudget-shrc`) + always-on proof-cost profiling. Exported → recipes AND sub-makes inherit it;
    the findstring guard keeps it from re-prepending across the recursion. membudget auto-inits its budget
    on first use, so an un-`init`'d make still works. Disable profiling: MEMBUDGET_NOPROFILE=1. Pin a
    specific agda: `make AGDA=/path/to/agda` (?= preserved)."""
    return [
        "# membudget agda-shim → make is the controlled+instrumented build path (RAM-budgeted + proof-cost",
        "# profiled). Idempotent (findstring); exported to recipes + sub-makes. MEMBUDGET_NOPROFILE=1 to skip",
        "# profiling; `make AGDA=…` to pin a different agda.",
        f"SHIM_DIR := {SHIM_DIR}",
        "ifeq (,$(findstring $(SHIM_DIR),$(PATH)))",
        "export PATH := $(SHIM_DIR):$(PATH)",
        "endif",
        "",
    ]


def parse_tree():
    """Walk Substrate/**.agda → ({module_name: src_relpath}, {module: set(direct in-tree import modules)}).

    Module name = the PATH-derived name (Agda requires the declared name match the path under the include
    root, so this == the `module X where` name == every `open import X` string). Imports are source-parsed
    (SOUND super-set of build deps); restricted to modules present on disk. Src relpath is `Substrate/…/X.agda`
    relative to agda/ (the -i root the build runs from)."""
    disk = {}
    for dp, _, fns in os.walk(SRC):
        if "_build" in dp.split(os.sep):
            continue
        for fn in fns:
            if not fn.endswith(".agda"):
                continue
            rel = os.path.relpath(os.path.join(dp, fn), AGDA_DIR)   # Substrate/…/X.agda
            disk[rel[:-5].replace(os.sep, ".")] = rel               # only '.'→module-sep; '-' stays
    deps = {m: set() for m in disk}
    for m, rel in disk.items():
        t = strip(open(os.path.join(AGDA_DIR, rel), encoding="utf-8").read())
        for im in IMPRE.finditer(t):
            d = im.group(1)
            if d in disk and d != m:
                deps[m].add(d)
    return disk, deps


def kahn_check(disk, deps):
    """Agda modules are acyclic; a cycle would hang `make`. Kahn topo-sort as the gen-time gate (exit 2)."""
    from collections import deque
    radj = {m: set() for m in disk}          # dep -> {modules that depend on it}
    for m in disk:
        for d in deps[m]:
            radj[d].add(m)
    indeg = {m: len(deps[m]) for m in disk}
    q = deque(m for m in disk if indeg[m] == 0)
    seen = 0
    while q:
        x = q.popleft()
        seen += 1
        for m in radj[x]:
            indeg[m] -= 1
            if indeg[m] == 0:
                q.append(m)
    if seen != len(disk):
        cyc = [m for m in disk if indeg[m] > 0]
        print(f"gen_build_makefiles: ⚠ import CYCLE among {len(cyc)} modules "
              f"(make would hang): {cyc[:8]}", file=sys.stderr)
        sys.exit(2)


def flat_text(disk, deps):
    kahn_check(disk, deps)
    mods = sorted(disk)
    L = []
    L.append(MARKER)
    L.append("# ⟡make-import-dag: SINGLE flat makefile. Per-module m/<Module> phony target + its DIRECT-import")
    L.append("# prereqs (SOURCE-PARSED from `open import`/`import`, NOT catalog.db) → `make -j` builds in true")
    L.append("# import-DAG order (deps as .agdai first, independents concurrent). make = dispatcher; agda")
    L.append("# decides cached-vs-recheck transitively. A stale edge costs parallelism, never soundness.")
    L.append("# Invoked from agda/. Regenerate: scripts/gen_build_makefiles.py.")
    L.append("")
    L.extend(_shim_block())
    L.append("AGDA ?= agda")
    L.append("AGDA_FLAGS ?= --safe --without-K")
    L.append(f"MEM_CAP ?= {MEM_CAP}")
    L.append("AGDA_ROOT := .")
    L.append("SCRIPTS := ../scripts")   # ⟡gqs-make-targets: sppf_db.py (the per-core ingest) home
    L.append("")
    L.append("MODULES := " + " ".join(mods))
    L.append("MTARGETS := $(MODULES:%=m/%)")
    L.append("ITARGETS := $(MODULES:%=i/%)")
    L.append("")
    L.append(".PHONY: all check-sync ingest clean $(MTARGETS) $(ITARGETS)")
    L.append("")
    L.append("all: check-sync $(MTARGETS)")
    L.append("")
    # ⟡mid-check-sync: whole-tree drift gate (the 280 per-dir check-sync recipes collapse into ONE).
    L.append("# Blow up if the on-disk .agda set differs from the generated MODULES (new/removed file →")
    L.append("# regenerate). Both sides normalised through newline-list + drop-empties + sort.")
    L.append("check-sync:")
    L.append("\t@disk=`find Substrate -name '*.agda' | sed 's#/#.#g; s#\\.agda$$##' | sort`; \\")
    L.append("\t listed=`printf '%s\\n' $(MODULES) | tr ' ' '\\n' | sed '/^$$/d' | sort`; \\")
    L.append("\t if [ \"$$disk\" != \"$$listed\" ]; then \\")
    L.append("\t   echo 'ERROR: on-disk .agda set differs from Flat.mk MODULES.'; \\")
    L.append("\t   echo '  Run scripts/gen_build_makefiles.py.'; exit 1; \\")
    L.append("\t fi")
    L.append("")
    # One agda process PER FILE, RTS heap-capped, invoked from agda/ so .agda-lib/_build resolve. Always
    # runs (phony); agda no-ops a current interface cheaply. Import prereqs give the -j DAG order.
    L.append("# ── compile: m/<Module> depends on m/<direct-import> ─────────────────────────────────────")
    for m in mods:
        pre = " ".join(f"m/{d}" for d in sorted(deps[m]))
        L.append(f"m/{m}: {pre}".rstrip())
        L.append(f"\t@$(AGDA) $(AGDA_FLAGS) +RTS -M$(MEM_CAP) -RTS -i $(AGDA_ROOT) $(AGDA_ROOT)/{disk[m]}")
    L.append("")
    # ⟡gqs-make-targets: parallel-to-compile SPPF ingest — one --ingest-core per module (INDEPENDENT of the
    # compile; WAL+busy_timeout in sppf_db → parallel decode / serialized insert; self-skips unadvanced cores).
    # The root `catalog` target uses the BATCHED engine instead; these `i/` targets are the run-alongside form.
    L.append("# ── ingest: parallel-to-compile SPPF internment (run `make -f Flat.mk ingest` alongside) ──")
    L.append("ingest: $(ITARGETS)")
    for m in mods:
        L.append(f"i/{m}:")
        L.append(f"\t@python3 $(SCRIPTS)/sppf_db.py --ingest-core $(AGDA_ROOT)/{disk[m]}")
    L.append("")
    L.append("clean:")
    L.append("\t@true")
    L.append("")
    return "\n".join(L)


def root_text():
    """Thin root agda/Makefile — root-only targets (shim/catalog/check*/advise) + `all`/`clean` delegating
    to Flat.mk. `make -C agda -j` (the pre-commit gate) runs `all` → the flat import-DAG build under one
    jobserver. NOT recursive-agda; the compile lives entirely in Flat.mk."""
    return "\n".join([
        MARKER,
        "# Top-level entry: per-file, memory-confined Agda build. `all` delegates to the flat import-DAG",
        "# makefile (Flat.mk); root-only invariant/catalog/advise targets live here. Correctness is Agda's",
        "# (transitive re-check); make bounds RAM + orders by import DAG. See scripts/gen_build_makefiles.py.",
        "",
        *_shim_block(),
        ".PHONY: all clean shim catalog check check-makefiles check-defproof check-vacuity check-index check-import check-decltag check-carrier check-sumtype check-apex advise",
        "all:",
        "\t@$(MAKE) -f Flat.mk all",
        "clean:",
        "\t@$(MAKE) -f Flat.mk clean",
        "# ⟡gqs-catalog-engine: (re)build the .agdai shim (iff agdai_shim.hs changed) + catalog.db from the",
        "# interned SPPF. `catalog` = the BATCHED controller/actuator build (sppf_db \"\"): ONE process models the",
        "# topology once, then rides the decode-parallelism roofline INTERNALLY — per window it co-reads the LIVE",
        "# contention and decodes via a ThreadPool of shim subprocesses sized to the free CPU (interner+DB insert",
        "# serial → NO python-spawn tax), self-skipping unchanged cores. Cheaper than per-core `make -f Flat.mk",
        "# ingest' for the common incremental case (no spawn tax) and it self-parallelizes the full rebuild.",
        "shim:",
        "\t@$(MAKE) -C ../jea/metalanguage shim",
        "catalog: shim",
        "\t@python3 ../scripts/sppf_db.py \"\" --argperm",
        "# Aggregate invariant GATE (same checks the pre-commit hook runs):",
        "# def/proof separation + makefile-tree sync + UP non-vacuity + shape index. Blocking.",
        "check: check-defproof check-makefiles check-vacuity check-index check-import check-decltag check-carrier check-sumtype check-apex",
        "\t@echo 'all invariant checks passed.'",
        "# Verify Flat.mk + the root Makefile are in sync with the source tree.",
        "check-makefiles:",
        "\t@python3 ../scripts/gen_build_makefiles.py --check",
        "# Verify def/proof separation (definition-providers import no proof modules).",
        "check-defproof:",
        "\t@../scripts/check_def_proof_separation.sh",
        "# Verify no vacuous (⊤-collapse) universal properties outside the sanctioned two.",
        "check-vacuity:",
        "\t@../scripts/check_up_nonvacuity.sh",
        "# Verify the shape-node collision index is current (names→shapes, visible).",
        "check-index:",
        "\t@python3 ../scripts/sppf_node_index.py --check",
        "# Ratchet: no NEW bare imports of genuinely-ambiguous names (specialize by shape).",
        "check-import:",
        "\t@python3 ../scripts/check_import_shape.py --quiet",
        "# Every genuinely-ambiguous declaration carries a visible shape tag.",
        "check-decltag:",
        "\t@python3 ../scripts/decl_shape_tag.py",
        "# Canonical operators live in their carrier's home, one-per-file (no forks/buckets).",
        "check-carrier:",
        "\t@python3 ../scripts/check_carrier_locality.py --quiet",
        "# Ratchet: duplicate type-declarations are DEBT (paydown-only); no NEW forked copy.",
        "check-sumtype:",
        "\t@python3 ../scripts/check_sumtype_ratchet.py --quiet",
        "# Apex gate: every relational law-motif (≥3 instances) must have a parametric",
        "# apex (a parameterizable module, NOT an index). No baseline — build the apex.",
        "check-apex:",
        "\t@python3 ../scripts/law_motif_apex.py --check",
        "# ADVISORY (non-blocking): judgment reports, deliberately NOT in `check` /",
        "# the hook (each has real false positives, so they inform, never gate):",
        "#   * theorem-per-file pressure (signature counts)",
        "#   * categorical grounding (domain algebraic modules w/ no Category dep)",
        "advise:",
        "\t@../scripts/check_file_sizes.sh",
        "\t@../scripts/check_categorical_grounding.sh",
        "",
    ])


def main():
    check = "--check" in sys.argv
    disk, deps = parse_tree()
    targets = {
        os.path.join(AGDA_DIR, "Flat.mk"): flat_text(disk, deps),
        os.path.join(AGDA_DIR, "Makefile"): root_text(),
    }

    if check:
        problems = []
        for path, body in targets.items():
            if not os.path.exists(path):
                problems.append("missing: " + os.path.relpath(path, ROOT))
            elif open(path, encoding="utf8").read() != body:
                problems.append("stale:   " + os.path.relpath(path, ROOT))
        if problems:
            print("gen_build_makefiles --check: FAILED")
            for p in problems:
                print("  " + p)
            print("Run scripts/gen_build_makefiles.py to regenerate.")
            sys.exit(1)
        print(f"gen_build_makefiles --check: OK ({len(targets)} makefiles current, "
              f"{len(disk)} modules)")
        sys.exit(0)

    written = 0
    for path, body in targets.items():
        old = open(path, encoding="utf8").read() if os.path.exists(path) else None
        if old != body:
            open(path, "w", encoding="utf8").write(body)
            written += 1
    print(f"gen_build_makefiles: wrote/updated {written} of {len(targets)} makefiles "
          f"({len(disk)} modules, import-DAG source-parsed).")


if __name__ == "__main__":
    main()
