#!/usr/bin/env python3
"""sppf_node_index.py — lift shape-specialization to a VISIBLE artifact.

Agda resolves colliding names by scope/type; a reader can't see the shape. This
emits a name → shape-node index: for every name declared in >1 module, each
member with a one-line SHAPE descriptor (kind + constructors/fields), flagging
  GENUINE AMBIGUITY  — members have DIFFERENT shapes (the name points at
                       distinct nodes; specify the shape to disambiguate);
  VARIANT            — members share a shape (level/field variants of one node).
Writes Markdown to stdout (intended: scratch/sppf_collision_index.md), the
visible map the entity manipulating the code consults.
"""
import os, re, collections, hashlib
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "agda", "Substrate"))
def strip(s):
    s=re.sub(r"\{-.*?-\}"," ",s,flags=re.S); return re.sub(r"--[^\n]*"," ",s)

decls=collections.defaultdict(list)   # name -> [(module, kind, descriptor, shapehash)]
modre=re.compile(r"^module\s+(\S+)\s+where",re.M)
declre=re.compile(r"^(data|record)\s+(\S+)(.*)$")
for dp,_,fns in os.walk(ROOT):
    for fn in fns:
        if not fn.endswith(".agda"): continue
        p=os.path.join(dp,fn); t=strip(open(p,encoding="utf-8").read())
        mm=modre.search(t); mod=mm.group(1) if mm else os.path.relpath(p,ROOT)
        lines=t.splitlines(); i=0
        while i<len(lines):
            m=declre.match(lines[i])
            if m:
                kind,name,rest=m.group(1),m.group(2),m.group(3)
                # collect constructor/field heads for the descriptor + shape hash
                heads=[]; body=[rest]; j=i+1
                while j<len(lines) and (lines[j].strip()=="" or lines[j][:1] in " \t"):
                    s=lines[j].strip()
                    if " : " in s: heads.append(s.split(" : ",1)[0].strip()); body.append(s.split(" : ",1)[1])
                    j+=1
                desc=f"{kind} {{{', '.join(heads[:5])}{'…' if len(heads)>5 else ''}}}" if heads else kind
                sh=hashlib.sha1((kind+"|"+"|".join(sorted(body))).encode()).hexdigest()[:8]
                decls[name].append((mod,kind,desc,sh))
                i=j; continue
            i+=1

coll={n:v for n,v in decls.items() if len({m for m,_,_,_ in v})>1}
genuine=[(n,v) for n,v in coll.items() if len({sh for *_,sh in v})>1]
variant=[(n,v) for n,v in coll.items() if len({sh for *_,sh in v})==1]
genuine.sort(key=lambda kv:-len(kv[1])); variant.sort(key=lambda kv:-len(kv[1]))

import sys
L=[]
L.append("# Name → shape-node index (collision disambiguation)\n")
L.append("Names are vacuous; the shape is the meaning. A name in >1 module points at")
L.append("a node *per shape*. To use a colliding name, specialize by the shape below.")
L.append("GENERATED by `scripts/sppf_node_index.py` — do not edit by hand.\n")
L.append(f"## GENUINE AMBIGUITY — {len(genuine)} names point at DISTINCT shape-nodes\n")
for n,v in genuine:
    L.append(f"### `{n}` — {len(v)} distinct nodes")
    for mod,kind,desc,sh in sorted(v):
        L.append(f"- `⟦{sh}⟧` {desc}  ·  {mod}")
    L.append("")
L.append(f"## VARIANTS — {len(variant)} names, same shape across modules (one node, "
         f"level/field variants)\n")
for n,v in variant:
    L.append(f"- `{n}`  ⟦{v[0][3]}⟧  ·  " + ", ".join(sorted(m for m,_,_,_ in v)))
out="\n".join(L)+"\n"

DOC=os.path.join(os.path.dirname(__file__),"..","scratch","sppf_collision_index.md")
DOC=os.path.abspath(DOC)
if "--check" in sys.argv:
    cur=open(DOC,encoding="utf-8").read() if os.path.exists(DOC) else ""
    if cur!=out:
        print("sppf-node-index: STALE — regenerate with scripts/sppf_node_index.py",file=sys.stderr)
        sys.exit(1)
    print("sppf-node-index: current. ✓")
else:
    open(DOC,"w",encoding="utf-8").write(out)
    print(f"wrote {os.path.relpath(DOC, os.path.join(os.path.dirname(__file__),'..'))}")
