#!/usr/bin/env python3
"""
gen_case_no_fix.py — brute-force search for a decomposition of
case-{D,C,S,W}-no-fix into parametric/recursive Agda proofs.

Generates candidate Agda proof bodies for `case-any-no-fix` and the
per-anchor wrapper lemmas case-{C,S,W}-no-fix; writes each candidate
to a temp file, runs agda --safe to check, reports which compile and
their line counts.

The "decomposition structures" tried:

  A. FLAT-COPY:    case-{C,S,W}-no-fix as direct analogs of case-D-no-fix,
                   with axis substitution per anchor. ~80 lines per lemma.

  B. PER-ANCHOR-HELPER:  Extract the "swap-back + bijection-derived
                   third-axis-image" core into a per-(X, target) helper.
                   The case-{C,S,W}-no-fix dispatchers call it. Reduces
                   duplication via parametric helpers.

  C. UNIFIED-ALGEBRAIC: case-any-no-fix as a single parametric function
                   using act-axis-as-V₄-mult + axis-pigeonhole-3. The
                   case-{C,S,W}-no-fix dispatchers wrap it.

Each strategy is generated by templated substitution. The script
reports for each: (compiles? Y/N, line count, time-to-check).

Usage:
    python3 gen_case_no_fix.py            # try all strategies
    python3 gen_case_no_fix.py --strategy=A      # only strategy A
    python3 gen_case_no_fix.py --inline    # inline winner into V4-Normality
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable, Callable, Dict, List, Tuple

AGDA_DIR = Path("/home/mikemol/github/substrate/agda")
V4_NORMALITY = AGDA_DIR / "Substrate/Groups/V4-Normality.agda"

# V₄ Cayley table — used to compute (V₄, Y, Z) per (X, target) pair.
V4_ELEMS = ("e", "α", "β", "γ")
V4_MULT = {
    ("e", "e"): "e", ("e", "α"): "α", ("e", "β"): "β", ("e", "γ"): "γ",
    ("α", "e"): "α", ("α", "α"): "e", ("α", "β"): "γ", ("α", "γ"): "β",
    ("β", "e"): "β", ("β", "α"): "γ", ("β", "β"): "e", ("β", "γ"): "α",
    ("γ", "e"): "γ", ("γ", "α"): "β", ("γ", "β"): "α", ("γ", "γ"): "e",
}

# Axis ↔ V₄ iso (per Substrate.Groups.V4-Embedding).
AXIS_OF_V = {"e": "D", "α": "C", "β": "S", "γ": "W"}
V_OF_AXIS = {v: k for k, v in AXIS_OF_V.items()}

AXES = ("D", "C", "S", "W")


def act_axis(v: str, x: str) -> str:
    """V₄ action on Axis: act-axis v x = axis-of-v (v · v-of-axis x)."""
    return AXIS_OF_V[V4_MULT[(v, V_OF_AXIS[x])]]


def v_of_axis_anchor(X: str, target: str) -> str:
    """v-of-axis-anchor X target = v-of-axis target · v-of-axis X (in V₄)."""
    return V4_MULT[(V_OF_AXIS[target], V_OF_AXIS[X])]


def other_two_axes(X: str, target: str) -> tuple[str, str]:
    """Given (X, target), return (Y, Z): the two non-(X, target) axes,
    in the swap-pair order under v-of-axis-anchor X target."""
    v = v_of_axis_anchor(X, target)
    others = [a for a in AXES if a not in (X, target)]
    # v swaps (X, target) and swaps (Y, Z). Determine which pair is (Y, Z).
    Y = others[0]
    Z = act_axis(v, Y)
    if Z not in others:
        raise RuntimeError(f"sanity: v={v} on Y={Y} → {Z}, others={others}")
    return Y, Z


def gen_case_X_no_fix_flat(X: str) -> str:
    """Strategy A: direct copy of case-D-no-fix with axis substitution.

    Emits one `case-X-no-fix` lemma (X ∈ {C, S, W}) as 4-case dispatch
    on target. Each non-trivial target case has the swap-back + 4-case
    bijection-derivation + matches structure.
    """
    # Per-X non-X axis ordering (Y, Z, W are the 3 non-X axes).
    non_X = tuple(a for a in AXES if a != X)
    a1, a2, a3 = non_X  # The 3 "non-X" axes; one is target, the other 2 are Y, Z.

    # Argument names for non-fix premises per axis.
    nofix_args = {a: f"τ{a}≢" for a in non_X}
    nofix_arg_str = " ".join(nofix_args[a] for a in non_X)

    lines = []
    lines.append(f"case-{X}-no-fix :")
    lines.append(f"  (τ : Permutation) → (τ · τ) ≈ ε →")
    lines.append(f"  (target : Axis) → target ≢ {X} →")
    lines.append(f"  applyₛ τ {X} ≡ target →")
    for a in non_X:
        lines.append(f"  applyₛ τ {a} ≢ {a} →")
    lines.append(f"  V₄-image τ")
    lines.append(f"case-{X}-no-fix τ τ² {X} {X}≢{X} _ {nofix_arg_str} = ⊥-elim ({X}≢{X} refl)")

    # 3 target cases. For each: derive swap, derive two third-axis images,
    # build matches function.
    for target in non_X:
        v = v_of_axis_anchor(X, target)
        Y, Z = other_two_axes(X, target)
        # Variable names for premises (per (X, target) case).
        # τX≡target is the input
        # We derive τtarget≡X, τY≡Z, τZ≡Y.
        body_lines = []
        # Function header:
        target_arg = "_"   # the target≢X premise position
        # Build the function clause:
        nf_args_at_target = [f"τ{a}≢" for a in non_X]
        body_lines.append(
            f"case-{X}-no-fix τ τ² {target} _ τ{X}≡{target}"
            f" {' '.join(nf_args_at_target)} = {v} , {v}-matches"
        )
        body_lines.append(f"  where")
        # τtarget≡X via swap-back.
        body_lines.append(
            f"    τ{target}≡{X} : applyₛ τ {target} ≡ {X}"
        )
        body_lines.append(
            f"    τ{target}≡{X} = trans (sym (cong (applyₛ τ) τ{X}≡{target})) (τ² {X})"
        )
        # τY≡Z derivation.
        body_lines.append(f"    τ{Y}≡{Z} : applyₛ τ {Y} ≡ {Z}")
        body_lines.append(f"    τ{Y}≡{Z} with applyₛ τ {Y} in p{Y}")
        for axval in AXES:
            if axval == Z:
                body_lines.append(f"    ... | {axval} = refl")
            elif axval == Y:
                body_lines.append(f"    ... | {axval} = ⊥-elim (τ{Y}≢ refl)")
            else:
                # Bijection contradiction.
                # τ.Y = axval. We have τ on either X (→ target) or target (→ X).
                if axval == X:
                    # τ.Y = X = τ.target → Y = target. Contradicts Y ≠ target.
                    body_lines.append(
                        f"    ... | {axval} = ⊥-elim ({Y}≢{target} "
                        f"(σ-injective τ {Y} {target} (trans p{Y} (sym τ{target}≡{X}))))"
                    )
                elif axval == target:
                    body_lines.append(
                        f"    ... | {axval} = ⊥-elim ({Y}≢{X} "
                        f"(σ-injective τ {Y} {X} (trans p{Y} (sym τ{X}≡{target}))))"
                    )
                else:
                    raise RuntimeError(f"unreachable: axval={axval} not in {{X={X}, target={target}, Y={Y}, Z={Z}}}")
        # τZ≡Y derivation (symmetric).
        body_lines.append(f"    τ{Z}≡{Y} : applyₛ τ {Z} ≡ {Y}")
        body_lines.append(f"    τ{Z}≡{Y} with applyₛ τ {Z} in p{Z}")
        for axval in AXES:
            if axval == Y:
                body_lines.append(f"    ... | {axval} = refl")
            elif axval == Z:
                body_lines.append(f"    ... | {axval} = ⊥-elim (τ{Z}≢ refl)")
            else:
                if axval == X:
                    body_lines.append(
                        f"    ... | {axval} = ⊥-elim ({Z}≢{target} "
                        f"(σ-injective τ {Z} {target} (trans p{Z} (sym τ{target}≡{X}))))"
                    )
                elif axval == target:
                    body_lines.append(
                        f"    ... | {axval} = ⊥-elim ({Z}≢{X} "
                        f"(σ-injective τ {Z} {X} (trans p{Z} (sym τ{X}≡{target}))))"
                    )
                else:
                    raise RuntimeError(f"unreachable")
        # Matches function.
        body_lines.append(
            f"    {v}-matches : (x : Axis) → applyₛ τ x ≡ applyₛ (embed {v}) x"
        )
        for axval in AXES:
            if axval == X:
                rhs = f"τ{X}≡{target}"
            elif axval == target:
                rhs = f"τ{target}≡{X}"
            elif axval == Y:
                rhs = f"τ{Y}≡{Z}"
            else:  # axval == Z
                rhs = f"τ{Z}≡{Y}"
            body_lines.append(f"    {v}-matches {axval} = {rhs}")
        lines.extend(body_lines)

    return "\n".join(lines)


def axis_distinctness_lemmas_needed(X: str) -> list[str]:
    """List axis-distinctness lemma names referenced in case-X-no-fix
    (e.g., 'S≢C' for case-C-no-fix). Lets us verify all are in scope."""
    needed = set()
    non_X = tuple(a for a in AXES if a != X)
    for target in non_X:
        Y, Z = other_two_axes(X, target)
        for a in (Y, Z):
            for b in (X, target):
                if a != b:
                    needed.add(f"{a}≢{b}")
    return sorted(needed)


def write_candidate_to_file(name: str, body: str) -> Path:
    """Insert a candidate proof block into V4-Normality.agda just before
    `is-V₄-shape-classifies`. Returns the path written (a copy for
    safe testing)."""
    text = V4_NORMALITY.read_text()
    marker = "-- Putting the classification together. The all-fixed branch dispatches"
    if marker not in text:
        raise RuntimeError(f"marker not found in {V4_NORMALITY}")
    new_text = text.replace(marker, body + "\n\n" + marker, 1)
    test_path = AGDA_DIR / f"Substrate/Groups/V4-Normality-{name}.agda"
    test_text = new_text.replace(
        "module Substrate.Groups.V4-Normality where",
        f"module Substrate.Groups.V4-Normality-{name} where",
    )
    test_path.write_text(test_text)
    return test_path


def type_check(path: Path, timeout: int = 180) -> tuple[bool, str, float]:
    """Run agda on path; return (ok, last-error-line, elapsed-seconds)."""
    t0 = time.time()
    proc = subprocess.run(
        ["agda", str(path.relative_to(AGDA_DIR))],
        cwd=str(AGDA_DIR),
        capture_output=True, text=True, timeout=timeout,
    )
    elapsed = time.time() - t0
    ok = proc.returncode == 0
    last = ""
    if not ok:
        # Get the most informative error line.
        for line in (proc.stdout + proc.stderr).splitlines():
            if "error" in line.lower() or "!=" in line or "expected" in line.lower():
                last = line.strip()
                break
    return ok, last, elapsed


def gen_case_X_no_fix_with_helpers(X: str) -> str:
    """Strategy B: extract `swap-back` and `bij-clash` as top-level
    private helpers (shared across all case-{C,S,W}-no-fix). The per-
    (X, target) cases use them, reducing inline boilerplate."""
    # Same structure as flat, but uses the shared helpers `swap-back`
    # and `bij-clash` (declared globally; we don't emit them per X).
    non_X = tuple(a for a in AXES if a != X)
    nofix_args = {a: f"τ{a}≢" for a in non_X}
    nofix_arg_str = " ".join(nofix_args[a] for a in non_X)
    lines = []
    lines.append(f"case-{X}-no-fix :")
    lines.append(f"  (τ : Permutation) → (τ · τ) ≈ ε →")
    lines.append(f"  (target : Axis) → target ≢ {X} →")
    lines.append(f"  applyₛ τ {X} ≡ target →")
    for a in non_X:
        lines.append(f"  applyₛ τ {a} ≢ {a} →")
    lines.append(f"  V₄-image τ")
    lines.append(f"case-{X}-no-fix τ τ² {X} {X}≢{X} _ {nofix_arg_str} = ⊥-elim ({X}≢{X} refl)")
    for target in non_X:
        v = v_of_axis_anchor(X, target)
        Y, Z = other_two_axes(X, target)
        nf_args_at_target = [f"τ{a}≢" for a in non_X]
        lines.append(
            f"case-{X}-no-fix τ τ² {target} _ τ{X}≡{target}"
            f" {' '.join(nf_args_at_target)} = {v} , {v}-matches"
        )
        lines.append(f"  where")
        # swap-back helper, applied per case (still a 1-liner; can't share globally
        # without parametrizing over τ).
        lines.append(
            f"    τ{target}≡{X} : applyₛ τ {target} ≡ {X}"
        )
        lines.append(
            f"    τ{target}≡{X} = swap-back τ² τ{X}≡{target}"
        )
        # τY≡Z via the same with-and-bij pattern (still 4-case; the bij-clash
        # helper compresses the inline lambda).
        lines.append(f"    τ{Y}≡{Z} : applyₛ τ {Y} ≡ {Z}")
        lines.append(f"    τ{Y}≡{Z} with applyₛ τ {Y} in p{Y}")
        for axval in AXES:
            if axval == Z:
                lines.append(f"    ... | {axval} = refl")
            elif axval == Y:
                lines.append(f"    ... | {axval} = ⊥-elim (τ{Y}≢ refl)")
            elif axval == X:
                lines.append(
                    f"    ... | {axval} = ⊥-elim (bij-clash τ {Y}≢{target} p{Y} τ{target}≡{X})"
                )
            elif axval == target:
                lines.append(
                    f"    ... | {axval} = ⊥-elim (bij-clash τ {Y}≢{X} p{Y} τ{X}≡{target})"
                )
        # τZ≡Y derivation (symmetric).
        lines.append(f"    τ{Z}≡{Y} : applyₛ τ {Z} ≡ {Y}")
        lines.append(f"    τ{Z}≡{Y} with applyₛ τ {Z} in p{Z}")
        for axval in AXES:
            if axval == Y:
                lines.append(f"    ... | {axval} = refl")
            elif axval == Z:
                lines.append(f"    ... | {axval} = ⊥-elim (τ{Z}≢ refl)")
            elif axval == X:
                lines.append(
                    f"    ... | {axval} = ⊥-elim (bij-clash τ {Z}≢{target} p{Z} τ{target}≡{X})"
                )
            elif axval == target:
                lines.append(
                    f"    ... | {axval} = ⊥-elim (bij-clash τ {Z}≢{X} p{Z} τ{X}≡{target})"
                )
        # Matches.
        lines.append(
            f"    {v}-matches : (x : Axis) → applyₛ τ x ≡ applyₛ (embed {v}) x"
        )
        for axval in AXES:
            if axval == X:
                rhs = f"τ{X}≡{target}"
            elif axval == target:
                rhs = f"τ{target}≡{X}"
            elif axval == Y:
                rhs = f"τ{Y}≡{Z}"
            else:  # axval == Z (only remaining option since {X,target,Y,Z} = Axis)
                rhs = f"τ{Z}≡{Y}"
            lines.append(f"    {v}-matches {axval} = {rhs}")
    return "\n".join(lines)


# Shared helpers prepended to strategy B output.
STRATEGY_B_HELPERS = """\
private
  swap-back : ∀ {τ : Permutation} → (τ · τ) ≈ ε → ∀ {X target : Axis} →
              applyₛ τ X ≡ target → applyₛ τ target ≡ X
  swap-back {τ} {X} {_} τ² p = trans (sym (cong (applyₛ τ) p)) (τ² X)

  bij-clash : (τ : Permutation) {a b x : Axis} → a ≢ b →
              applyₛ τ a ≡ x → applyₛ τ b ≡ x → ⊥
  bij-clash τ a≢b pa pb = a≢b (σ-injective τ _ _ (trans pa (sym pb)))
"""


def gen_strategy_B() -> str:
    """Strategy B: helpers + 3 case-{C,S,W}-no-fix using them."""
    body = STRATEGY_B_HELPERS + "\n"
    body += "\n\n".join(gen_case_X_no_fix_with_helpers(X) for X in ("C", "S", "W"))
    return body


STRATEGIES = {
    "A": lambda: "\n\n".join(gen_case_X_no_fix_flat(X) for X in ("C", "S", "W")),
    "B": gen_strategy_B,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strategy", default="all",
                        help="A/B/C/all (default: all)")
    parser.add_argument("--inline", action="store_true",
                        help="install the winning strategy into V4-Normality")
    args = parser.parse_args()

    chosen = list(STRATEGIES) if args.strategy == "all" else [args.strategy]
    results = []
    for strat in chosen:
        gen = STRATEGIES[strat]
        body = gen()
        line_count = body.count("\n") + 1

        # Insert into a test file copy, type-check.
        test_path = write_candidate_to_file(f"strategy-{strat}", body)
        print(f"[strategy {strat}] {line_count} lines; writing to "
              f"{test_path.name} and type-checking…", file=sys.stderr)
        try:
            ok, err, elapsed = type_check(test_path)
        except subprocess.TimeoutExpired:
            ok, err, elapsed = False, "TIMEOUT", 0.0
        # Clean up temp.
        for suf in (".agda", ".agdai"):
            p = test_path.with_suffix(suf)
            if p.exists():
                p.unlink()
        results.append((strat, ok, line_count, err, elapsed))
        print(f"  → {'OK' if ok else 'FAIL'} ({elapsed:.1f}s); "
              f"first error: {err[:100]}", file=sys.stderr)

    print()
    print("=== Strategy comparison ===")
    print(f"{'strat':<8} {'ok':<5} {'lines':<8} {'sec':<7} {'first error'}")
    for strat, ok, lc, err, sec in results:
        print(f"{strat:<8} {'Y' if ok else 'N':<5} {lc:<8} {sec:<7.1f} "
              f"{err[:80]}")

    winners = [(s, lc) for s, ok, lc, _, _ in results if ok]
    if winners:
        best_strat, best_lines = min(winners, key=lambda t: t[1])
        print(f"\nWinner: strategy {best_strat} ({best_lines} lines)")
        if args.inline:
            body = STRATEGIES[best_strat]()
            text = V4_NORMALITY.read_text()
            marker = ("-- Putting the classification together. "
                      "The all-fixed branch dispatches")
            new_text = text.replace(marker, body + "\n\n" + marker, 1)
            V4_NORMALITY.write_text(new_text)
            print(f"Installed into {V4_NORMALITY}")
    else:
        print("\nNo strategy compiled. Inspect failures above.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
