------------------------------------------------------------------------
-- Substrate.WitnessTower.Wedge.OrientationRigCatPermAdjClosure
--
-- THE CONCRETE GRADE-3 GAP-CLOSURE WITNESS — the POSITIVE dual of
-- OrientationRigCatPermGap. Where that module proved the NEGATIVE half of
-- the primality gap (the ROTATION braidings of orientationRigCatPerm reach
-- only C₃ = ⟨g1,g2⟩ ⊊ S₃ at prime grade 3), THIS module proves the
-- POSITIVE closure once the ⊕-BIFUNCTOR is available:
--
--   the two grade-3 ADJACENT transpositions
--       a0 = (0 1) = [1,0,2]   ( = id ⊕ s₁ ⊕ id at position 0 )
--       a1 = (1 2) = [0,2,1]   ( = id ⊕ s₁ ⊕ id at position 1 )
--   GENERATE ALL of S₃ under ∘ — i.e. ⟨a0,a1⟩ = S₃ (all 6 elements).
--
-- The adjacent transpositions aᵢ are REACHABLE ONLY VIA THE ⊕-BIFUNCTOR:
-- aᵢ = blockSum (blockSum (id-perm i) s₁) (id-perm j) (Part 2 of
-- OrientationRigCatPermBifunctor) — they are NOT among the block/factor
-- braidings that orientationRigCatPerm exposes without a monoidal product on
-- morphisms. So the ⊕-bifunctor is EXACTLY what closes the primality gap at
-- grade 3: C₃ (braidings, OrientationRigCatPermGap) ⊊ S₃ (adjacent
-- transpositions, HERE).
--
-- THE SIX ELEMENTS OF S₃ (numpy-verified image-vectors, and their explicit
-- compose-words in a0,a1 — each product reduces definitionally to a `refl`):
--   e    = [0,1,2] = id
--   a0   = [1,0,2]                                    (generator)
--   a1   = [0,2,1]                                    (generator)
--   c120 = [1,2,0] = compose a0 a1                    (3-cycle)
--   c201 = [2,0,1] = compose a1 a0                    (3-cycle)
--   c210 = [2,1,0] = compose a0 (compose a1 a0)       (transposition (0 2))
--
-- THE ROUTE — FINITE CONSTRUCTION (mirrors OrientationRigCatPermGap, inverted
-- to positive):
--   * data AdjGen = the subgroup inductively generated by { id, a0, a1 } under
--     compose (S₃ finite ⇒ compose-closure already supplies inverses — no
--     separate inv constructor).
--   * six explicit witnesses adj-e … adj-c210 : AdjGen p, each a compose-word
--     in a0,a1 whose reduct is the concrete image-vector p (so the type
--     AdjGen (compose …) IS AdjGen p by computation).
--   * AllS₃ p = the 6-element ⊎-predicate (honest ⊎-data, NO Σ/∃).
--   * adjT-generate-S₃ : AllS₃ p → AdjGen p — the 6-witness bundle: every
--     element of S₃ is in ⟨a0,a1⟩. Contrast Gen⊆S in the Gap file (⟨braidings⟩
--     ⊆ C₃, the 3-element set): here the generated set is ALL of S₃.
--
-- HONEST SCOPE. This settles the CONCRETE grade-3 closure ⟨a0,a1⟩ = S₃ (the
-- positive dual of the grade-3 gap). The GENERAL positive UP
-- (orientationRigCatPerm-with-⊕-bifunctor is free/initial ∀ grade) additionally
-- needs Coxeter completeness — "every Perm n is a word in adjacent
-- transpositions" — which is NOW PROVEN ∀n (commit 9dcdbb7):
-- OrientationRigCatPermCoxeterGeneral.Properties.coxeter-complete. This module
-- retains the standalone concrete n=3 instance; the general theorem subsumes it.
-- (The earlier "NOT yet in the tree" was stale — committed just before the close.)
--
-- This module DECLARES `data AdjGen` → it is a DEFINITION-PROVIDER (def-side):
-- it imports ONLY Perm (Enumerate) and compose/id-perm (FirstAppearance) plus
-- foundation ⊎/≡ — NO proof-carrying .Properties/.Laws/.Proofs module. The
-- closure witnesses are `refl` (compose reduces on the concrete vectors), so no
-- lemma import is needed. `AdjGen` is a tree-unique data name (cf. the Gap
-- file's `BraidGen`, chosen to avoid the `Gen` collision).
--
-- zero postulates, zero holes, --safe --without-K, GREEN.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Wedge.OrientationRigCatPermAdjClosure where

open import Substrate.Foundation.Fin using (Fin; zero; suc)
open import Substrate.Foundation.Vec using (Vec; []; _∷_)
open import Substrate.Foundation.Eq using (_≡_; refl)
open import Substrate.Foundation.Sum using (_⊎_; inj₁; inj₂)

open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.FirstAppearance using (id-perm; compose)

------------------------------------------------------------------------
-- 1. The six concrete grade-3 group elements. Perm 3 = Vec (Fin 3) 3
--    (position i ↦ image); Fin 3 literals zero, suc zero, suc (suc zero).
------------------------------------------------------------------------

e a0 a1 c120 c201 c210 : Perm 3
e    = zero           ∷ suc zero        ∷ suc (suc zero) ∷ []   -- [0,1,2] = id
a0   = suc zero       ∷ zero            ∷ suc (suc zero) ∷ []   -- [1,0,2] = (0 1)
a1   = zero           ∷ suc (suc zero)  ∷ suc zero       ∷ []   -- [0,2,1] = (1 2)
c120 = suc zero       ∷ suc (suc zero)  ∷ zero           ∷ []   -- [1,2,0]
c201 = suc (suc zero) ∷ zero            ∷ suc zero       ∷ []   -- [2,0,1]
c210 = suc (suc zero) ∷ suc zero        ∷ zero           ∷ []   -- [2,1,0] = (0 2)

-- Sanity: e is the identity permutation of Fin 3 (definitional).
e-is-id : e ≡ id-perm 3
e-is-id = refl

------------------------------------------------------------------------
-- 2. The adjacent-transposition-generated subgroup, inductively: id + a0 +
--    a1, closed under compose. (S₃ finite ⇒ compose-closure already gives
--    inverses; no separate inv constructor is needed.)
------------------------------------------------------------------------

data AdjGen : Perm 3 → Set where
  gen-id : AdjGen e
  gen-a0 : AdjGen a0
  gen-a1 : AdjGen a1
  gen-∘  : {σ τ : Perm 3} → AdjGen σ → AdjGen τ → AdjGen (compose σ τ)

------------------------------------------------------------------------
-- 3. The six witnesses. Each non-generator is an explicit compose-word in
--    a0,a1; the type `AdjGen (compose …)` IS `AdjGen p` because compose
--    reduces definitionally on the concrete image-vectors (numpy-verified:
--    a0∘a1 = [1,2,0], a1∘a0 = [2,0,1], a0∘(a1∘a0) = [2,1,0]).
------------------------------------------------------------------------

adj-e    : AdjGen e
adj-e    = gen-id

adj-a0   : AdjGen a0
adj-a0   = gen-a0

adj-a1   : AdjGen a1
adj-a1   = gen-a1

adj-c120 : AdjGen c120                          -- [1,2,0] = a0 ∘ a1
adj-c120 = gen-∘ gen-a0 gen-a1

adj-c201 : AdjGen c201                          -- [2,0,1] = a1 ∘ a0
adj-c201 = gen-∘ gen-a1 gen-a0

adj-c210 : AdjGen c210                          -- [2,1,0] = a0 ∘ (a1 ∘ a0)
adj-c210 = gen-∘ gen-a0 (gen-∘ gen-a1 gen-a0)

------------------------------------------------------------------------
-- 4. Membership in the 6-element set S₃ — honest ⊎-data, NO Σ/∃.
------------------------------------------------------------------------

AllS₃ : Perm 3 → Set
AllS₃ σ = (σ ≡ e)
        ⊎ ((σ ≡ a0)
        ⊎ ((σ ≡ a1)
        ⊎ ((σ ≡ c120)
        ⊎ ((σ ≡ c201)
        ⊎  (σ ≡ c210)))))

------------------------------------------------------------------------
-- 5. THE WITNESS BUNDLE. Every element of S₃ is in ⟨a0,a1⟩ — the adjacent
--    transpositions GENERATE the full symmetric group at grade 3, so the
--    primality gap CLOSES once the ⊕-bifunctor makes a0,a1 reachable.
--    (Contrast OrientationRigCatPermGap's Gen⊆S: the ROTATION braidings
--    generate only the 3-element C₃.)
------------------------------------------------------------------------

adjT-generate-S₃ : {σ : Perm 3} → AllS₃ σ → AdjGen σ
adjT-generate-S₃ (inj₁ refl)                             = adj-e
adjT-generate-S₃ (inj₂ (inj₁ refl))                      = adj-a0
adjT-generate-S₃ (inj₂ (inj₂ (inj₁ refl)))               = adj-a1
adjT-generate-S₃ (inj₂ (inj₂ (inj₂ (inj₁ refl))))        = adj-c120
adjT-generate-S₃ (inj₂ (inj₂ (inj₂ (inj₂ (inj₁ refl))))) = adj-c201
adjT-generate-S₃ (inj₂ (inj₂ (inj₂ (inj₂ (inj₂ refl))))) = adj-c210
