------------------------------------------------------------------------
-- Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral
--
-- ⟡coxeter-completeness-general (DEF SIDE) — the datatype + the adjacent
-- transposition it is generated by. This is the definition-provider for the
-- GENERAL ∀-n Coxeter-completeness theorem
--
--     every  σ : Perm n  with  IsPerm σ  is a word in adjacent transpositions
--
-- proven in the companion .Properties. It closes the last gap of
-- ⟡rig-UP-cat-perm-UP (⇒ full positive freeness of orientationRigCatPerm with
-- the ⊕-bifunctor): OrientationRigCatPermBifunctor settled the CONCRETE grade-3
-- closure ⟨a0,a1⟩ = S₃; this file's companion lifts it to ALL grades.
--
-- WHAT LIVES HERE (def side, self-contained — imports ONLY Perm, id-perm,
-- compose, blockSum + Foundation; NO proof-carrying .Properties module):
--
--   * sadj n j — the adjacent transposition swapping positions (inj1 j) and
--     (suc j) of Fin (suc n), for a position j : Fin n. Defined by the SAME
--     ⊕-recursion as adjT (OrientationRigCatPermBifunctor): sadj at the bottom
--     is  s₁ ⊕ id ; sadj one position up is  id ⊕ (sadj below). The one-up
--     recursion is EXACTLY  blockSum (id-perm 1) _ , so the embedding law
--       blockSum (id-perm 1) (sadj n j) ≡ sadj (suc n) (suc j)   (L4)
--     holds DEFINITIONALLY (it is the second clause read backwards) — no proof.
--
--   * data CoxGen — the subgroup inductively generated by { id, every adjacent
--     transposition sadj n j } under compose. GRADE-POLYMORPHIC (indexed over
--     all n at once) so a single derivation tree can talk about a perm and its
--     grade-raised image. `CoxGen σ` IS the constructive witness that σ is an
--     adjacent-transposition word — a derivation, NOT a Σ-packaged existence.
--
--   * inj1 — the value-preserving Fin n ↪ Fin (suc n) (the bubble recursion
--     descends the insertion position through it; its numeric value is fixed,
--     `toℕ (inj1 j) ≡ toℕ j`, proven in .Properties).
--
-- The tree-unique data name is `CoxGen` (AdjGen is taken by the grade-3
-- OrientationRigCatPermAdjClosure, AdjGen4 by OrientationRigCatPermCoxeter4).
--
-- zero postulates, zero holes, --safe --without-K, GREEN.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral where

open import Substrate.Foundation.Nat using (ℕ; zero; suc; _+_)
open import Substrate.Foundation.Fin using (Fin; zero; suc)
open import Substrate.Foundation.Vec using (Vec; []; _∷_)

open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.FirstAppearance using (id-perm; compose)
open import Substrate.WitnessTower.Wedge.OrientationDistributor using (blockSum)

------------------------------------------------------------------------
-- 1. s₁ : Perm 2 = [1,0] — the grade-2 transposition (stated locally as the
--    concrete image-vector to keep this file off the proof side; it is the
--    same s₁ as OrientationRigCatPermBifunctor, but re-declaring the two-entry
--    vector costs nothing and avoids importing a lemma module).
------------------------------------------------------------------------

s₁ : Perm 2
s₁ = suc zero ∷ zero ∷ []

------------------------------------------------------------------------
-- 2. sadj n j : the adjacent transposition at position j : Fin n of grade
--    (suc n). ⊕-recursion:  bottom = s₁ ⊕ id ,  one-up = id ⊕ (sadj below).
------------------------------------------------------------------------

sadj : (n : ℕ) → Fin n → Perm (suc n)
sadj (suc n) zero    = blockSum s₁ (id-perm n)
sadj (suc n) (suc j) = blockSum (id-perm 1) (sadj n j)

------------------------------------------------------------------------
-- 3. inj1 : the value-preserving inclusion Fin n ↪ Fin (suc n).
------------------------------------------------------------------------

inj1 : {n : ℕ} → Fin n → Fin (suc n)
inj1 zero    = zero
inj1 (suc i) = suc (inj1 i)

------------------------------------------------------------------------
-- 4. data CoxGen — the adjacent-transposition-generated subgroup, grade-
--    polymorphic. id + every sadj, closed under compose (finite ⇒ compose-
--    closure supplies inverses; no separate inv constructor).
------------------------------------------------------------------------

data CoxGen : {n : ℕ} → Perm n → Set where
  cox-id : {n : ℕ}                             → CoxGen (id-perm n)
  cox-s  : {n : ℕ} (j : Fin n)                 → CoxGen (sadj n j)
  cox-∘  : {n : ℕ} {σ τ : Perm n} → CoxGen σ → CoxGen τ → CoxGen (compose σ τ)
