------------------------------------------------------------------------
-- Substrate.WitnessTower.Wedge.OrientationRigCatPermGap
--
-- THE CONCRETE GRADE-3 NON-MEMBERSHIP WITNESS — closes the Ⓐ follow-on of
-- ⟡rig-UP-cat-perm-UP (OrientationRigCatPermUP). It proves, in Agda, the
-- NEGATIVE half of the primality gap on the nose:
--
--   the transposition (0 1) = [1,0,2] ∈ Perm 3 is NOT any ∘-composite of the
--   grade-3 braidings of orientationRigCatPerm — i.e. it is NOT in the sub-
--   group ⟨g1,g2⟩ they generate, which is exactly C₃ = { id, [1,2,0], [2,0,1] }.
--
-- So orientationRigCatPerm is PROVABLY NOT free/initial via its braidings at
-- prime grade 3: the full S₃-morphism (0 1) is not pinned by the GradedRigCat
-- structure (F-∘ + F-braid⊕/⊗) at that grade. The obstruction is precisely
-- PRIMALITY — at grade 3 the ⊗-braidings are trivial (i·j=3 has no nontrivial
-- factor) and only the two ⊕-rotations survive, generating C₃ ⊊ S₃.
--
-- THE BRAIDING VALUES (numpy-verified; = OrientationRigCatPerm.swPerm/blockSwap
-- readouts at grade 3, hard-coded here per the def/proof-separation scope):
--   g1 = [2,0,1]  (blockSwap 1 2 = braid⊕ at i=1,j=2, the cyclic shift)
--   g2 = [1,2,0]  (blockSwap 2 1 = braid⊕ at i=2,j=1)
--   (braid⊗ at grade 3 is trivial.) As image-vectors Perm 3 = Vec (Fin 3) 3.
--
-- THE ROUTE — FINITE CLOSURE (no general sign-multiplicativity theorem needed):
--   * S σ = "σ is one of the 3 elements of C₃" (honest ⊎-data, NO Σ/∃).
--   * data BraidGen = the subgroup inductively generated by { id, g1, g2 } under
--     compose (C₃ is finite abelian, so closure under compose already supplies
--     inverses — no separate inv constructor).
--   * S-closed : the 9-case finite closure check — every product of two of the
--     3 elements is again one of the 3 (each case a `refl`, compose reducing
--     definitionally on the concrete image-vectors). Hence Gen⊆S.
--   * ¬ S t01 : the transposition is none of the 3 (three constructor-distinct
--     Vec (Fin 3) 3 equalities, each absurd by `()`).
--   * THE WITNESS: transposition-∉-braidings = λ g → ¬S-t01 (Gen⊆S g).
--
-- Cross-check (the general separator, not needed here): cycle-type gives
-- t01 ↦ [1,1,0] (ODD) vs id ↦ [3,0,0], the 3-cycles ↦ [0,0,1] (all EVEN).
--
-- This module DECLARES `data BraidGen` → it is a DEFINITION-PROVIDER (def-side):
-- it imports ONLY Perm (Enumerate) and compose/id-perm (FirstAppearance) plus
-- foundation ⊎/≡/¬ — NO proof-carrying .Properties/.Laws/.Proofs module.
--
-- zero postulates, zero holes, --safe --without-K, GREEN.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Wedge.OrientationRigCatPermGap where

open import Substrate.Foundation.Fin.Fin
open import Substrate.Foundation.Vec using (Vec; []; _∷_)
open import Substrate.Foundation.Eq using (_≡_; refl)
open import Substrate.Foundation.Sum using (_⊎_; inj₁; inj₂)
open import Substrate.Foundation.Negation using (¬_)

open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.FirstAppearance using (id-perm; compose)

------------------------------------------------------------------------
-- 1. The three concrete grade-3 group elements (C₃) and the transposition.
--    Perm 3 = Vec (Fin 3) 3 (position i ↦ image); Fin 3 literals are
--    zero, suc zero, suc (suc zero).
------------------------------------------------------------------------

p-id p-g1 p-g2 t01 : Perm 3
p-id = zero        ∷ suc zero     ∷ suc (suc zero) ∷ []   -- [0,1,2] = id
p-g1 = suc (suc zero) ∷ zero      ∷ suc zero       ∷ []   -- [2,0,1] = blockSwap 1 2
p-g2 = suc zero     ∷ suc (suc zero) ∷ zero        ∷ []   -- [1,2,0] = blockSwap 2 1
t01  = suc zero     ∷ zero         ∷ suc (suc zero) ∷ []   -- [1,0,2] = transposition (0 1)

-- Sanity: p-id is the identity permutation of Fin 3 (definitional).
p-id-is-id : p-id ≡ id-perm 3
p-id-is-id = refl

------------------------------------------------------------------------
-- 2. Membership S σ in the 3-element set { id, g1, g2 } — honest ⊎-data.
------------------------------------------------------------------------

S : Perm 3 → Set
S σ = (σ ≡ p-id) ⊎ ((σ ≡ p-g1) ⊎ (σ ≡ p-g2))

------------------------------------------------------------------------
-- 3. The braiding-generated subgroup, inductively: id + g1 + g2, closed
--    under compose. (C₃ finite abelian ⇒ compose-closure already gives
--    inverses; no separate inv constructor is needed.)
------------------------------------------------------------------------

-- (named BraidGen, not Gen, to keep the tree's `Gen` name single-shape:
--  a distinct-shape `data Gen` here would retroactively make `Gen`
--  import-ambiguous — check_import_shape.py.)
data BraidGen : Perm 3 → Set where
  gen-id : BraidGen p-id
  gen-g1 : BraidGen p-g1
  gen-g2 : BraidGen p-g2
  gen-∘  : {σ τ : Perm 3} → BraidGen σ → BraidGen τ → BraidGen (compose σ τ)

------------------------------------------------------------------------
-- 4. Finite closure: every product of two elements of { id, g1, g2 } is
--    again one of the three. compose σ τ = tabulate (λ i → lookup σ (lookup
--    τ i)) reduces definitionally on the concrete vectors, so each of the
--    9 cases is a `refl`. (Table numpy-verified: g1·g1=g2, g1·g2=id,
--    g2·g2=g1, g2·g1=id, etc.)
------------------------------------------------------------------------

S-closed : {σ τ : Perm 3} → S σ → S τ → S (compose σ τ)
S-closed (inj₁ refl)        (inj₁ refl)        = inj₁ refl              -- id·id = id
S-closed (inj₁ refl)        (inj₂ (inj₁ refl)) = inj₂ (inj₁ refl)       -- id·g1 = g1
S-closed (inj₁ refl)        (inj₂ (inj₂ refl)) = inj₂ (inj₂ refl)       -- id·g2 = g2
S-closed (inj₂ (inj₁ refl)) (inj₁ refl)        = inj₂ (inj₁ refl)       -- g1·id = g1
S-closed (inj₂ (inj₁ refl)) (inj₂ (inj₁ refl)) = inj₂ (inj₂ refl)       -- g1·g1 = g2
S-closed (inj₂ (inj₁ refl)) (inj₂ (inj₂ refl)) = inj₁ refl              -- g1·g2 = id
S-closed (inj₂ (inj₂ refl)) (inj₁ refl)        = inj₂ (inj₂ refl)       -- g2·id = g2
S-closed (inj₂ (inj₂ refl)) (inj₂ (inj₁ refl)) = inj₁ refl              -- g2·g1 = id
S-closed (inj₂ (inj₂ refl)) (inj₂ (inj₂ refl)) = inj₂ (inj₁ refl)       -- g2·g2 = g1

-- The generated subgroup is contained in the 3-element set: by induction,
-- with the gen-∘ case discharged by the finite closure above.
Gen⊆S : {σ : Perm 3} → BraidGen σ → S σ
Gen⊆S gen-id       = inj₁ refl
Gen⊆S gen-g1       = inj₂ (inj₁ refl)
Gen⊆S gen-g2       = inj₂ (inj₂ refl)
Gen⊆S (gen-∘ g h)  = S-closed (Gen⊆S g) (Gen⊆S h)

------------------------------------------------------------------------
-- 5. The transposition is none of the three (constructor-distinct vectors).
------------------------------------------------------------------------

¬S-t01 : ¬ S t01
¬S-t01 (inj₁ ())
¬S-t01 (inj₂ (inj₁ ()))
¬S-t01 (inj₂ (inj₂ ()))

------------------------------------------------------------------------
-- 6. THE WITNESS. The transposition (0 1) is not in the braiding-generated
--    subgroup C₃ — so orientationRigCatPerm is NOT braiding-generated (not
--    free/initial via its braidings) at prime grade 3.
------------------------------------------------------------------------

transposition-∉-braidings : ¬ BraidGen t01
transposition-∉-braidings g = ¬S-t01 (Gen⊆S g)
