------------------------------------------------------------------------
-- Substrate.WitnessTower.Wedge.OrientationRigCatSym
--
-- ⟡perm-UP-assemble (STAGE 1) — THE GENUINE SYMMETRIC (Sₙ-morphism) RIG
-- CATEGORY orientationRigCatSym. The companion orientationRigCatPerm
-- (OrientationRigCatPerm) has morphisms = an UNRESTRICTED Vec (Fin j) j, i.e.
-- the full transformation MONOID Tₙ (every self-map of the grade-j set, n^n of
-- them). Its functors are therefore NOT free: a target-choice on the braidings
-- does not determine the image of a NON-permutation morphism, because those are
-- not generated by anything. THIS category restricts the hom-set to the genuine
-- PERMUTATIONS — the symmetric GROUPOID Sₙ — where (Stage 3) the just-landed
-- `coxeter-complete` witnesses that EVERY morphism is an adjacent-transposition
-- word, so a functor IS determined by its action on generators.
--
--   Tₙ  =  orientationRigCatPerm   (Homᵣ i j = Σ (i≡j) (Perm j), Perm = any Vec)
--   Sₙ  =  orientationRigCatSym    (Homˢ i j = Σ (Homᵣ i j) (Iso ∘ proj₂))
--
-- THE PERMUTATION WITNESS — Iso, NOT raw injectivity. The task's first draft
-- carried IsPerm σ = (i j) → lookup σ i ≡ lookup σ j → i ≡ j (injectivity of
-- lookup). That is a Π-TYPE; making the morphism hom-set a SET (so morphism
-- equality reduces to the Perm component) needs IsPerm to be a mere proposition,
-- which for a Π requires FUNCTION EXTENSIONALITY. This substrate is funext-free
-- (`--without-K`, no funext axiom; empirically, empty-domain funext and the
-- Fin surjective-pairing η both FAIL by refl — verified — so `fin-funext` is not
-- provable, and neither is IsPerm-prop). The funext-free route to the SAME Sₙ is
-- the TWO-SIDED-INVERSE witness
--
--   Iso σ = Σ (Perm n) (λ τ → (compose σ τ ≡ id) × (compose τ σ ≡ id))
--
-- which is a genuine mere proposition WITHOUT funext: the inverse τ is unique by
-- pure monoid algebra (inv-unique: τ' = τ'·id = τ'·(σ·τ) = (τ'·σ)·τ = id·τ = τ),
-- and the round-trip components are UIP because Perm n = Vec (Fin n) n is a SET
-- (Vec ≡-dec ∘ Fin _≟_ ⇒ Hedberg Decidable⇒UIP). And Iso σ ⇔ IsPerm σ on the
-- finite set (Iso→IsPerm: a left inverse ⇒ injective; IsPerm→Iso: injective ⇒
-- surjective [WitnessTower.Surjective] ⇒ a two-sided inverse), so the object it
-- carves out is EXACTLY the symmetric group Sₙ — the genuine groupoid, every
-- morphism invertible.
--
-- REUSE (not reinvention): the category's category-structure IS
-- orientationRigCatPerm's — idᵣ / _∘ᵣ_ / left-idᵣ / right-idᵣ / assocᵣ and the
-- braidings braid⊕ / braid⊗ (with braid⊕/⊗-invol) are reused verbatim on the
-- Homᵣ part; Stage 1 only ADDS the Iso witness (rebuilt uniformly through
-- IsPerm→Iso) and reduces the laws to the Homᵣ laws via Iso-prop (homEqˢ).
--
-- Zero postulates, zero holes, --safe --without-K. NO Σ / ∃ packages an
-- existence/uniqueness claim; every Σ here (Iso, Homˢ) is honest morphism DATA.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Wedge.OrientationRigCatSym where

open import Substrate.Foundation.Nat using (ℕ; _+_; _*_)
open import Substrate.Foundation.Fin using (Fin; _≟_)
open import Substrate.Foundation.Eq
  using (_≡_; refl; sym; trans; cong; subst; subst-const)
open import Substrate.Foundation.Product
  using (Σ; _,_; proj₁; proj₂; _×_; Σ-≡,≡→≡)
open import Substrate.Foundation.Vec using (lookup; tabulate)
open import Substrate.Foundation.Vec.Properties using (lookup∘tabulate; ≡-dec)
open import Substrate.Foundation.Hedberg using (Decidable⇒UIP)

open import Substrate.WitnessTower.Enumerate using (Perm)
open import Substrate.WitnessTower.FirstAppearance using (id-perm; compose)
open import Substrate.WitnessTower.SnGroup
  using ( apply; apply-compose; apply-id; apply-injective
        ; compose-is-perm; compose-id-left; compose-id-right )
open import Substrate.WitnessTower.CyclicGrounding using (compose-assoc)
open import Substrate.WitnessTower.IsPermutation using (IsPerm)
open import Substrate.WitnessTower.Surjective using (perm-surjective)

open import Substrate.WitnessTower.Wedge.OrientationBimonoidal
  using (GradedProductOver; _∧_; u)
open import Substrate.WitnessTower.Wedge.OrientationRigCat
  using ( GradedRigCat; Objₛ; ⋆
        ; idHom; _∘_; braid⊕; braid⊗; braid⊕-invol; braid⊗-invol )
open import Substrate.WitnessTower.Wedge.OrientationRigCatPerm
  using (orientationRigCatPerm; Objₚ; Homᵣ; idᵣ; _∘ᵣ_; left-idᵣ; right-idᵣ; assocᵣ)

private
  ob = orientationRigCatPerm

------------------------------------------------------------------------
-- S0 — Perm n is a SET (UIP). Vec (Fin n) n has decidable equality
-- (≡-dec on Fin _≟_), so Hedberg gives uniqueness of identity proofs. This
-- is what makes the Iso round-trip proofs a proposition — no funext.
------------------------------------------------------------------------

perm-UIP : {n : ℕ} {σ τ : Perm n} (p q : σ ≡ τ) → p ≡ q
perm-UIP {n} = Decidable⇒UIP (≡-dec (_≟_ {n}))

-- (`subst-const` — constant-family `subst` is the identity — was proved here
-- locally; it is now imported from `Foundation.Eq`, level-polymorphic. The
-- second consumer that forced the home is `Algebra.Z.JacobianNegSemiring`.)

-- a product of two mere propositions is a mere proposition (funext-free:
-- the components are ≡-in-a-set, Σ-≡ closes the pair).
×-eq-prop : {P Q : Set} → ((a b : P) → a ≡ b) → ((a b : Q) → a ≡ b) →
            (x y : P × Q) → x ≡ y
×-eq-prop Pp Qp (x₁ , x₂) (y₁ , y₂) =
  Σ-≡,≡→≡ (Pp x₁ y₁ , trans (subst-const (Pp x₁ y₁) x₂) (Qp x₂ y₂))

------------------------------------------------------------------------
-- S1 — THE PERMUTATION WITNESS Iso and its mere-proposition-ness.
------------------------------------------------------------------------

-- σ is a permutation: it has a two-sided inverse under `compose`. Honest DATA
-- (the inverse + its two round-trips), not an ∃-packaged existence claim.
Iso : {n : ℕ} → Perm n → Set
Iso {n} σ = Σ (Perm n) (λ τ → (compose σ τ ≡ id-perm n) × (compose τ σ ≡ id-perm n))

-- inverse uniqueness — pure monoid algebra (no funext, no finiteness):
--   τ = id·τ = (τ'·σ)·τ = τ'·(σ·τ) = τ'·id = τ'.
-- (σ τ τ' are EXPLICIT: `compose` never reduces to expose them, so they can
-- not be inferred from the argument types — the substrate-wide _∘ᵣ_/Iso idiom.)
inv-unique : {n : ℕ} (σ τ τ' : Perm n) →
             compose σ τ ≡ id-perm n → compose τ' σ ≡ id-perm n → τ ≡ τ'
inv-unique σ τ τ' στ τ'σ =
  trans (sym (compose-id-left τ))
  (trans (cong (λ z → compose z τ) (sym τ'σ))
  (trans (compose-assoc τ' σ τ)
  (trans (cong (compose τ') στ)
         (compose-id-right τ'))))

-- Iso is a mere proposition: the inverse is unique (inv-unique) and the two
-- round-trips are UIP (perm-UIP). No funext anywhere.
Iso-prop : {n : ℕ} {σ : Perm n} (p q : Iso σ) → p ≡ q
Iso-prop {σ = σ} (τ , στ , τσ) (τ' , στ' , τ'σ) =
  Σ-≡,≡→≡ (inv-unique σ τ τ' στ τ'σ , ×-eq-prop perm-UIP perm-UIP _ (στ' , τ'σ))

------------------------------------------------------------------------
-- S2 — Iso ⇔ IsPerm, and the small closure lemmas that let every operation
-- rebuild its Iso witness uniformly through IsPerm→Iso.
------------------------------------------------------------------------

-- a LEFT inverse forces injectivity: h·g = id ⇒ g injective (i ↦ h(g i) = i).
left-inv→isperm : {n : ℕ} (h g : Perm n) → compose h g ≡ id-perm n → IsPerm g
left-inv→isperm h g hg i j e =
  trans (sym (idhg i)) (trans (cong (lookup h) e) (idhg j))
  where
    idhg : (k : Fin _) → lookup h (lookup g k) ≡ k
    idhg k = trans (sym (apply-compose h g k))
                   (trans (cong (λ p → lookup p k) hg) (apply-id k))

-- Iso ⇒ IsPerm: read off the left inverse (the τσ = id round-trip).
Iso→IsPerm : {n : ℕ} (σ : Perm n) → Iso σ → IsPerm σ
Iso→IsPerm σ (τ , _ , τσ) = left-inv→isperm τ σ τσ

-- IsPerm ⇒ Iso: the inverse is "where does σ send something to y"
-- (perm-surjective), exactly SymBridge.to-Sym at the vector level.
IsPerm→Iso : {n : ℕ} (σ : Perm n) → IsPerm σ → Iso σ
IsPerm→Iso σ pf = τ , right , left
  where
    τ : Perm _
    τ = tabulate (λ y → proj₁ (perm-surjective σ pf y))
    right : compose σ τ ≡ id-perm _
    right = apply-injective (λ y →
      trans (apply-compose σ τ y)
      (trans (cong (lookup σ) (lookup∘tabulate _ y))
      (trans (proj₂ (perm-surjective σ pf y))
             (sym (apply-id y)))))
    left : compose τ σ ≡ id-perm _
    left = apply-injective (λ x →
      trans (apply-compose τ σ x)
      (trans (lookup∘tabulate _ (lookup σ x))
      (trans (pf _ _ (proj₂ (perm-surjective σ pf (lookup σ x))))
             (sym (apply-id x)))))

-- IsPerm transported along a grade-equality (needed for _∘ᵣ_, whose perm part
-- carries a subst Perm).
isperm-subst : {n n' : ℕ} (q : n ≡ n') (σ : Perm n) → IsPerm σ → IsPerm (subst Perm q σ)
isperm-subst refl σ p = p

isperm-subst-inv : {n n' : ℕ} (q : n ≡ n') (σ : Perm n) →
                   IsPerm (subst Perm q σ) → IsPerm σ
isperm-subst-inv refl σ p = p

------------------------------------------------------------------------
-- S3 — THE MORPHISMS. Homˢ = a Homᵣ arrow whose Perm component is a genuine
-- permutation (Iso). Because Iso is a proposition, morphism equality reduces to
-- equality of the underlying Homᵣ arrow (homEqˢ) — the whole point of Sₙ ⊂ Tₙ.
------------------------------------------------------------------------

Homˢ : ℕ → ℕ → Set
Homˢ i j = Σ (Homᵣ i j) (λ h → Iso (proj₂ h))

Homˢᵒ : {i j : ℕ} → Objₚ i → Objₚ j → Set
Homˢᵒ {i} {j} _ _ = Homˢ i j

-- morphism equality from the Homᵣ component alone (Iso-prop discharges the rest).
homEqˢ : {i j : ℕ} {h h' : Homˢ i j} → proj₁ h ≡ proj₁ h' → h ≡ h'
homEqˢ {h' = h'} e = Σ-≡,≡→≡ (e , Iso-prop {σ = proj₂ (proj₁ h')} _ _)

------------------------------------------------------------------------
-- S4 — IDENTITY, COMPOSITION, LAWS. The Homᵣ parts ARE orientationRigCatPerm's;
-- the Iso witnesses are rebuilt via IsPerm→Iso from the committed
-- id-perm / compose closure of IsPerm. The laws are the Homᵣ laws under homEqˢ.
------------------------------------------------------------------------

-- Iso of the identity — directly (inverse = id-perm, both round-trips compose-id).
iso-id : {n : ℕ} → Iso (id-perm n)
iso-id {n} = id-perm n , compose-id-left (id-perm n) , compose-id-left (id-perm n)

idˢ : (i : ℕ) → Homˢ i i
idˢ i = idᵣ i , iso-id

infixr 9 _∘ˢ_
_∘ˢ_ : {i j k : ℕ} → Homˢ j k → Homˢ i j → Homˢ i k
g ∘ˢ f = h , IsPerm→Iso (proj₂ h) (compose-is-perm σg τf pg pf)
  where
    h  = proj₁ g ∘ᵣ proj₁ f
    σg = proj₂ (proj₁ g)
    τf = subst Perm (proj₁ (proj₁ g)) (proj₂ (proj₁ f))
    pg = Iso→IsPerm σg (proj₂ g)
    pf = isperm-subst (proj₁ (proj₁ g)) (proj₂ (proj₁ f))
                      (Iso→IsPerm (proj₂ (proj₁ f)) (proj₂ f))

left-idˢ : {i j : ℕ} (f : Homˢ i j) → (idˢ j ∘ˢ f) ≡ f
left-idˢ f = homEqˢ (left-idᵣ (proj₁ f))

right-idˢ : {i j : ℕ} (f : Homˢ i j) → (f ∘ˢ idˢ i) ≡ f
right-idˢ f = homEqˢ (right-idᵣ (proj₁ f))

assocˢ : {i j k l : ℕ} (f : Homˢ i j) (g : Homˢ j k) (h : Homˢ k l) →
         ((h ∘ˢ g) ∘ˢ f) ≡ (h ∘ˢ (g ∘ˢ f))
assocˢ f g h = homEqˢ (assocᵣ (proj₁ f) (proj₁ g) (proj₁ h))

------------------------------------------------------------------------
-- S5 — THE BRAIDINGS. The Homᵣ arrow IS orientationRigCatPerm's braid⊕/braid⊗;
-- its Iso witness is read off the braiding's OWN involution (braid⊕/⊗-invol
-- supply a left inverse ⇒ IsPerm ⇒ Iso). The Sym involution law is then the
-- Homᵣ involution under homEqˢ.
------------------------------------------------------------------------

-- The braiding IS a permutation: its OWN involution (braid⊕-invol) reads
-- `compose H G ≡ id` with G = the transported braiding, a left inverse ⇒ IsPerm.
iso-braid⊕ : {i j : ℕ} (a : Objₚ i) (b : Objₚ j) → Iso (proj₂ (braid⊕ ob a b))
iso-braid⊕ a b =
  IsPerm→Iso (proj₂ (braid⊕ ob a b))
    (isperm-subst-inv (proj₁ (braid⊕ ob b a)) (proj₂ (braid⊕ ob a b))
      (left-inv→isperm
        (proj₂ (braid⊕ ob b a))
        (subst Perm (proj₁ (braid⊕ ob b a)) (proj₂ (braid⊕ ob a b)))
        (cong proj₂ (braid⊕-invol ob a b))))

iso-braid⊗ : {i j : ℕ} (a : Objₚ i) (b : Objₚ j) → Iso (proj₂ (braid⊗ ob a b))
iso-braid⊗ a b =
  IsPerm→Iso (proj₂ (braid⊗ ob a b))
    (isperm-subst-inv (proj₁ (braid⊗ ob b a)) (proj₂ (braid⊗ ob a b))
      (left-inv→isperm
        (proj₂ (braid⊗ ob b a))
        (subst Perm (proj₁ (braid⊗ ob b a)) (proj₂ (braid⊗ ob a b)))
        (cong proj₂ (braid⊗-invol ob a b))))

braidˢ⊕ : {i j : ℕ} (a : Objₚ i) (b : Objₚ j) → Homˢ (i + j) (j + i)
braidˢ⊕ a b = braid⊕ ob a b , iso-braid⊕ a b

braidˢ⊗ : {i j : ℕ} (a : Objₚ i) (b : Objₚ j) → Homˢ (i * j) (j * i)
braidˢ⊗ a b = braid⊗ ob a b , iso-braid⊗ a b

------------------------------------------------------------------------
-- S6 — THE OBJECT-MONOID PRODUCTS. Objₚ = Objₛ is the grade-indexed singleton;
-- both products are the trivial GradedProductOver (u = ⋆, _∧_ = λ _ _ → ⋆),
-- IDENTICAL to orientationRigCatPerm. All symmetry lives in the Sₙ morphisms.
------------------------------------------------------------------------

⊕objₛ : GradedProductOver _+_ 0 Objₚ
⊕objₛ = record { u = ⋆ ; _∧_ = λ _ _ → ⋆ }

⊗objₛ : GradedProductOver _*_ 1 Objₚ
⊗objₛ = record { u = ⋆ ; _∧_ = λ _ _ → ⋆ }

------------------------------------------------------------------------
-- S7 — THE INSTANCE. The genuine symmetric (Sₙ-morphism) rig category.
-- Green at `: GradedRigCat Objₚ Homˢᵒ`.
------------------------------------------------------------------------

orientationRigCatSym : GradedRigCat Objₚ Homˢᵒ
orientationRigCatSym = record
  { idHom        = λ {i} _ → idˢ i
  ; _∘_          = λ g f → g ∘ˢ f
  ; left-id      = λ f → left-idˢ f
  ; right-id     = λ f → right-idˢ f
  ; assoc        = λ f g h → assocˢ f g h
  ; ⊕obj         = ⊕objₛ
  ; ⊗obj         = ⊗objₛ
  ; braid⊕       = λ a b → braidˢ⊕ a b
  ; braid⊗       = λ a b → braidˢ⊗ a b
  ; braid⊕-invol = λ a b → homEqˢ (braid⊕-invol ob a b)
  ; braid⊗-invol = λ a b → homEqˢ (braid⊗-invol ob a b)
  }
