------------------------------------------------------------------------
-- Substrate.WitnessTower.Wedge.PyAstRewrite
--
-- ⟡pyrig-rebuild-rig — THE CORRECTED pyast rewrite rig. (SPPF-built-wrong
-- correction: PyAstRig built `Objpy = SPPF (Fin n)`, the free SEMIRING on
-- operand POSITIONS — the OBJECT carrier — when the rig is meant to be the
-- MORPHISMS: the semantics-preserving TRANSFORMATIONS.)
--
-- A pyast rewrite IS a word in the Coxeter generators (adjacent transpositions)
-- = a permutation in Lehmer normal form. The tower ALREADY is this rig:
-- `LehmerPath` (the INITIAL rig algebra), each Coxeter word a generator. So the
-- rig is REUSED, not rebuilt — and the residue/initiality "splits" of
-- ⟡pyrig-ground DISSOLVE into INSTANCES of the proven tower machinery:
--
--   PyRewrite      = LehmerPath              -- the rewrite rig (words = Coxeter words)
--   interp         = foldR                    -- pyEval, now THE unique interpretation (initiality)
--   interp-id                                 -- reading a rewrite into itself = its normal form
--   rewrite-is-coxeter-word                   -- every rewrite IS an adjacent-transposition word
--
-- Zero postulates, --safe --without-K.
------------------------------------------------------------------------

{-# OPTIONS --safe --without-K #-}

module Substrate.WitnessTower.Wedge.PyAstRewrite where

open import Substrate.Foundation.Nat using (ℕ)
open import Substrate.Foundation.Eq using (_≡_)
open import Substrate.WitnessTower.LehmerPath using (LehmerPath; decode; decode-is-perm)
open import Substrate.WitnessTower.Wedge.OrientationRigInitial using (RigAlgebra; foldR)
open import Substrate.WitnessTower.Wedge.OrientationRigInstance using (LehmerRig; fold-idAlg)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral using (CoxGen)
open import Substrate.WitnessTower.Wedge.OrientationRigCatPermCoxeterGeneral.Properties
  using (coxeter-complete)

-- THE REWRITE RIG: a pyast rewrite = a permutation in Lehmer normal form = a Coxeter word.
-- Reused verbatim from the tower — NOT a new SPPF.
PyRewrite : ℕ → Set
PyRewrite = LehmerPath

-- pyEval, CORRECTED: interpret a rewrite in any semantic rig algebra. This is the UNIQUE map out
-- of the initial rig algebra — `foldR` — so the initiality face is now a literal INSTANCE (was:
-- SPPF's `inside`, a DIFFERENT initial object). "The universal fold" is the tower's own theorem.
interp : {C : ℕ → Set} → RigAlgebra C → {n : ℕ} → PyRewrite n → C n
interp = foldR

-- GROUNDING 1: interpreting a rewrite into the canonical (identity) rig algebra returns it — the
-- rewrite read as itself IS its normal form (foldR LehmerRig = fold idAlg = id).
interp-id : {n : ℕ} (l : PyRewrite n) → interp LehmerRig l ≡ l
interp-id = fold-idAlg

-- GROUNDING 2 (the correction, witnessed): every rewrite IS a word in the Coxeter generators —
-- its decode is generated by the adjacent transpositions. "Each Coxeter word is a generator."
rewrite-is-coxeter-word : {n : ℕ} (l : PyRewrite n) → CoxGen (decode l)
rewrite-is-coxeter-word l = coxeter-complete (decode l) (decode-is-perm l)
