#!/usr/bin/env python3
"""query_builders.py — ⟡qinfra: the cached RUNTIME. Imports NO SQLAlchemy: executes precompiled SQL from the
generated `query_sql.py` by NAME. The compiler + the builder definitions live in the sibling `query_defs.py`;
regenerate the cache with `python3 query_defs.py --compile` (drift-gated by `--check`).

    import query_builders as QB
    QB.run(con, "unit_cod")                 # named: fast path — no SQLAlchemy import
    QB.run(con, "fanin", lim=20)            # named + params (merged over the builder's baked literal defaults)

Why: `import query_defs` costs ~0.4s (SQLAlchemy's SQL-compilation layer). The hot paths — sppf_db
`--ingest-core`, the pre-commit gates — only READ, so they `import query_builders` and pay ~nothing. The
runtime `run` merges the caller's params over the builder's compiled defaults (baked string/int literals like
COALESCE's `''`/`0`), replaying exactly what query_defs.run would have compiled — byte-equivalent results.

Back-compat: `run(con, <Core stmt>, **params)` (a non-str first arg) lazy-imports query_defs and compiles —
the dynamic path (a query whose TEXT genuinely varies), which pays SQLAlchemy only there.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)
try:
    from query_sql import SQL  # {name: (sql_text, default_params)} — generated by query_defs.py --compile
except Exception:  # pragma: no cover — absent before the first --compile; named lookups then KeyError loudly
    SQL = {}


def run(con, name, **params):
    """Execute a compiled read-query by NAME on the existing sqlite3 connection (no engine churn, column order
    preserved for Row/positional reads). A non-str `name` is a Core stmt → lazy-compile via query_defs."""
    if isinstance(name, str):
        try:
            sql, defaults = SQL[name]
        except KeyError:
            raise KeyError(f"query_builders: no compiled query {name!r}; the builder set changed — regenerate "
                           f"query_sql.py via `python3 jea/metalanguage/query_defs.py --compile`") from None
        p = dict(defaults)
        p.update(params)
        return con.execute(sql, p)
    from query_defs import run as _compile_run  # back-compat: a Core stmt object (dynamic path)
    return _compile_run(con, name, **params)
