#!/usr/bin/env python3
"""synth_agda_prototype.py — ⟡pipeline-driver: numpy ⊗ dedup/catalog → an Agda PROTOTYPE.

The three prior tools STOP at "an LLM writes the Agda" (typeholer_path.py says so in its
HONEST SCOPE). This closes that last step: ONE script that runs the three engines and EMITS
a compiling Agda module.

  1. numpy SEARCH  — enumerate the concrete instance (here: a permutation subgroup and its
     finite closure under `compose`), and VERIFY the target's (non-)membership + the k×k
     product table. This is the "show a solution exists" step, now the synthesis INPUT.
  2. catalog/dedup DB — resolve every Agda name the prototype needs (Perm, compose, id-perm,
     ⊎, ¬, …) to its canonical home by reading `catalog/reuse-index.md` (the dedup machinery's
     product: it is generated by gen_reuse_index.py from the typechecked .agdai cores). The
     deeper structural confirmation is `jea_pysim … --clusters` (see --check-pieces).
  3. EMIT  — write the Agda module: imports (resolved), the concrete Fin-vector literals, the
     ⊎-membership predicate S, the inductively-generated subgroup `data …Gen`, the finite
     closure lemma S-closed (numpy's k×k table, each case `refl`), Gen⊆S, ¬S-target, and the
     witness `¬ …Gen target`.

The core is a FACT-FAMILY → CLAUSE engine (numpy enumerates a finite family of decidable
ground facts; each becomes a `refl`/`()` Agda clause under a structured wrapper). The wrapper
is a pluggable prototype CLASS — the tool ships five, all over the same numpy closure:

  · nonmembership — `¬ (target ∈ ⟨gens⟩)`: the ⊎-membership S, the inductive `data …Gen`, the
    finite-closure table, and the witness. (Re-derives the hand-checked grade-3 theorem
    `Substrate.WitnessTower.Wedge.OrientationRigCatPermGap` mechanically, at any grade.)
  · equation — a numpy-verified `compose`/`id` identity over the domain, e.g. commutativity
    `compose a b = compose b a`, emitted as `law : {…} → S … → LHS ≡ RHS` with one refl clause
    per assignment; on failure emits the NEGATIVE-SPACE witness (a concrete `¬`-counterexample),
    never nothing.
  · residue — the wedge defect `δ = LHS·RHS⁻¹` (the path of paths BETWEEN `≡` and `¬`): the δ-field
    over the domain + the reconstruction `LHS ≡ compose δ RHS` (all refl) + the spectrum `im δ`
    (for commutativity, the commutator subgroup).
  · orbit — the FULL group `⟨gens⟩` mapped as generator-words + `complete : AllGen σ → …Gen σ`;
    when `|orbit| = n!` this IS Coxeter-completeness at grade n.
  · cayley — the complete finite group as its multiplication (Cayley) TABLE (`mul-table`'s clauses
    ARE the table: `eᵢ·eⱼ = e_{f(i,j)}`) + the inverse map (`eᵢ·e_{inv i} ≡ id`), all refl.
  · reconstruct — the Set₀ reconstruction of a Set₁ target (⟡pipeline-driver-reconstruct). Two modes:
      · --recon-target <builtin> (e.g. `refinement`) — a located rich reconstruction (graded, grade-
        exposed); e.g. Refinement Set₁ → GRefinement : Set + reify, residue = the grade. Shape LOCATED
        mechanically (numpy verifies the correspondence; jea_pysim locates the carrier-hole).
      · --recon-source <file> --recon-record <R> — GENERAL M1 carrier-parameterization: PARSE `record R
        : Set₁`, hoist its bare-`Set` carrier field to a module PARAM ⇒ Rₚ : Set (the paydown, e.g.
        ShadowArchitecture.Cell). If a non-carrier field is itself Set₁-typed (M1+M2), the driver REPORTS
        that TRANSITIVE RESIDUE (reconstruct those types first, recursively) — the negative space, honest.

Usage (caller chooses --out; e.g. a temp dir, kept out of the promoted tree):
  # non-membership witness:
  synth_agda_prototype.py --class nonmembership --grade 3 --gens '2,0,1;1,2,0' \
      --target '1,0,2' --module PermGapPrototype --out /tmp/gen/PermGapPrototype.agda
  # equational law (C₃ is abelian):
  synth_agda_prototype.py --class equation --grade 3 --gens '2,0,1;1,2,0' \
      --law 'compose a b = compose b a' --lawname C₃-abelian \
      --module C3AbelianProto --out /tmp/gen/C3AbelianProto.agda
  # then typecheck:  agda --safe -i /tmp/gen -i agda /tmp/gen/<Module>.agda
"""
from __future__ import annotations
import sys, os, argparse, re
from itertools import product

# ── 1. numpy SEARCH ─────────────────────────────────────────────────────────
# (pure-tuple perm algebra; numpy used if present, but not required — the search
#  is over Sₙ which is finite and small.)

def compose(sigma, tau):
    """(compose σ τ)[i] = σ[τ[i]]  — the tower's `compose` semantics (lookup∘lookup)."""
    return tuple(sigma[tau[i]] for i in range(len(sigma)))

def orbit_words(gens, n):
    """BFS the orbit ⟨gens⟩ from id; returns (order, parent) where order is the
    reachable elements (id first, BFS/shortest-word order) and parent[y] = (gi, x)
    means y = compose(gens[gi], x) — the shortest generator-word to y."""
    ident = tuple(range(n))
    parent = {ident: None}
    order = [ident]
    dq = [ident]
    head = 0
    while head < len(dq):
        x = dq[head]; head += 1
        for gi, g in enumerate(gens):
            y = compose(g, x)
            if y not in parent:
                parent[y] = (gi, x)
                order.append(y); dq.append(y)
    return order, parent

def closure_of(gens, n):
    """The subgroup generated by `gens` (+ identity) under compose. Returns (ordered
    element list with id first then the generators then the rest, index-map, product-table)."""
    ident = tuple(range(n))
    seen = {ident}
    frontier = [ident]
    while frontier:
        x = frontier.pop()
        for g in gens:
            for y in (compose(g, x), compose(x, g)):
                if y not in seen:
                    seen.add(y); frontier.append(y)
    # deterministic order: id, then the generators (in given order), then the rest sorted.
    ordered = [ident]
    for g in gens:
        if g not in ordered:
            ordered.append(g)
    for e in sorted(seen):
        if e not in ordered:
            ordered.append(e)
    idx = {e: i for i, e in enumerate(ordered)}
    table = {(i, j): idx[compose(ordered[i], ordered[j])]
             for i in range(len(ordered)) for j in range(len(ordered))}
    return ordered, idx, table

def cycle_type(p):
    n = len(p); seen = [False]*n; counts = [0]*(n+1)
    for i in range(n):
        if seen[i]:
            continue
        L = 0; j = i
        while not seen[j]:
            seen[j] = True; j = p[j]; L += 1
        counts[L] += 1
    return tuple(counts[1:])

# ── 2. catalog / dedup DB  (import resolution) ───────────────────────────────

# Foundation homes are stable; the domain names are confirmed against reuse-index.md.
FALLBACK_HOME = {
    "Fin": "Substrate.Foundation.Fin", "zero": "Substrate.Foundation.Fin",
    "suc": "Substrate.Foundation.Fin",
    "Vec": "Substrate.Foundation.Vec", "[]": "Substrate.Foundation.Vec",
    "_∷_": "Substrate.Foundation.Vec",
    "_≡_": "Substrate.Foundation.Eq", "refl": "Substrate.Foundation.Eq",
    "_⊎_": "Substrate.Foundation.Sum", "inj₁": "Substrate.Foundation.Sum",
    "inj₂": "Substrate.Foundation.Sum",
    "¬_": "Substrate.Foundation.Negation",
    "Perm": "Substrate.WitnessTower.Enumerate",
    "id-perm": "Substrate.WitnessTower.FirstAppearance",
    "compose": "Substrate.WitnessTower.FirstAppearance",
}

def resolve_homes(names, repo_root):
    """Resolve each name to its canonical Agda home, consulting catalog/reuse-index.md
    (the dedup-derived catalog) first, falling back to the stable foundation map."""
    index_path = os.path.join(repo_root, "catalog", "reuse-index.md")
    index_txt = ""
    if os.path.exists(index_path):
        with open(index_path, encoding="utf-8") as fh:
            index_txt = fh.read()
    homes = {}
    for nm in names:
        home = None
        # catalog lookup: a line `... `Name`@`Module`` or `| Name | ... | Module |`
        m = re.search(r"`" + re.escape(nm) + r"`\s*(?:@|—|·)?\s*`?(Substrate\.[\w.]+)`?", index_txt)
        if m:
            home = m.group(1)
        homes[nm] = home or FALLBACK_HOME.get(nm)
    return homes

# ── 3. EMIT  ─────────────────────────────────────────────────────────────────

def fin_lit(v):
    """A Fin literal: 0→zero, 1→suc zero, 2→suc (suc zero), …"""
    if v == 0:
        return "zero"
    inner = fin_lit(v - 1)
    return "suc " + (f"({inner})" if v - 1 > 0 else "zero")

def perm_lit(p):
    return " ∷ ".join(fin_lit(v) for v in p) + " ∷ []"

def nest(m, k, inner):
    """Select the m-th of k right-nested ⊎ slots, wrapping `inner` (a value or pattern).
    m<k-1: inj₂^m (inj₁ inner);  m==k-1: inj₂^m inner."""
    if k == 1:
        return inner
    if m < k - 1:
        s = "inj₁ " + inner
        for _ in range(m):
            s = "inj₂ (" + s + ")"
        return s
    else:  # last slot: all inj₂
        s = inner
        for _ in range(m):
            s = "inj₂ (" + s + ")"
        return s

def emit_nonmembership(module, n, gens, target, ordered, table, homes):
    k = len(ordered)
    ident = tuple(range(n))
    # element names: e0 = id, generators keep g-names, rest h-names
    names = []
    for i, e in enumerate(ordered):
        if e == ident:
            names.append("p-id")
        elif e in gens:
            names.append(f"p-g{gens.index(e)+1}")
        else:
            names.append(f"p-h{i}")
    tname = "t-tgt"
    gen_dtype = module.split(".")[-1] + "Gen" if False else "BraidGen"

    # imports grouped by home
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "¬_", "Perm", "id-perm", "compose"]
    by_home = {}
    for nm in need:
        h = homes.get(nm)
        by_home.setdefault(h, []).append(nm)
    import_lines = []
    for h in ["Substrate.Foundation.Fin", "Substrate.Foundation.Vec",
              "Substrate.Foundation.Eq", "Substrate.Foundation.Sum",
              "Substrate.Foundation.Negation", "Substrate.WitnessTower.Enumerate",
              "Substrate.WitnessTower.FirstAppearance"]:
        if h in by_home:
            import_lines.append(f"open import {h} using ({'; '.join(by_home[h])})")

    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver):")
    L.append("--   numpy enumerated the grade-%d braiding subgroup ⟨%s⟩ = C%d (order %d, closed" %
             (n, ", ".join(str(list(g)) for g in gens), k, k))
    L.append("--   under compose); the target %s is NOT in it. Imports resolved from" % (list(target),))
    L.append("--   catalog/reuse-index.md. Each closure case is `refl`; the target disequalities")
    L.append("--   are constructor-distinct `()`. Zero postulates, zero holes, --safe --without-K.")
    L.append("------------------------------------------------------------------------")
    L.append("")
    L.append("{-# OPTIONS --safe --without-K #-}")
    L.append("")
    L.append(f"module {module} where")
    L.append("")
    L.extend(import_lines)
    L.append("")
    L.append(f"-- the {k} concrete grade-{n} group elements and the target.")
    sig = " ".join(names + [tname])
    L.append(f"{sig} : Perm {n}")
    for nm, e in zip(names, ordered):
        L.append(f"{nm} = {perm_lit(e)}")
    L.append(f"{tname} = {perm_lit(target)}")
    L.append("")
    # S predicate
    disj = " ⊎ ".join(f"(σ ≡ {nm})" for nm in names)
    # right-nest the parenthesisation
    def paren_disj(nms):
        if len(nms) == 1:
            return f"(σ ≡ {nms[0]})"
        return f"(σ ≡ {nms[0]}) ⊎ ({paren_disj(nms[1:])})"
    L.append(f"S : Perm {n} → Set")
    L.append(f"S σ = {paren_disj(names)}")
    L.append("")
    # data …Gen
    L.append(f"data {gen_dtype} : Perm {n} → Set where")
    L.append(f"  gen-id : {gen_dtype} p-id")
    for gi, g in enumerate(gens):
        L.append(f"  gen-g{gi+1} : {gen_dtype} p-g{gi+1}")
    L.append(f"  gen-∘  : {{σ τ : Perm {n}}} → {gen_dtype} σ → {gen_dtype} τ → {gen_dtype} (compose σ τ)")
    L.append("")
    # S-closed (k×k table)
    L.append(f"S-closed : {{σ τ : Perm {n}}} → S σ → S τ → S (compose σ τ)")
    for i in range(k):
        for j in range(k):
            lhs_i = nest(i, k, "refl"); lhs_j = nest(j, k, "refl")
            rhs = nest(table[(i, j)], k, "refl")
            L.append(f"S-closed ({lhs_i}) ({lhs_j}) = {rhs}")
    L.append("")
    # Gen⊆S
    L.append(f"Gen⊆S : {{σ : Perm {n}}} → {gen_dtype} σ → S σ")
    id_idx = ordered.index(ident)
    L.append(f"Gen⊆S gen-id      = {nest(id_idx, k, 'refl')}")
    for gi, g in enumerate(gens):
        L.append(f"Gen⊆S gen-g{gi+1}      = {nest(ordered.index(g), k, 'refl')}")
    L.append(f"Gen⊆S (gen-∘ g h) = S-closed (Gen⊆S g) (Gen⊆S h)")
    L.append("")
    # ¬S-target
    L.append(f"¬S-tgt : ¬ S {tname}")
    for m in range(k):
        L.append(f"¬S-tgt ({nest(m, k, '()')})")
    L.append("")
    # witness
    L.append(f"witness : ¬ {gen_dtype} {tname}")
    L.append(f"witness g = ¬S-tgt (Gen⊆S g)")
    L.append("")
    return "\n".join(L)

# ── the `equation` class: a general pointwise `compose`/`id` identity ────────
# A second prototype SHAPE sharing the enumerate→resolve→emit core: numpy verifies
# a permutation identity over a finite domain (the closure), and each assignment
# becomes a `refl` clause under a ∀-over-S wrapper. Demonstrates that the core is a
# fact-family→clause engine, not a non-membership-specific one.

def tokenize_expr(s):
    return s.replace("(", " ( ").replace(")", " ) ").split()

def parse_expr(toks):
    t = toks.pop(0)
    if t == "(":
        e = parse_expr(toks)
        assert toks and toks.pop(0) == ")", "unbalanced ()"
        return e
    if t == "compose":
        a = parse_expr(toks); b = parse_expr(toks); return ("compose", a, b)
    if t == "id":
        return ("id",)
    return ("var", t)

def eval_expr(e, env, n):
    if e[0] == "compose":
        return compose(eval_expr(e[1], env, n), eval_expr(e[2], env, n))
    if e[0] == "id":
        return tuple(range(n))
    return env[e[1]]

def inverse(p):
    inv = [0] * len(p)
    for i, pi in enumerate(p):
        inv[pi] = i
    return tuple(inv)

def render_expr(e, n, top=True):
    if e[0] == "compose":
        s = f"compose {render_expr(e[1], n, False)} {render_expr(e[2], n, False)}"
        return s if top else f"({s})"
    if e[0] == "id":
        return f"id-perm {n}" if top else f"(id-perm {n})"
    return e[1]

def free_vars(e, acc):
    if e[0] == "compose":
        free_vars(e[1], acc); free_vars(e[2], acc)
    elif e[0] == "var" and e[1] not in acc:
        acc.append(e[1])

def _elem_names(n, ordered, gens):
    ident = tuple(range(n)); names = []
    for i, e in enumerate(ordered):
        if e == ident:
            names.append("p-id")
        elif e in gens:
            names.append(f"p-g{gens.index(e)+1}")
        else:
            names.append(f"p-h{i}")
    return names

def _paren_disj(names):
    if len(names) == 1:
        return f"(σ ≡ {names[0]})"
    return f"(σ ≡ {names[0]}) ⊎ ({_paren_disj(names[1:])})"

def _eq_imports(homes, need):
    by_home = {}
    for nm in need:
        by_home.setdefault(homes.get(nm), []).append(nm)
    lines = []
    for h in ["Substrate.Foundation.Fin", "Substrate.Foundation.Vec",
              "Substrate.Foundation.Eq", "Substrate.Foundation.Sum",
              "Substrate.Foundation.Negation", "Substrate.WitnessTower.Enumerate",
              "Substrate.WitnessTower.FirstAppearance"]:
        if h in by_home:
            lines.append(f"open import {h} using ({'; '.join(by_home[h])})")
    return lines

def emit_equation(module, n, gens, ordered, homes, lhs, rhs, lawname):
    """Emit the identity at WHATEVER POLARITY numpy finds it — never nothing:
      · holds on every assignment  → the positive lemma  {v…} → S v… → LHS ≡ RHS  (refl table);
      · fails somewhere            → the NEGATIVE-SPACE witness  ¬ (LHS ≡ RHS) at a concrete
                                     counterexample (a covered constraint, not a deleted finding).
    Returns (src, polarity, n_holds, n_fails)."""
    k = len(ordered)
    lvs, rvs = [], []
    free_vars(lhs, lvs); free_vars(rhs, rvs)
    vs = []
    for v in lvs + rvs:
        if v not in vs:
            vs.append(v)
    arity = len(vs)

    holds, fail_envs = 0, []
    for combo in product(range(k), repeat=arity):
        env = {v: ordered[combo[m]] for m, v in enumerate(vs)}
        if eval_expr(lhs, env, n) == eval_expr(rhs, env, n):
            holds += 1
        else:
            fail_envs.append(combo)
    total = k ** arity

    if not fail_envs:
        # ── positive: the refl-table lemma over the ⊎-membership domain ──
        names = _elem_names(n, ordered, gens)
        need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
                "_⊎_", "inj₁", "inj₂", "Perm", "id-perm", "compose"]
        L = []
        L.append("------------------------------------------------------------------------")
        L.append(f"-- {module}")
        L.append("--")
        L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
        L.append("-- `equation` class, POSITIVE polarity): numpy verified the identity")
        L.append(f"--     {render_expr(lhs,n)}  ≡  {render_expr(rhs,n)}")
        L.append(f"--   over the grade-{n} domain ⟨{', '.join(str(list(g)) for g in gens)}⟩ = C{k}")
        L.append(f"--   — all {total} assignments hold. Each is a `refl` clause. Imports from")
        L.append("--   catalog/reuse-index.md. Zero postulates/holes, --safe --without-K.")
        L.append("------------------------------------------------------------------------")
        L.append(""); L.append("{-# OPTIONS --safe --without-K #-}"); L.append("")
        L.append(f"module {module} where"); L.append("")
        L.extend(_eq_imports(homes, need)); L.append("")
        L.append(f"{' '.join(names)} : Perm {n}")
        for nm, e in zip(names, ordered):
            L.append(f"{nm} = {perm_lit(e)}")
        L.append("")
        L.append(f"S : Perm {n} → Set")
        L.append(f"S σ = {_paren_disj(names)}"); L.append("")
        hyps = " → ".join(f"S {v}" for v in vs)
        L.append(f"{lawname} : {{{' '.join(vs)} : Perm {n}}} → {hyps} → "
                 f"{render_expr(lhs,n)} ≡ {render_expr(rhs,n)}")
        for combo in product(range(k), repeat=arity):
            pats = " ".join(f"({nest(combo[m], k, 'refl')})" for m in range(arity))
            L.append(f"{lawname} {pats} = refl")
        L.append("")
        return "\n".join(L), "holds", holds, 0

    # ── negative space: a concrete counterexample refutation (¬), the covered constraint ──
    combo = fail_envs[0]
    ce = {v: ordered[combo[m]] for m, v in enumerate(vs)}
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "¬_", "Perm", "id-perm", "compose"]
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append("-- `equation` class, NEGATIVE polarity — the finding is NOT deleted, it is the")
    L.append("-- covered constraint). numpy found the identity")
    L.append(f"--     {render_expr(lhs,n)}  ≡  {render_expr(rhs,n)}")
    L.append(f"--   FAILS on {len(fail_envs)}/{total} assignments over the grade-{n} domain")
    L.append(f"--   ⟨{', '.join(str(list(g)) for g in gens)}⟩. Witnessed by the concrete")
    L.append(f"--   counterexample below (the negative space, as a ¬-refutation — reuse it as a")
    L.append("--   constraint to cover). Imports from catalog/reuse-index.md. --safe --without-K.")
    L.append("------------------------------------------------------------------------")
    L.append(""); L.append("{-# OPTIONS --safe --without-K #-}"); L.append("")
    L.append(f"module {module} where"); L.append("")
    L.extend(_eq_imports(homes, need)); L.append("")
    L.append(f"-- the counterexample assignment ({', '.join(f'{v}={list(ce[v])}' for v in vs)}):")
    L.append(f"-- LHS ↦ {list(eval_expr(lhs, ce, n))}   ≠   RHS ↦ {list(eval_expr(rhs, ce, n))}")
    L.append(f"{' '.join(vs)} : Perm {n}")
    for v in vs:
        L.append(f"{v} = {perm_lit(ce[v])}")
    L.append("")
    L.append(f"-- the law does NOT hold here: the two sides are constructor-distinct vectors.")
    L.append(f"{lawname}-counterexample : ¬ ({render_expr(lhs,n)} ≡ {render_expr(rhs,n)})")
    L.append(f"{lawname}-counterexample ()")
    L.append("")
    return "\n".join(L), "fails", holds, len(fail_envs)

def emit_residue(module, n, gens, ordered, homes, lhs, rhs, resname):
    """The PATH OF PATHS between (LHS ≡ RHS) and ¬(LHS ≡ RHS): the wedge residue
    δ(a…) = LHS · RHS⁻¹ (the counit-defect). It is `id` EXACTLY on the equation
    locus and the measured obstruction elsewhere; the reconstruction is the wedge
    `LHS ≡ compose δ RHS`, which holds IDENTICALLY (every assignment, refl). Emits
    the δ-field (a function over the ⊎-domain), the recon lemma, and the spectrum
    (im δ) — for commutativity, δ is the commutator [a,b] and im δ its image."""
    k = len(ordered)
    lvs, rvs = [], []
    free_vars(lhs, lvs); free_vars(rhs, rvs)
    vs = []
    for v in lvs + rvs:
        if v not in vs:
            vs.append(v)
    arity = len(vs)
    names = _elem_names(n, ordered, gens)
    ident = tuple(range(n))

    dtab, spectrum, holds = {}, [], 0
    for combo in product(range(k), repeat=arity):
        env = {v: ordered[combo[m]] for m, v in enumerate(vs)}
        Lv, Rv = eval_expr(lhs, env, n), eval_expr(rhs, env, n)
        d = compose(Lv, inverse(Rv))                     # δ = L·R⁻¹  ⇒  δ·R = L
        dtab[combo] = d
        if d == ident:
            holds += 1
        if d not in spectrum:
            spectrum.append(d)

    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "Perm", "id-perm", "compose"]
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append("-- `residue` class — THE PATH OF PATHS between (LHS ≡ RHS) and ¬(LHS ≡ RHS)).")
    L.append("-- The two polarities are the poles; the object BETWEEN them is the wedge")
    L.append("-- residue / counit-defect")
    L.append(f"--     δ(…) = {render_expr(lhs,n)} · ({render_expr(rhs,n)})⁻¹")
    L.append("-- which is `id` EXACTLY where the law holds and the measured obstruction")
    L.append("-- elsewhere. The reconstruction is the wedge  LHS ≡ compose δ RHS  — it holds")
    L.append(f"--   IDENTICALLY over the grade-{n} domain ⟨{', '.join(str(list(g)) for g in gens)}⟩")
    L.append(f"--   (all {k**arity} assignments refl). δ=id on {holds}/{k**arity} (the equation")
    L.append(f"--   locus); |im δ| = {len(spectrum)} (the defect spectrum = the path of paths;")
    L.append("--   for commutativity δ is the commutator [a,b]). --safe --without-K, no holes.")
    L.append("------------------------------------------------------------------------")
    L.append(""); L.append("{-# OPTIONS --safe --without-K #-}"); L.append("")
    L.append(f"module {module} where"); L.append("")
    L.extend(_eq_imports(homes, need)); L.append("")
    L.append(f"{' '.join(names)} : Perm {n}")
    for nm, e in zip(names, ordered):
        L.append(f"{nm} = {perm_lit(e)}")
    L.append("")
    L.append(f"S : Perm {n} → Set")
    L.append(f"S σ = {_paren_disj(names)}"); L.append("")
    # spectrum listing (the path-of-paths, im δ)
    L.append(f"-- the defect spectrum  im δ  ({len(spectrum)} element(s); {'ABELIAN — δ≡id' if spectrum == [ident] else 'the non-trivial path of paths'}):")
    for d in spectrum:
        L.append(f"--   {list(d)}" + ("   (= id, the equation locus)" if d == ident else ""))
    # δ : the residue field over the domain
    hyps_ty = " → ".join(f"S {v}" for v in vs)
    L.append(f"δ : {{{' '.join(vs)} : Perm {n}}} → {hyps_ty} → Perm {n}")
    for combo in product(range(k), repeat=arity):
        pats = " ".join(f"({nest(combo[m], k, 'refl')})" for m in range(arity))
        L.append(f"δ {pats} = {perm_lit(dtab[combo])}")
    L.append("")
    # the wedge/recon lemma: LHS ≡ compose δ RHS, identically (every assignment refl)
    sh = [f"s{m}" for m in range(arity)]
    binders = "".join(f"({sh[m]} : S {vs[m]}) " for m in range(arity)).rstrip()
    L.append(f"-- the wedge: LHS reconstructs from the residue δ over RHS (holds for ALL assignments).")
    L.append(f"{resname} : {{{' '.join(vs)} : Perm {n}}} {binders} → "
             f"{render_expr(lhs,n)} ≡ compose (δ {' '.join(sh)}) {render_expr(rhs,n,top=False)}")
    for combo in product(range(k), repeat=arity):
        pats = " ".join(f"({nest(combo[m], k, 'refl')})" for m in range(arity))
        L.append(f"{resname} {pats} = refl")
    L.append("")
    return "\n".join(L), holds, len(spectrum)

def emit_orbit(module, n, gens, homes, gname):
    """Fully map the group structure ⟨gens⟩ as an Agda file: `data …Gen` inductively
    generated by {id, gens…} under compose, an explicit generator-WORD witness for
    EVERY orbit element (from the BFS parent-tree — each y = compose gᵢ parent, so its
    witness is gen-∘ gen-gᵢ orbit-parent), and `complete : AllG σ → …Gen σ` — every
    listed element is reachable. If |orbit| = n!, this IS Coxeter-completeness at grade
    n (⟨gens⟩ = Sₙ), proven by exhausting the orbit."""
    import math
    order, parent = orbit_words(gens, n)
    k = len(order)
    idx = {e: i for i, e in enumerate(order)}
    gen_pos = [idx[g] for g in gens]                 # each generator's index in `order`
    full = (k == math.factorial(n))
    names = [f"e{i}" for i in range(k)]
    dtype = gname

    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "Perm", "id-perm", "compose"]
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append("-- `orbit` class — the full group structure ⟨gens⟩ mapped as generator-words).")
    L.append(f"--   grade {n}; generators {[list(g) for g in gens]}; |orbit| = {k}"
             + (f" = {n}! ⇒ ⟨gens⟩ = ALL of S{n} (COXETER-COMPLETENESS at grade {n})." if full
                else f" (a proper subgroup of S{n}, order {math.factorial(n)})."))
    L.append("--   Every element carries an explicit generator-word (BFS-shortest); `complete`")
    L.append("--   exhausts the orbit. Imports from catalog/reuse-index.md. Zero postulates/holes.")
    L.append("------------------------------------------------------------------------")
    L.append(""); L.append("{-# OPTIONS --safe --without-K #-}"); L.append("")
    L.append(f"module {module} where"); L.append("")
    L.extend(_eq_imports(homes, need)); L.append("")
    L.append(f"-- the {k} orbit elements (e0 = id, BFS order):")
    L.append(f"{' '.join(names)} : Perm {n}")
    for nm, e in zip(names, order):
        L.append(f"{nm} = {perm_lit(e)}")
    L.append("")
    # data …Gen: id + one constructor per generator + closure under compose
    L.append(f"data {dtype} : Perm {n} → Set where")
    L.append(f"  gen-id : {dtype} e0")
    for gi in range(len(gens)):
        L.append(f"  gen-g{gi} : {dtype} e{gen_pos[gi]}")
    L.append(f"  gen-∘  : {{σ τ : Perm {n}}} → {dtype} σ → {dtype} τ → {dtype} (compose σ τ)")
    L.append("")
    # per-element word witnesses (parent index < own index, so no forward ref)
    L.append(f"-- every orbit element as an explicit word in the generators:")
    for i in range(k):
        if i == 0:
            rhs = "gen-id"
        elif i in gen_pos:
            rhs = f"gen-g{gen_pos.index(i)}"
        else:
            gi, par = parent[order[i]]
            rhs = f"gen-∘ gen-g{gi} orbit-{idx[par]}"
        L.append(f"orbit-{i} : {dtype} e{i}")
        L.append(f"orbit-{i} = {rhs}")
    L.append("")
    # AllG membership + the completeness bundle
    L.append(f"All{dtype} : Perm {n} → Set")
    L.append(f"All{dtype} σ = {_paren_disj(names)}")
    L.append("")
    tag = "coxeter-complete" if full else "orbit-complete"
    L.append(f"-- {'⟨gens⟩ = Sₙ: every permutation is a generator-word' if full else 'every orbit element is a generator-word'}.")
    L.append(f"{tag} : {{σ : Perm {n}}} → All{dtype} σ → {dtype} σ")
    for m in range(k):
        L.append(f"{tag} ({nest(m, k, 'refl')}) = orbit-{m}")
    L.append("")
    return "\n".join(L), k, full

def emit_cayley(module, n, gens, homes):
    """The complete finite group ⟨gens⟩ as its CAYLEY (multiplication) TABLE: the
    k×k product table exposed as a closure witness whose CLAUSES ARE THE TABLE
    (`mul-table (inj_i refl)(inj_j refl) = inj_{f(i,j)} refl` literally says
    eᵢ·eⱼ = e_{f(i,j)}), plus the inverse map (eᵢ · e_{inv i} ≡ id). Reuses
    closure_of, which already computes the product table. Every fact is `refl`."""
    import math
    ordered, idx, table = closure_of(gens, n)
    k = len(ordered)
    ident = tuple(range(n))
    id_idx = idx[ident]
    names = _elem_names(n, ordered, gens)
    inv = {}
    for i in range(k):
        for j in range(k):
            if table[(i, j)] == id_idx:
                inv[i] = j
                break
    full = (k == math.factorial(n))
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "Perm", "id-perm", "compose"]
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append("-- `cayley` class — the complete finite group ⟨gens⟩ as its multiplication table).")
    L.append(f"--   grade {n}; generators {[list(g) for g in gens]}; |⟨gens⟩| = {k}"
             + (f" = {n}! (= S{n})." if full else f" (a subgroup of S{n}, order {math.factorial(n)})."))
    L.append("--   `mul-table` IS the Cayley table (each clause eᵢ·eⱼ = e_{f(i,j)}); `inv-*` the")
    L.append("--   inverse map (eᵢ·e_{inv i} ≡ e0 = id). All refl. Imports from catalog/reuse-index.md.")
    L.append("------------------------------------------------------------------------")
    L.append(""); L.append("{-# OPTIONS --safe --without-K #-}"); L.append("")
    L.append(f"module {module} where"); L.append("")
    L.extend(_eq_imports(homes, need)); L.append("")
    L.append(f"-- the {k} group elements (e0 = id):")
    L.append(f"{' '.join(names)} : Perm {n}")
    for nm, e in zip(names, ordered):
        L.append(f"{nm} = {perm_lit(e)}")
    L.append("")
    L.append(f"S : Perm {n} → Set")
    L.append(f"S σ = {_paren_disj(names)}"); L.append("")
    L.append(f"-- THE CAYLEY TABLE: every product of two elements is a specific element")
    L.append(f"-- (the {k}×{k} clauses below ARE the multiplication table; also proves closure).")
    L.append(f"mul-table : {{a b : Perm {n}}} → S a → S b → S (compose a b)")
    for i in range(k):
        for j in range(k):
            L.append(f"mul-table ({nest(i, k, 'refl')}) ({nest(j, k, 'refl')}) = {nest(table[(i, j)], k, 'refl')}")
    L.append("")
    L.append(f"-- the inverse map: eᵢ · e_{{inv i}} ≡ e0 (= id-perm {n} = id).")
    for i in range(k):
        L.append(f"inv-{i} : compose {names[i]} {names[inv[i]]} ≡ {names[id_idx]}")
        L.append(f"inv-{i} = refl")
    L.append("")
    return "\n".join(L), k, full

def emit_reconstruct(module, target):
    """SYNTHESIZE the Set₀ reconstruction of a Set₁ target as a TRUNCATION of its
    graded (grade-exposed) form — the ⟡pipeline-driver-reconstruct class. The shape
    is supplied by the mechanical search (numpy verifies the correspondence; jea_pysim
    locates the carrier-hole C:ℕ→Set + the graded field), NOT typechecker trial-and-error.
    First located target: `refinement` (Category.Allegory.Refinement, Fam-operator Set₁)."""
    if target != "refinement":
        raise SystemExit(f"[abort] no located reconstruction spec for target '{target}' "
                         f"(known: refinement). Locate it first (numpy + jea_pysim).")
    # ── the located shape for `refinement` (numpy: Φ-chain C n = Φⁿ R⁰ is a descending
    #    graded family, grade IS the chain; jea_pysim: carrier C:ℕ→Set, step (n)→C(suc n)→C n).
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append("-- `reconstruct` class) — the Set₀ reconstruction of `Substrate.Category.Allegory")
    L.append("-- .Refinement` (ALG-7 — the monotone Φ-operator on FIBER FAMILIES; NB this is NOT the")
    L.append("-- unrelated `Substrate.Category.UniversalProperty.Refinement`, which is cover-refinement).")
    L.append("-- Substrate-only imports (no stdlib). It is Set₁, and we reconstruct it as a TRUNCATION")
    L.append("-- of its graded, grade-EXPOSED form. The shape was located")
    L.append("-- MECHANICALLY: numpy verified the Φ-chain C n = Φⁿ R⁰ is a DESCENDING graded")
    L.append("-- family (Rⁿ⁺¹ ⊑ Rⁿ; the grade IS the chain, over all subsets of Fin 4); jea_pysim")
    L.append("-- located the carrier-hole C : ℕ→Set + the graded field (n)→C(suc n)→C n.")
    L.append("--")
    L.append("-- Refinement's Set₁ is the GRADE-COLLAPSE: it holds Φ : Fam A → Fam A (Fam A =")
    L.append("-- A → Set : Set₁) instead of the graded C : ℕ→Set. GRefinement EXPOSES the grade")
    L.append("-- (C a MODULE PARAM ⇒ the record lands at `: Set`, the paydown), and `reify` shows")
    L.append("-- Refinement REIFIES to it (the 'build MORE' — the constructive graded chain). The")
    L.append("-- RESIDUE is the grade n itself: recovering the ABSTRACT Φ-operator back from the")
    L.append("-- graded form re-quantifies over Fam (Set₁) — that Set₁ is exactly the grade the")
    L.append("-- truncation drops. This closes the arc's 'IDENTIFIED NOT YET PROVEN' ALG-7 chain")
    L.append("-- deferral to the reification degree. Zero postulates, zero holes, --safe --without-K.")
    L.append("------------------------------------------------------------------------")
    L.append("")
    L.append("{-# OPTIONS --safe --without-K #-}")
    L.append("")
    L.append(f"module {module} where")
    L.append("")
    L.append("open import Substrate.Foundation.Nat using (ℕ; zero; suc)")
    L.append("open import Substrate.Category.Allegory.Refinement")
    L.append("  using (Refinement; Fam; iterate; _⊑ᶠ_)")
    L.append("open Refinement using (Φ; mono)   -- Φ/mono are record field projections")
    L.append("")
    L.append("-- THE RICH Set₀ RECONSTRUCTION: the grade EXPOSED as a graded family. C : ℕ → Set")
    L.append("-- is a MODULE PARAMETER (not a held field), so the bundle lands at `: Set` — NOT")
    L.append("-- Set₁. That green compile at `: Set` IS the Set₁ paydown.")
    L.append("module _ (C : ℕ → Set) where")
    L.append("  record GRefinement : Set where")
    L.append("    field")
    L.append("      step : (n : ℕ) → C (suc n) → C n")
    L.append("")
    L.append("-- the descent chain (Refinement.mono + a pre-fixed-point Φ R⁰ ⊑ R⁰): Rⁿ⁺¹ ⊑ᶠ Rⁿ.")
    L.append("descend : {A : Set} (r : Refinement A) (R⁰ : Fam A) →")
    L.append("          Φ r R⁰ ⊑ᶠ R⁰ → (n : ℕ) → iterate r (suc n) R⁰ ⊑ᶠ iterate r n R⁰")
    L.append("descend r R⁰ pre zero    = pre")
    L.append("descend r R⁰ pre (suc n) = mono r (descend r R⁰ pre n)")
    L.append("")
    L.append("-- REIFY (the 'build MORE'): Refinement's abstract Φ-operator, at a pre-fixed-point")
    L.append("-- R⁰ and a point a, reifies to the graded, grade-exposed form. The graded step at")
    L.append("-- n is the descent Rⁿ⁺¹ ⊑ Rⁿ read at a.")
    L.append("reify : {A : Set} (r : Refinement A) (R⁰ : Fam A) →")
    L.append("        Φ r R⁰ ⊑ᶠ R⁰ → (a : A) → GRefinement (λ n → iterate r n R⁰ a)")
    L.append("reify r R⁰ pre a = record { step = λ n → descend r R⁰ pre n a }")
    L.append("")
    return "\n".join(L)

def _parse_set1_record(source_path, record_name):
    """Read an Agda source, locate `record <record_name> ... : Set₁ where`, and return
    (imports, constructor, fields) — fields as (name, type) pairs, comment-stripped. The
    carrier fields (type == 'Set') are the Set₁ cause; the rest are carried verbatim."""
    import re
    lines = open(source_path, encoding="utf-8").read().splitlines()
    imports = [l for l in lines if l.startswith("open import") or l.startswith("import ")]
    # find the record header
    ri = next((i for i, l in enumerate(lines)
               if re.match(rf"\s*record\s+{re.escape(record_name)}\b", l) and "Set₁" in l), None)
    if ri is None:
        raise SystemExit(f"[abort] no `record {record_name} : Set₁` in {source_path}")
    ctor = None
    fields = []
    in_field = False
    for l in lines[ri+1:]:
        s = re.sub(r"--.*$", "", l).rstrip()          # strip line comments
        if not s.strip():
            continue
        indent = len(l) - len(l.lstrip())
        if indent == 0:                                # dedent to col 0 → record block ended
            break
        m = re.match(r"\s*constructor\s+(\S+)", s)
        if m:
            ctor = m.group(1); continue
        if re.match(r"\s*field\b", s):
            in_field = True; continue
        if in_field:
            fm = re.match(r"\s*([^\s:]+)\s*:\s*(.+)$", s)
            if fm:
                fields.append((fm.group(1), fm.group(2).strip()))
    return imports, ctor, fields

def emit_reconstruct_m1(module_out, source_path, record_name):
    """GENERAL M1 reconstruction: parse a `record R : Set₁` whose Set₁ cause is a bare-`Set`
    carrier FIELD, and emit the Set₀ reconstruction with that carrier HOISTED to a module
    PARAMETER (set1-carrier-always-parameterize). The record then lands at `: Set` — the
    paydown. The original = this at a re-fielded carrier (Σ Set Rₚ); the RESIDUE is the
    held carrier. Mechanical: parses the target; no typechecker search."""
    imports, ctor, fields = _parse_set1_record(source_path, record_name)
    carriers = [nm for nm, ty in fields if ty.strip() == "Set"]
    if not carriers:
        raise SystemExit(f"[abort] {record_name} fields no bare-`Set` carrier (not an M1 target); "
                         f"fields: {[(n,t) for n,t in fields]}")
    rest = [(nm, ty) for nm, ty in fields if ty.strip() != "Set"]
    rn = record_name + "ₚ"
    # RESIDUE detection: a non-carrier field whose type references a CAPITALISED name that is
    # not the carrier / not Foundation is a potential TRANSITIVE Set₁ (M2) — parameterising the
    # carrier alone won't reach Set₀; those types must be reconstructed first (recursively).
    import re as _re
    # not-residue: the carriers, the record's OWN field names (values, not Set₁ types), + Foundation.
    _found = set(carriers) | {nm for nm, _ in fields} | {"Set", "ℕ", "Fin", "Bool", "List", "Vec", "Maybe", "Σ"}
    residue = set()
    for _nm, ty in rest:
        for tok in _re.findall(r"[A-Z][A-Za-z0-9]*", ty):
            if tok not in _found:
                residue.add(tok)
    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module_out}")
    L.append("--")
    L.append(f"-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver,")
    L.append(f"-- `reconstruct` class, M1 carrier-parameterization) — the Set₀ reconstruction of")
    L.append(f"-- `{record_name}` (Set₁). Located mechanically: the Set₁ cause is the bare-`Set`")
    L.append(f"--   carrier field(s) {carriers} — a HELD carrier. Hoisting it to a MODULE PARAMETER")
    L.append(f"--   (set1-carrier-always-parameterize) lands the record at `: Set`. That green `: Set`")
    L.append(f"--   compile IS the Set₁ paydown. The original `{record_name}` = this at a re-fielded")
    L.append(f"--   carrier (Σ Set {rn}); the RESIDUE is exactly the held carrier {carriers}.")
    if residue:
        L.append(f"-- ⚠ TRANSITIVE RESIDUE (M1+M2): non-carrier fields reference {sorted(residue)}, which")
        L.append(f"--   are themselves Set₁ — parameterising the carrier alone will NOT reach Set₀; those")
        L.append(f"--   types must be reconstructed FIRST (recursively). This module is then the scaffold.")
    L.append("-- Substrate-only imports (carried from the target). Zero postulates, --safe --without-K.")
    L.append("------------------------------------------------------------------------")
    L.append("")
    L.append("{-# OPTIONS --safe --without-K #-}")
    L.append("")
    L.append(f"module {module_out} where")
    L.append("")
    L.extend(imports)
    L.append("")
    L.append(f"-- carrier(s) {carriers} hoisted to a module PARAMETER ⇒ the record lands at `: Set`.")
    L.append(f"module _ ({' '.join(carriers)} : Set) where")
    L.append(f"  record {rn} : Set where")
    if ctor:
        L.append(f"    constructor {ctor}ₚ")
    L.append("    field")
    for nm, ty in rest:
        L.append(f"      {nm} : {ty}")
    L.append("")
    return "\n".join(L), carriers, rn, sorted(residue)

# ── driver ───────────────────────────────────────────────────────────────────

def parse_perm(s):
    return tuple(int(x) for x in s.replace(" ", "").split(","))

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--class", dest="cls", default="nonmembership",
                    choices=["nonmembership", "equation", "residue", "orbit", "cayley", "reconstruct"],
                    help="prototype SHAPE (the perm classes share the enumerate→resolve→emit core): "
                         "nonmembership (¬ target∈⟨gens⟩); equation (LHS≡RHS or its counterexample); "
                         "residue (the wedge δ=LHS·RHS⁻¹, the path of paths); "
                         "orbit (the FULL group ⟨gens⟩ mapped as generator-words — Coxeter-completeness if =Sₙ); "
                         "cayley (the complete group as its multiplication table + inverse map); "
                         "reconstruct (the Set₀ reconstruction of a Set₁ target as a truncation of its graded form)")
    ap.add_argument("--gname", default="Gen", help="[orbit] the generated-subgroup data type name")
    ap.add_argument("--recon-target", dest="recon_target",
                    help="[reconstruct] a builtin located Set₁ target (e.g. 'refinement')")
    ap.add_argument("--recon-source", dest="recon_source",
                    help="[reconstruct, general M1] path to the target Agda source (carrier-parameterization)")
    ap.add_argument("--recon-record", dest="recon_record",
                    help="[reconstruct, general M1] the Set₁ record name to reconstruct")
    ap.add_argument("--grade", type=int, help="[perm classes] n (perms of Fin n)")
    ap.add_argument("--gens", help="[perm classes] generators, ';'-separated perm tuples e.g. '2,0,1;1,2,0'")
    ap.add_argument("--target", help="[nonmembership] element to prove non-member, e.g. '1,0,2'")
    ap.add_argument("--law", help="[equation] a `compose`/`id`/var identity, LHS '=' RHS, "
                                  "e.g. 'compose a b = compose b a' (commutativity of the domain)")
    ap.add_argument("--lawname", default="law", help="[equation] the emitted lemma's name")
    ap.add_argument("--module", default="PermGapPrototype", help="Agda module name")
    ap.add_argument("--out", required=True,
                    help="output path for the synthesized .agda (caller chooses; e.g. a temp or "
                         "generated dir). The module name must match the file's include-path.")
    ap.add_argument("--repo-root", default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
    args = ap.parse_args()

    # reconstruct — a non-perm class: emit the Set₀ reconstruction of a located Set₁ target.
    if args.cls == "reconstruct":
        if args.recon_source and args.recon_record:      # general M1 carrier-parameterization
            src, carriers, rn, residue = emit_reconstruct_m1(args.module, args.recon_source, args.recon_record)
            if residue:
                print(f"[reconstruct] M1+M2 {args.recon_record}: carrier(s) {carriers} hoisted, but "
                      f"TRANSITIVE RESIDUE {residue} (Set₁ field-types) ⇒ {rn} stays Set₁ until those are "
                      f"reconstructed FIRST (recursive). Scaffold emitted; NOT a Set₀ paydown yet.")
            else:
                print(f"[reconstruct] PURE-M1 {args.recon_record}: carrier(s) {carriers} hoisted to module "
                      f"param ⇒ {rn} : Set (Set₀ paydown); residue = the held carrier only")
        elif args.recon_target:                          # builtin located target (e.g. refinement)
            src = emit_reconstruct(args.module, args.recon_target)
            print(f"[reconstruct] builtin '{args.recon_target}': Set₀ graded reconstruction "
                  f"+ reify; residue = the grade (located: numpy + jea_pysim)")
        else:
            sys.exit("[abort] reconstruct needs --recon-target (builtin) OR --recon-source + --recon-record (general M1)")
        out = os.path.join(args.repo_root, args.out) if not os.path.isabs(args.out) else args.out
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(src)
        print(f"[emit] wrote {out}  ({src.count(chr(10))+1} lines)")
        print(f"[typecheck] agda --safe -i {os.path.dirname(args.out)} -i agda {args.out}")
        return

    if args.grade is None or not args.gens:
        sys.exit(f"[abort] --grade and --gens required for --class {args.cls}")
    n = args.grade
    gens = [parse_perm(g) for g in args.gens.split(";")]

    # 1. numpy search (shared): the domain is the generated closure.
    ordered, idx, table = closure_of(gens, n)
    print(f"[numpy] grade-{n} closure ⟨{', '.join(str(list(g)) for g in gens)}⟩ = "
          f"{[list(e) for e in ordered]}  (order {len(ordered)})")
    print(f"[numpy] cycle-types: " + ", ".join(f"{list(e)}↦{cycle_type(e)}" for e in ordered))

    # 2. catalog/dedup resolution (shared).
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "¬_", "Perm", "id-perm", "compose"]
    homes = resolve_homes(need, args.repo_root)
    unresolved = [nm for nm in need if not homes.get(nm)]
    print(f"[catalog] resolved {len(need)-len(unresolved)}/{len(need)} names from reuse-index.md + foundation map"
          + (f"; UNRESOLVED {unresolved}" if unresolved else ""))

    # 3. emit (class-dispatched).
    if args.cls == "nonmembership":
        if not args.target:
            sys.exit("[abort] --target required for --class nonmembership")
        target = parse_perm(args.target)
        in_closure = target in idx
        print(f"[numpy] target {list(target)} cycle-type {cycle_type(target)}; in closure? {in_closure}")
        if in_closure:
            sys.exit("[abort] target IS in the closure — no non-membership witness to synthesize.")
        src = emit_nonmembership(args.module, n, gens, target, ordered, table, homes)
    elif args.cls == "equation":  # emit at whichever polarity holds; a false law is negative space
        if not args.law or "=" not in args.law:
            sys.exit("[abort] --law 'LHS = RHS' required for --class equation")
        lhs_s, rhs_s = args.law.split("=", 1)
        lhs = parse_expr(tokenize_expr(lhs_s)); rhs = parse_expr(tokenize_expr(rhs_s))
        src, polarity, n_holds, n_fails = emit_equation(args.module, n, gens, ordered, homes, lhs, rhs, args.lawname)
        if polarity == "holds":
            print(f"[numpy] identity HOLDS on all {n_holds} assignments → positive lemma")
        else:
            print(f"[numpy] identity FAILS on {n_fails}/{n_holds + n_fails} assignments "
                  f"→ NEGATIVE-SPACE witness (counterexample refutation, a constraint to cover)")
    elif args.cls == "residue":  # the path of paths: the wedge defect δ = LHS·RHS⁻¹ over the domain
        if not args.law or "=" not in args.law:
            sys.exit("[abort] --law 'LHS = RHS' required for --class residue")
        lhs_s, rhs_s = args.law.split("=", 1)
        lhs = parse_expr(tokenize_expr(lhs_s)); rhs = parse_expr(tokenize_expr(rhs_s))
        src, holds, spec = emit_residue(args.module, n, gens, ordered, homes, lhs, rhs, args.lawname)
        print(f"[numpy] wedge residue δ=LHS·RHS⁻¹: δ=id on {holds} assignment(s) (the equation locus); "
              f"|im δ|={spec} (the path of paths — "
              f"{'δ≡id, holds everywhere' if spec == 1 else 'non-trivial defect spectrum'}); "
              f"recon LHS≡compose δ RHS holds identically")
    elif args.cls == "orbit":  # fully map ⟨gens⟩ as generator-words (Coxeter-completeness if orbit = Sₙ)
        import math
        src, korb, full = emit_orbit(args.module, n, gens, homes, args.gname)
        print(f"[numpy] orbit ⟨gens⟩ mapped: |orbit|={korb}"
              + (f" = {n}! → ⟨gens⟩ = ALL of S{n} (COXETER-COMPLETENESS at grade {n})"
                 if full else f" (proper subgroup; |S{n}|={math.factorial(n)})")
              + "; every element carries an explicit generator-word")
    else:  # cayley — the complete finite group ⟨gens⟩ as its multiplication table + inverse map
        import math
        src, kc, full = emit_cayley(args.module, n, gens, homes)
        print(f"[numpy] Cayley table of ⟨gens⟩: order {kc}"
              + (f" = {n}! (= S{n})" if full else f" (subgroup; |S{n}|={math.factorial(n)})")
              + f"; {kc}×{kc} products + {kc} inverses, all refl")

    out = os.path.join(args.repo_root, args.out) if not os.path.isabs(args.out) else args.out
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(f"[emit] wrote {out}  ({src.count(chr(10))+1} lines)")
    print(f"[typecheck] agda --safe -i {os.path.dirname(args.out)} -i agda {args.out}")

if __name__ == "__main__":
    main()
