#!/usr/bin/env python3
"""synth_agda_prototype.py — ⟡pipeline-driver: numpy ⊗ dedup/catalog → an Agda PROTOTYPE.

The three prior tools STOP at "an LLM writes the Agda" (typeholer_path.py says so in its
HONEST SCOPE). This closes that last step: ONE script that runs the three engines and EMITS
a compiling Agda module.

  1. numpy SEARCH  — enumerate the concrete instance (here: a permutation subgroup and its
     finite closure under `compose`), and VERIFY the target's (non-)membership + the k×k
     product table. This is the "show a solution exists" step, now the synthesis INPUT.
  2. catalog/dedup DB — resolve every Agda name the prototype needs (Perm, compose, id-perm,
     ⊎, ¬, …) to its canonical home by reading `catalog/reuse-index.md` (the dedup machinery's
     product: it is generated by gen_reuse_index.py from the typechecked .agdai cores). The
     deeper structural confirmation is `jea_pysim … --clusters` (see --check-pieces).
  3. EMIT  — write the Agda module: imports (resolved), the concrete Fin-vector literals, the
     ⊎-membership predicate S, the inductively-generated subgroup `data …Gen`, the finite
     closure lemma S-closed (numpy's k×k table, each case `refl`), Gen⊆S, ¬S-target, and the
     witness `¬ …Gen target`.

The synthesized module is a PROTOTYPE in the exact shape of the hand-checked
`Substrate.WitnessTower.Wedge.OrientationRigCatPermGap` (grade-3 witness) — parameterised on
the generators / target / grade, so it re-derives that theorem AND any sibling
(subgroup-non-membership at any grade) mechanically.

Usage (caller chooses --out; e.g. a temp dir, kept out of the promoted tree):
  synth_agda_prototype.py --grade 3 --gens '2,0,1;1,2,0' --target '1,0,2' \
      --module PermGapPrototype --out /tmp/gen/PermGapPrototype.agda
  # then typecheck:  agda --safe -i /tmp/gen -i agda /tmp/gen/PermGapPrototype.agda
"""
from __future__ import annotations
import sys, os, argparse, re
from itertools import product

# ── 1. numpy SEARCH ─────────────────────────────────────────────────────────
# (pure-tuple perm algebra; numpy used if present, but not required — the search
#  is over Sₙ which is finite and small.)

def compose(sigma, tau):
    """(compose σ τ)[i] = σ[τ[i]]  — the tower's `compose` semantics (lookup∘lookup)."""
    return tuple(sigma[tau[i]] for i in range(len(sigma)))

def closure_of(gens, n):
    """The subgroup generated by `gens` (+ identity) under compose. Returns (ordered
    element list with id first then the generators then the rest, index-map, product-table)."""
    ident = tuple(range(n))
    seen = {ident}
    frontier = [ident]
    while frontier:
        x = frontier.pop()
        for g in gens:
            for y in (compose(g, x), compose(x, g)):
                if y not in seen:
                    seen.add(y); frontier.append(y)
    # deterministic order: id, then the generators (in given order), then the rest sorted.
    ordered = [ident]
    for g in gens:
        if g not in ordered:
            ordered.append(g)
    for e in sorted(seen):
        if e not in ordered:
            ordered.append(e)
    idx = {e: i for i, e in enumerate(ordered)}
    table = {(i, j): idx[compose(ordered[i], ordered[j])]
             for i in range(len(ordered)) for j in range(len(ordered))}
    return ordered, idx, table

def cycle_type(p):
    n = len(p); seen = [False]*n; counts = [0]*(n+1)
    for i in range(n):
        if seen[i]:
            continue
        L = 0; j = i
        while not seen[j]:
            seen[j] = True; j = p[j]; L += 1
        counts[L] += 1
    return tuple(counts[1:])

# ── 2. catalog / dedup DB  (import resolution) ───────────────────────────────

# Foundation homes are stable; the domain names are confirmed against reuse-index.md.
FALLBACK_HOME = {
    "Fin": "Substrate.Foundation.Fin", "zero": "Substrate.Foundation.Fin",
    "suc": "Substrate.Foundation.Fin",
    "Vec": "Substrate.Foundation.Vec", "[]": "Substrate.Foundation.Vec",
    "_∷_": "Substrate.Foundation.Vec",
    "_≡_": "Substrate.Foundation.Eq", "refl": "Substrate.Foundation.Eq",
    "_⊎_": "Substrate.Foundation.Sum", "inj₁": "Substrate.Foundation.Sum",
    "inj₂": "Substrate.Foundation.Sum",
    "¬_": "Substrate.Foundation.Negation",
    "Perm": "Substrate.WitnessTower.Enumerate",
    "id-perm": "Substrate.WitnessTower.FirstAppearance",
    "compose": "Substrate.WitnessTower.FirstAppearance",
}

def resolve_homes(names, repo_root):
    """Resolve each name to its canonical Agda home, consulting catalog/reuse-index.md
    (the dedup-derived catalog) first, falling back to the stable foundation map."""
    index_path = os.path.join(repo_root, "catalog", "reuse-index.md")
    index_txt = ""
    if os.path.exists(index_path):
        with open(index_path, encoding="utf-8") as fh:
            index_txt = fh.read()
    homes = {}
    for nm in names:
        home = None
        # catalog lookup: a line `... `Name`@`Module`` or `| Name | ... | Module |`
        m = re.search(r"`" + re.escape(nm) + r"`\s*(?:@|—|·)?\s*`?(Substrate\.[\w.]+)`?", index_txt)
        if m:
            home = m.group(1)
        homes[nm] = home or FALLBACK_HOME.get(nm)
    return homes

# ── 3. EMIT  ─────────────────────────────────────────────────────────────────

def fin_lit(v):
    """A Fin literal: 0→zero, 1→suc zero, 2→suc (suc zero), …"""
    if v == 0:
        return "zero"
    inner = fin_lit(v - 1)
    return "suc " + (f"({inner})" if v - 1 > 0 else "zero")

def perm_lit(p):
    return " ∷ ".join(fin_lit(v) for v in p) + " ∷ []"

def nest(m, k, inner):
    """Select the m-th of k right-nested ⊎ slots, wrapping `inner` (a value or pattern).
    m<k-1: inj₂^m (inj₁ inner);  m==k-1: inj₂^m inner."""
    if k == 1:
        return inner
    if m < k - 1:
        s = "inj₁ " + inner
        for _ in range(m):
            s = "inj₂ (" + s + ")"
        return s
    else:  # last slot: all inj₂
        s = inner
        for _ in range(m):
            s = "inj₂ (" + s + ")"
        return s

def emit(module, n, gens, target, ordered, table, homes):
    k = len(ordered)
    ident = tuple(range(n))
    # element names: e0 = id, generators keep g-names, rest h-names
    names = []
    for i, e in enumerate(ordered):
        if e == ident:
            names.append("p-id")
        elif e in gens:
            names.append(f"p-g{gens.index(e)+1}")
        else:
            names.append(f"p-h{i}")
    tname = "t-tgt"
    gen_dtype = module.split(".")[-1] + "Gen" if False else "BraidGen"

    # imports grouped by home
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "¬_", "Perm", "id-perm", "compose"]
    by_home = {}
    for nm in need:
        h = homes.get(nm)
        by_home.setdefault(h, []).append(nm)
    import_lines = []
    for h in ["Substrate.Foundation.Fin", "Substrate.Foundation.Vec",
              "Substrate.Foundation.Eq", "Substrate.Foundation.Sum",
              "Substrate.Foundation.Negation", "Substrate.WitnessTower.Enumerate",
              "Substrate.WitnessTower.FirstAppearance"]:
        if h in by_home:
            import_lines.append(f"open import {h} using ({'; '.join(by_home[h])})")

    L = []
    L.append("------------------------------------------------------------------------")
    L.append(f"-- {module}")
    L.append("--")
    L.append("-- SYNTHESIZED by jea/metalanguage/synth_agda_prototype.py (⟡pipeline-driver):")
    L.append("--   numpy enumerated the grade-%d braiding subgroup ⟨%s⟩ = C%d (order %d, closed" %
             (n, ", ".join(str(list(g)) for g in gens), k, k))
    L.append("--   under compose); the target %s is NOT in it. Imports resolved from" % (list(target),))
    L.append("--   catalog/reuse-index.md. Each closure case is `refl`; the target disequalities")
    L.append("--   are constructor-distinct `()`. Zero postulates, zero holes, --safe --without-K.")
    L.append("------------------------------------------------------------------------")
    L.append("")
    L.append("{-# OPTIONS --safe --without-K #-}")
    L.append("")
    L.append(f"module {module} where")
    L.append("")
    L.extend(import_lines)
    L.append("")
    L.append(f"-- the {k} concrete grade-{n} group elements and the target.")
    sig = " ".join(names + [tname])
    L.append(f"{sig} : Perm {n}")
    for nm, e in zip(names, ordered):
        L.append(f"{nm} = {perm_lit(e)}")
    L.append(f"{tname} = {perm_lit(target)}")
    L.append("")
    # S predicate
    disj = " ⊎ ".join(f"(σ ≡ {nm})" for nm in names)
    # right-nest the parenthesisation
    def paren_disj(nms):
        if len(nms) == 1:
            return f"(σ ≡ {nms[0]})"
        return f"(σ ≡ {nms[0]}) ⊎ ({paren_disj(nms[1:])})"
    L.append(f"S : Perm {n} → Set")
    L.append(f"S σ = {paren_disj(names)}")
    L.append("")
    # data …Gen
    L.append(f"data {gen_dtype} : Perm {n} → Set where")
    L.append(f"  gen-id : {gen_dtype} p-id")
    for gi, g in enumerate(gens):
        L.append(f"  gen-g{gi+1} : {gen_dtype} p-g{gi+1}")
    L.append(f"  gen-∘  : {{σ τ : Perm {n}}} → {gen_dtype} σ → {gen_dtype} τ → {gen_dtype} (compose σ τ)")
    L.append("")
    # S-closed (k×k table)
    L.append(f"S-closed : {{σ τ : Perm {n}}} → S σ → S τ → S (compose σ τ)")
    for i in range(k):
        for j in range(k):
            lhs_i = nest(i, k, "refl"); lhs_j = nest(j, k, "refl")
            rhs = nest(table[(i, j)], k, "refl")
            L.append(f"S-closed ({lhs_i}) ({lhs_j}) = {rhs}")
    L.append("")
    # Gen⊆S
    L.append(f"Gen⊆S : {{σ : Perm {n}}} → {gen_dtype} σ → S σ")
    id_idx = ordered.index(ident)
    L.append(f"Gen⊆S gen-id      = {nest(id_idx, k, 'refl')}")
    for gi, g in enumerate(gens):
        L.append(f"Gen⊆S gen-g{gi+1}      = {nest(ordered.index(g), k, 'refl')}")
    L.append(f"Gen⊆S (gen-∘ g h) = S-closed (Gen⊆S g) (Gen⊆S h)")
    L.append("")
    # ¬S-target
    L.append(f"¬S-tgt : ¬ S {tname}")
    for m in range(k):
        L.append(f"¬S-tgt ({nest(m, k, '()')})")
    L.append("")
    # witness
    L.append(f"witness : ¬ {gen_dtype} {tname}")
    L.append(f"witness g = ¬S-tgt (Gen⊆S g)")
    L.append("")
    return "\n".join(L)

# ── driver ───────────────────────────────────────────────────────────────────

def parse_perm(s):
    return tuple(int(x) for x in s.replace(" ", "").split(","))

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--grade", type=int, required=True, help="n (perms of Fin n)")
    ap.add_argument("--gens", required=True, help="generators, ';'-separated perm tuples e.g. '2,0,1;1,2,0'")
    ap.add_argument("--target", required=True, help="the element to prove non-member, e.g. '1,0,2'")
    ap.add_argument("--module", default="PermGapPrototype", help="Agda module name")
    ap.add_argument("--out", required=True,
                    help="output path for the synthesized .agda (caller chooses; e.g. a temp or "
                         "generated dir). The module name must match the file's include-path.")
    ap.add_argument("--repo-root", default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
    args = ap.parse_args()

    n = args.grade
    gens = [parse_perm(g) for g in args.gens.split(";")]
    target = parse_perm(args.target)

    # 1. numpy search
    ordered, idx, table = closure_of(gens, n)
    in_closure = target in idx
    print(f"[numpy] grade-{n} closure ⟨{', '.join(str(list(g)) for g in gens)}⟩ = "
          f"{[list(e) for e in ordered]}  (order {len(ordered)})")
    print(f"[numpy] cycle-types: " + ", ".join(f"{list(e)}↦{cycle_type(e)}" for e in ordered))
    print(f"[numpy] target {list(target)} cycle-type {cycle_type(target)}; in closure? {in_closure}")
    if in_closure:
        sys.exit("[abort] target IS in the closure — no non-membership witness to synthesize.")

    # 2. catalog/dedup resolution
    need = ["Fin", "zero", "suc", "Vec", "[]", "_∷_", "_≡_", "refl",
            "_⊎_", "inj₁", "inj₂", "¬_", "Perm", "id-perm", "compose"]
    homes = resolve_homes(need, args.repo_root)
    unresolved = [nm for nm in need if not homes.get(nm)]
    print(f"[catalog] resolved {len(need)-len(unresolved)}/{len(need)} names from reuse-index.md + foundation map"
          + (f"; UNRESOLVED {unresolved}" if unresolved else ""))

    # 3. emit
    src = emit(args.module, n, gens, target, ordered, table, homes)
    out = os.path.join(args.repo_root, args.out) if not os.path.isabs(args.out) else args.out
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(src)
    print(f"[emit] wrote {out}  ({src.count(chr(10))+1} lines)")
    print(f"[typecheck] agda --safe -i {os.path.dirname(args.out)} -i agda {args.out}")

if __name__ == "__main__":
    main()
